### ISSUE TITLE
Second argument in `validate()` (Context) is not optional

### ISSUE THREAD

**Issue by wereHamster** [gcanti/io-ts#113]
Two things confused me:

 - The examples in the readme don't typecheck, they call validate with the type as second argument (eg. `validate(…, Person)`. But the context is an array, so it should be at the very least `[Person]`, not?
 - Some comments in the source call validate with just one argument (eg. `validate(x).fold(() => x, serialize) = x`).

Given that an empty array is a reasonable default value when invoking validate from my own code., can we make an empty array the default value?

**Comment by gcanti** [comment]
- the examples use the top level `t.validate` function https://github.com/gcanti/io-ts/blob/0ff24bea1dc7e864366b72ee0b7c70fdb720ec00/src/index.ts#L106
- I guess should be

```ts
/**
 * Laws:
 * 1. validate(x, T).fold(() => x, T.serialize) = x
 * 2. validate(T.serialize(x), T) = Right(x)
 *
 * where `T` is a runtime type
 */
```
