### ISSUE TITLE
Optimize comparison of union of literals

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#124]
The idea would be to speed up dramatically such unions:
```typescript
  t.union([t.literal('a'),t.literal('b'),t.literal('c),t.literal('d')])
```
maybe using something like:

```typescript
t.literals(['a', 'b', 'c', 'd'])
```

The idea would be to rely on a fast object lookup and not having to iterate through each io-ts definition.

I'm not sure about differentiating between literals of string or number (I would be in favor of allowing to mix those freely).

**Comment by gcanti** [comment]
with string literals you can use `t.keyof`

**Comment by sledorze** [comment]
Oh true!
Hummm let's close it.
