### ISSUE TITLE
Support request: exhaustive check on taggeUnion 

### ISSUE THREAD

**Issue by gunzip** [gcanti/io-ts#127]
Is there any way to do a statically-checked exhaustive check (switch) on taggedUnion(s) ?

ref. https://basarat.gitbooks.io/typescript/docs/types/discriminated-unions.html

**Comment by gcanti** [comment]
@gunzip not sure what you mean by that, could you please elaborate?

**Comment by gunzip** [comment]
I've answered myself, I meant something like the switch case here:

```
import * as t from "io-ts";

const A = t.type({
  foo: t.string,
  tag: t.literal("A")
});

type A = t.TypeOf<typeof A>;

const B = t.type({
  bar: t.number,
  tag: t.literal("B")
});

type B = t.TypeOf<typeof B>;

const U = t.taggedUnion("tag", [A, B]);

type U = t.TypeOf<typeof U>;

const aOrB: A = {
  foo: "foo",
  tag: "A"
};

const f = (u: U): U => {
  switch (u.tag) {
    case "A":
      return u;
    case "B":
      return u;
    default:
      const _: never = u;
      return _;
  }
};

f(aOrB);

```

**Comment by gcanti** [comment]
AFAIK this is not necessary

```ts
    default:
      const _: never = u
      return _
```

**Comment by gunzip** [comment]
it's useful because you get an error from typescriptchecker  if you don't handle all the possible switch cases (tags)

**Comment by gcanti** [comment]
TypeScript already does that (try to remove both the `default` and `case "B"` cases and you'll see TypeScript complaining)

**Comment by gunzip** [comment]
mmm it looks like it doesn't (at least in vscode):

![image](https://user-images.githubusercontent.com/148224/36026699-86c5cd92-0d98-11e8-84ff-8f1c169f031b.png)

![image](https://user-images.githubusercontent.com/148224/36026714-9636cf06-0d98-11e8-9d17-02dcb3d4ee7d.png)

Only in the first case I get 

> [ts] Il tipo 'InterfaceOf<{ bar: NumberType; }> & InterfaceOf<{ tag: LiteralType<"B">; }>' non è assegnabile al tipo 'never'.
> const _: never

**Comment by gcanti** [comment]
Weird. Make sure `strictNullChecks` (or even better the umbrella flag `strict`) is `true` in your `tsconfig.json`

**Comment by gunzip** [comment]
I confirm I've strict: true in my tsconfig.json:

https://github.com/teamdigitale/digital-citizenship-functions/blob/master/tsconfig.json
