### ISSUE TITLE
[Enhancement] Simple "Literal Union" type

### ISSUE THREAD

**Issue by aselbie** [gcanti/io-ts#128]
I'm arriving to `io-ts` via `prop-types-ts` (which is super cool, by the way 😄 ). We have a shared component library which some teams are consuming from TypeScript and others are not. I'm exploring whether `prop-types-ts` would be a fit, and one thing that jumps out at me is the verbosity of unions of literals, which we use heavily.

Taken directly from the README we have:
```ts
const AlertType = t.keyof(
  {
    success: true,
    warning: true,
    info: true
  },
  'AlertType'
)

const RuntimeProps = t.interface(
  {
    type: AlertType
  },
  'Props'
)
```

I think it is also equally valid to do:
```ts
const RuntimeProps = t.interface(
  {
    type: t.union([t.literal('success'), t.literal('warning'), t.literal('info')]),
  },
  'Props'
)
```

But an even further improvement, from an API standpoint would be:
```ts
const RuntimeProps = t.interface(
  {
    type: t.literalUnion(['primary', 'secondary', 'info']),
  },
  'Props'
)
```

Is this something you would consider adding?

**Comment by gcanti** [comment]
One advantage of `keyof` over `union` is the uniqueness check

```ts
const MyProps = t.interface(
  {
    type: t.keyof({
      success: null,
      warning: null,
      info: null,
      success: null // static error: Duplicate identifier 'success'
    })
  },
  'MyProps'
)
```

> Is this something you would consider adding?

I would prefer to keep it external to the core library
