### ISSUE TITLE
More optimization (breaking change)

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#136]
@gcanti please find in https://github.com/gcanti/io-ts/tree/optimize-breaking branch further speedup (going from 650 k op/s to 1 M op/s).

There's a test that no more pass (reporting wording), it may be something stupid but I'm running out of time and energy ATM.

Waiting for your feedback before investing more on it.

(from there, there may be further optimisation, I've not profiled that implementation)

**Comment by sledorze** [comment]
@gcanti I've added more optimizations.
Going from 1M op/s to 1.2 M op/s
These are also breaking changes and one of them modify considerably the User facing types, it's done so as an experiment.

**Comment by sledorze** [comment]
@gcanti 
Wow, I've got a huge boost: 3.6 M op/s by just pre flatenning out props so that we can parse it as array.
(I've just done that on interfaces for the moment so we can gain some more speed..).

**Comment by gcanti** [comment]
Great results @sledorze, thanks for working on this. 

Breaking changes are **excluded** at the moment, at least until TypeScript 2.8 is out (*), but hopefully some of these tweaks might be backward compatible (namely the last one).

(*) some new features like conditional types might allow for more ergonomic APIs (e.g. for optional fields) so we could get a chance to introduce breaking changes motivated  by more reasons than mere performance

**Comment by sledorze** [comment]
@gcanti My thinking:

1) The fist one is very desirable I think; so should be part of next breaking release IMHO. Also it exposes the errors results in a factorised, hierarchical way allowing better usage of reports while consuming a lot less memory (lower GC pressure) and well, it's a 50% speedup.
2) The second one; avoiding Right's construction is not desirable as it breaks too much for a 20% increase.
3) The last one is generalisable (more than interfaces) and can be applied without any breaking; I don't know the exact impact but may be around 25%.

(All gains being relative to the state of the previous phase optimisation).

My proposal; backport 3 and we can keep this branch to reconsider 1 after TS 2.8.

**Comment by gcanti** [comment]
@sledorze Agreed. Working on a PR that removes all `for ... in ...` loops

**Comment by gcanti** [comment]
> while consuming a lot less memory (lower GC pressure)

@sledorze speaking of which, I got a change I want to discuss about, when https://github.com/gcanti/io-ts/pull/137 is merged, that _looks_ backward compatible, memory friendly, and leads to 1M op/s

**Comment by sledorze** [comment]
@gcanti sorry for the delay, I've merged it

**Comment by sledorze** [comment]
@gcanti can go from 1570k op/s to 1622k op/s by making sure to avoid 'export' variable access indirection.
ex in the context of this branch : `export.isLeft(...)` => `isLeft(...)`
That may implies some way to inject 'dependencies'

**Comment by gcanti** [comment]
@sledorze I'm trying the `optimize-breaking` branch but there's something wrong

```ts
const T = t.type({
  a: t.string,
  b: t.string
})

const invalidPaylod = { a: 'a', b: 1 }

console.log(PathReporter.report(T.decode(invalidPaylod)))
// [ 'No errors!' ]
```

**Comment by sledorze** [comment]
@gcanti oh.. it may :(
I've tried to change the code incrementally and make it pass the tests just to see the perf.
Maybe it should be debugged or done again from scratch with a cleaner approach (I was in a 'hacky' mindset).

**Comment by sledorze** [comment]
@gcanti at which commit are you testing btw ?

**Comment by gcanti** [comment]
> at which commit are you testing btw ?

the last one: "flatten props as array" 8db4354f16a7aac8c22b288991510d9e1883dda6

**Comment by sledorze** [comment]
@gcanti Oh yes, wait, I forgot to push the fix of the 'typo'

**Comment by sledorze** [comment]
@gcanti I've commited it!

**Comment by sledorze** [comment]
@gcanti for information, there's one test not passing, something strange with error reporting where I need to specify an additional space (so I guess nothing fundamental) I may pass more time on it based on your feedback and your 'gut' about a 'continue-from-there' / 're-write' / 'lets-look-somewhere-else'

**Comment by sledorze** [comment]
@gcanti maybe what you're looking for is just at commit https://github.com/gcanti/io-ts/commit/1e2438cfbc9ca66255d7dcba3a0df0594a0319e5 
This is the first modification, which leads to the 1 M op/sec.

Btw the one that remove Right is not safe in its current incarnation and maybe not desirable.
The one after that flatten iteration is partially implemented and you've also already done it on master.
