### ISSUE TITLE
Suggestion: add `unchecked` type

### ISSUE THREAD

**Issue by phiresky** [gcanti/io-ts#141]
Basically as a way to escape from checking a type, while still having the type present at compile time.

Implementation:

`const unchecked = <T>() => t.any as t.Type<T>;`

Usage:

`const example = unchecked<{a: string, b: number}>();`

I'm using this primarily in my typed socket.io implementation, where I send messages between client and server. The client messages should be type checked, but the server messages don't really need to be since I trust the server. See this as an example: https://github.com/phiresky/typed-socket.io/blob/8eb5b7fb22279692d6e033de59cbaaee0c6ff520/example/chat-with-runtime-checks/common.ts#L10-L29

**Comment by gcanti** [comment]
Honestly this seems to go against the very spirit of this project, I would prefer to keep it external to the core library
