### ISSUE TITLE
t.array(t.string), t.Array not working on large objects

### ISSUE THREAD

**Issue by valvic66** [gcanti/io-ts#156]
Hello @gcanti,

I have a large JSON coming from the server and the parsed object has a property arrProp of type array of strings.

```
const obj = {
    ...
    propOptional?: 'String',
    arrProp: ['One', 'Two', 'Three']
    ...
};

const runtimeTypeOptional = t.type (
    {
        ...
        propOptional: t.string
        ...
    }
);

const runtimeTypeRequired = t.type (
    {
        ...
        arrProp: t.array(t.string)
        ...
    }
);

export const runtimeType = t.intersection([runtimeTypeOptional, runtimeTypeRequired]);
export type IRuntimeType = t.TypeOf<typeof runtimeType>;
```

When checking at runtime the large object, the validation fails for the property declared in t.type as t.array(t.string) or simply t.Array. However is passing for t.any

I havent's seen any issue open regarding any problem with t.array(t.string) or simply t.Array
Any help in solving this issue would be highly appreciated.

Error screenshot attached:
![error](https://user-images.githubusercontent.com/29757922/38618212-98592d22-3da1-11e8-8b00-3cfa2ab4ac69.png)

**Comment by gcanti** [comment]
@valvic66 could you please put up a repo containing a repro?

**Comment by valvic66** [comment]
Hello @gcanti,

The problem was related to mobX that creates an array of observable.array (array-like object) instead of a real array.
Used toJS() method that solved the problem and test passed successfully.

Thanks for your quick reply and the great job you did with the package.
