### ISSUE TITLE
Add `Integer` type (as refinement of number)

### ISSUE THREAD

**Issue by gcanti** [gcanti/io-ts#16]
```ts
const Integer = t.refinement(t.number, n => n % 1 === 0, 'Integer')

console.log(t.validate(1, Integer)) // => Right(1)
console.log(t.validate(1.1, Integer)) // => Left(...)
```

**Comment by gyzerok** [comment]
I seems to be quite easily implementable by the final consumer of the library. What would you say about trying to keep API surface as small as possible during the early stages?

**Comment by gcanti** [comment]
> What would you say about trying to keep API surface as small as possible during the early stages

Completely agree. 

Though an `Integer` type seems a must for a runtime type checking lib. Also it would show a useful example of what you can achieve with refinements
