### ISSUE TITLE
Incorrect inference of nested objects

### ISSUE THREAD

**Issue by gyzerok** [gcanti/io-ts#17]
### Code sample

```ts
const nestedObj = t.object({
  foo: t.object({
    bar: t.string,
  }),
});

type NestedObj = t.TypeOf<typeof nestedObj>;
```

### Actual behaviour

```ts
type NestedObj = {
  foo: any
}
```

### Expected behaviour

```ts
type NestedObj = {
  foo: {
    bar: string
  }
}
```

**Comment by gcanti** [comment]
Are you using VS Code? The extracted type seems ok

```ts
const x1: NestedObj = {  } // error
const x2: NestedObj = { foo: 1 } // error
const x3: NestedObj = { foo: {} } // error
const x4: NestedObj = { foo: { bar: 1 } } // error
const x5: NestedObj = { foo: { bar: 'bar' } } // ok
```

though the displayed type is loose

**Comment by gyzerok** [comment]
@gcanti ah, yes, I do use VSCode. Issue [about maybe](https://github.com/gcanti/io-ts/issues/19) is related here probably. Is there something we can do to fix it on the library level?

**Comment by gyzerok** [comment]
Hm, actually following compiles for me with 2.1.4.

```ts
const nestedObj = t.object({
  foo: t.object({
    bar: t.string,
  }),
});

type NestedObj = t.TypeOf<typeof nestedObj>;

const value: NestedObj = { foo: 123 };
```

**Comment by gcanti** [comment]
Ah, I'm using 2.2.0

**Comment by gcanti** [comment]
2.1.5 and 2.1.6 seems to work fine

**Comment by gyzerok** [comment]
@gcanti yeah, seem to work for me as well.

**P.S.:** I am wondering what may be the reason for VSCode to show type as `any`.

**Comment by gcanti** [comment]
Not sure, maybe a bug or a known limitation. I'm tweaking the definition of `t.object` to see if I can come up with a workaround

**Comment by gcanti** [comment]
@gyzerok No luck so far. This is a minimal repro

```ts
class Type<T> { t: T }

type TypeOf<T extends Type<any>> = T['t'];

type Props = { [key: string]: Type<any> };

declare function obj<P extends Props>(props: P): Type<{ [K in keyof P]: TypeOf<P[K]> }>;

const str = new Type<string>()

const A = obj({
  a: str
})

type TypeOfA = TypeOf<typeof A> // => { a: string }

const B = obj({
  b: obj({
    c: str
  })
})

type TypeOfB = TypeOf<typeof B> // => { b: { c: string } } but VS Code says { b: any; }

const b1: TypeOfB = {} // error
const b2: TypeOfB = { b: {} } // error
const b3: TypeOfB = { b: { c: 'foo' } } // NO error
```

Do you know if there is the possibility to query tsc and get the inferred type? (something like Flow's `type-at-pos`)

**Comment by gcanti** [comment]
FYI issue filed https://github.com/Microsoft/TypeScript/issues/14041

**Comment by gyzerok** [comment]
Great! Thank you for taking care of this 👍

**Comment by gcanti** [comment]
@gyzerok So, adding an helper type alias

```ts
export type InterfaceOf<P extends Props> = { [K in keyof P]: TypeOf<P[K]> };

export class InterfaceType<P extends Props> extends Type<InterfaceOf<P>> {
  constructor(name: string, validate: Validate<InterfaceOf<P>>, public readonly props: P) {
    super(name, validate)
  }
}
```

Instead of

```ts
type NestedObj = {
  foo: any;
}
```

you see

```ts
type NestedObj = {
  foo: t.InterfaceOf<{
    bar: t.Type<string>;
  }>;
}
```

is ugly but better than `any`. Until the problem will be fixed upstream we could live with this semi-fix, what do you think?

**Comment by gyzerok** [comment]
Yeah, you are right. Ugly thing is less misleading than have any. Should there be some section in the readme which describes why things are working this way, so people do not create multiple issues with the same question? Something like "known issues"?
