### ISSUE TITLE
is there a way to define function type ?

### ISSUE THREAD

**Issue by nielk** [gcanti/io-ts#184]
Is it possible to write something like this ?

```
const RuntimeProps = t.interface({
  name: t.string,
  callback: (name: t.string) => t.undefined,
})
```

With typescript I write

```
interface RuntimeProps {
  readonly name: string
  readonly callback: (name: string) => undefined
}
```

I tried with t.Function but the params type and return type are missing

**Comment by vegansk** [comment]
Are you sure you really need to store the function within the data? How it will be encoded/decoded? How can you check the signature of the function to be sure that it is valid for that field?

**Comment by gcanti** [comment]
> How can you check the signature of the function to be sure that it is valid for that field?

Indeed that's impossible.
