### ISSUE TITLE
Generic Types

### ISSUE THREAD

**Issue by peterharding** [gcanti/io-ts#190]
I've been trying to represent this structure in `io-ts`:
```
export interface Response<T> {
  result: T[];
  _links: Links;
}

export interface Links {
  previous?: string;
  self: string;
  next?: string;
}
```

But after reading the README and trying a few things, I couldn't find a solution.
If there were a solution, I would imagine it to be something like:
```
const Self = iots.interface({
  self: iots.string,
});

const PreviousNext = iots.partial({
  previous: iots.string,
  next: iots.string,
});

export const Links = iots.intersection([Self, PreviousNext]);

const GenericResult = iots.interface<T>({
  result: iots.array(T),
});

export const Response = iots.intersection([GenericResult, Links]);
```
But the `interface<T>` syntax is not understood. Also, unless I misunderstand, recursive types will not solve this problem since they require a static type as a hint (which I don't have for a generic type). 

So, are generic types unsupported, or is there something I'm missing?

**Comment by gcanti** [comment]
You can represent polimorphic runtime types with functions. For example `Array<T>` is represented by (the built-in)

```ts
iots.array: <RT extends Type<any, any, mixed>>(type: RT, name?: string) => ArrayType<RT, RT["_A"][], RT["_O"][], mixed>
```

So in your case

```ts
export const response = <RT extends iots.Mixed>(type: RT) =>
  iots.interface({
    result: iots.array(type),
    _links: Links
  })
```

**Comment by peterharding** [comment]
Thanks @gcanti !
Perhaps this would be a good example to add to the README?

**Comment by gcanti** [comment]
Sure, would you like to send a PR?

**Comment by peterharding** [comment]
Sure! PR created here: https://github.com/gcanti/io-ts/pull/191

**Comment by peterharding** [comment]
Resolved in https://github.com/gcanti/io-ts/pull/191, closing
