### ISSUE TITLE
Apply partial to a type

### ISSUE THREAD

**Issue by MastroLindus** [gcanti/io-ts#192]
Disclaimer: I recently found your library, I just started using it, so maybe I just missed the answer somewhere in the docs, however, is there a reason why I cannot apply partial to a type?

```
const Test = t.type({name: t.string});

const ReadonlyTest = t.readonly(Test); // readonly seems to work with types?

const PartialTest1 = t.partial({name: t.string}) // works but I have to rewrite the type, and I want to avoid that
const PartialTest2 = t.partial(Test); // doesn't, work, partial is not appliable to types?
```

My use case is that I have an object of type T, and API to allow users to update it. The user is allowed to specify his parameters as a Partial<T>, so I would like to validate that.

**Comment by sledorze** [comment]
try
```typescript
const PartialTest2 = t.partial(Test.props)
```

**Comment by gcanti** [comment]
@MastroLindus That's because `partial` is used to implement optional props https://github.com/gcanti/io-ts#mixing-required-and-optional-props
