### ISSUE TITLE
Unexpected validation path from partial type

### ISSUE THREAD

**Issue by mwikstrom** [gcanti/io-ts#195]
Hi. Thanks for providing this lib.

I'm seeing unexpected validation paths when using partial types.

To me it looks like an extra numeric path segment is added to all partial properties, like `a/b/0` instead of just `a/b`.

Please see the following test that reproduce the problem:

~~~~typescript
import * as t from "io-ts";

test("io-ts partial validation", () => {
    // Define a partial type
    const partialType = t.partial({
        a: t.number,
    });

    // Bad input to decode
    const badInput = { a: null };

    // Get validation result
    const result = partialType.decode(badInput);

    // We know there is a single error. Extract its path.
    const path = result.mapLeft(
        errors => errors[0].context.map(context => context.key).filter(key => !!key).join("/"),
    ).value;

    // Path should be `a`. But expectation fails. Actual value is `a/0`
    expect(path).toBe("a"); 
});
~~~~

Is this a bug or is there some reasoning behind that extra path segment?

(I'm using io-ts version 1.2.1)

**Comment by mwikstrom** [comment]
After looking at the implementation I see that partials are described by using unions.

[Line 600](https://github.com/gcanti/io-ts/blob/master/src/index.ts#L600):
~~~~typescript
partials[keys[i]] = union([types[i], undefinedType])
~~~~

So, the problem (if it is one) stems from the fact that the union type appends an integer key to the validation context for each type in the union.

[Line 734](https://github.com/gcanti/io-ts/blob/master/src/index.ts#L734):
~~~~typescript
const validation = type.validate(m, appendContext(c, String(i), type))
~~~~

What's the reason for appending that integer key? To me it looks wierd, but I've just started using this lib, so I might be missing something important.

**Comment by sledorze** [comment]
It is a (correct) feature; the error reported incorporate the failing union entry (here 0), otherwise you would have no clue which entry fails.

**Comment by mwikstrom** [comment]
Ok.

But union entry index (0 or 1) in a partial/optional property path does not make any sense. 

So maybe partials should be implemented in another way?

Maybe by not using unions, or maybe by stripping out that extra path from validation errors?

**Comment by sledorze** [comment]
Maybe by adding a specific solution for partials.
I'm not sure if its worth it.

**Comment by mwikstrom** [comment]
I've added PR #198 that do not use unions in partials. What's your opinion on that?
