### ISSUE TITLE
Make it easier to specify partial types

### ISSUE THREAD

**Issue by tonyxiao** [gcanti/io-ts#196]
There's this amazing tool to generate io-ts from json - https://transform.now.sh/json-to-io-ts

However it doesn't work with optional attributes. The current way (https://github.com/gcanti/io-ts#mixing-required-and-optional-props) of specifying partial is really complex / cumbersome. Could we support syntax like

```ts
const MyType = t.type({
  requiredField: t.number,
  optionalField: t.optional(t.string)
})
```

**Comment by gcanti** [comment]
I wish... (see https://github.com/gcanti/io-ts/issues/140)

**Comment by tonyxiao** [comment]
awww :( That's too bad. Any workaround you would recommend?
