### ISSUE TITLE
Type definition with default

### ISSUE THREAD

**Issue by wmaurer** [gcanti/io-ts#206]
Having used `io-ts` in a recent project. one of the the pain-points we had was optional (nullable) values from an API that we had no control over. In this case we used `createOptionFromNullable`, which started off nicely, but then started to spread its tentacles through much of our system. For example, an `Option<string[]>` was often very annoying to deal with - often (but not always) what we really wanted was simply a `string[]` (i.e. `[]` when `null` or absent key came from the API).

In the next project, I wrote a function called `withDefault`, inspired by what I found in the tests for `io-ts`:

```ts
import * as t from 'io-ts';

export class WithDefault<RT extends t.Any, A = any, O = A, I = t.mixed> extends t.Type<A, O, I> {
    readonly _tag: 'WithDefault' = 'WithDefault';
    constructor(
        name: string,
        is: WithDefault<RT, A, O, I>['is'],
        validate: WithDefault<RT, A, O, I>['validate'],
        serialize: WithDefault<RT, A, O, I>['encode'],
        readonly type: RT,
    ) {
        super(name, is, validate, serialize);
    }
}

export const withDefault = <RT extends t.Type<A, O>, A = any, O = A>(
    type: RT,
    defaultValue: t.TypeOf<RT>,
): WithDefault<RT, t.TypeOf<RT>, t.OutputOf<RT>, t.mixed> => {
    const Nullable = t.union([type, t.null, t.undefined]);
    return new WithDefault(
        name,
        (m): m is t.TypeOf<RT> => type.is(m),
        (s, c) => {
            const validation = Nullable.validate(s, c);
            return validation.isLeft()
                ? (validation as any)
                : t.success(validation.value != null ? validation.value : defaultValue);
        },
        a => type.encode(a),
        type,
    );
};
```

Do you think it would be useful to other users of `io-ts`? I would be happy to create a PR to add this if you do think so.

**Comment by wmaurer** [comment]
Oh, very nice, thanks. I hacked together my `withDefault`  code before you before you made your better `fallback` function available. But now I don't need my code any more. 😎 Cheers.

**Comment by zhaoyao91** [comment]
Hi, but the `withDefault` is diffrent from `withFallback` since it only transform value on `null/undefined`, but not `Left`.
How to support such case with `withFallback`?

**Comment by ssledorze** [comment]
Indeed, `withFallback` makes no distinction and matches all failures.
What you're looking for is something else not derivable from `withFallback` behaviour.

**Comment by zhaoyao91** [comment]
@ssledorze yes, and it is a common use case for decoding of api data. It would be great if there is such a `withDefault` in `io-ts-types`

**Comment by BenLangloisBitGo** [comment]
> Hi, but the `withDefault` is diffrent from `withFallback` since it only transforms value on `null/undefined`, but not `Left`.
> How to support such case with `withFallback`?

@zhaoyao91 I believe what you're looking for is [`fromNullable`](https://github.com/gcanti/io-ts-types/blob/032c569f50a61befcee77412f1745b7bf9874885/src/fromNullable.ts).
```typescript
import { fromNullable } from 'io-ts-types/lib/fromNullable'
import * as t from 'io-ts'
import { right } from 'fp-ts/lib/Either'
import { PathReporter } from 'io-ts/lib/PathReporter'

const T = fromNullable(t.number, -1)

assert.deepStrictEqual(T.decode(1), right(1))
assert.deepStrictEqual(T.decode(null), right(-1))
assert.deepStrictEqual(T.decode(undefined), right(-1))
assert.deepStrictEqual(PathReporter.report(T.decode('a')), ['Invalid value "a" supplied to : fromNullable(number)'])
```
