### ISSUE TITLE
Question: use existing interface in io-ts definition

### ISSUE THREAD

**Issue by alexandervanhecke** [gcanti/io-ts#209]
Hi,
first of all, thanks for your great work, I use fp-ts, io-ts and monocle-ts a lot and it saves a lot of time.

Also, apologies if this has been asked before but I couldn't find an answer in the issues for io-ts.

I just wanted to check if it's possible to re-use existing interfaces within an io-ts definition.  Let's say we have something like this : 

```
export interface Address {
  street: string;
  no: number;
}
```

and I want to reuse it in something like this : 

```
export const Person = t.interface({
  name: t.string;
  address: Address <-- how to make this work?
});
```
Is something like this possible, without having to duplicate Address into something like this : 

```
export const IAddress = t.interface({
  street: t.string,
  no: t.number
});
```

thanks in advance.

**Comment by vegansk** [comment]
If you need encode/decode/validate features, then you must write complete definition. If you don't, use `t.any` :-)

**Comment by sledorze** [comment]
@alexandervanhecke you may use `clean`, usage is depicted here: https://github.com/gcanti/io-ts#solution-the-clean-and-alias-functions

**Comment by sledorze** [comment]
@alexandervanhecke your `Address` interface is a type.
You need to create a io-ts Type to achieve your goal.
Note that you may take advantage of `clean` combinator to reuse your existing interface as depicted here: https://github.com/gcanti/io-ts#solution-the-clean-and-alias-functions

**Comment by alexandervanhecke** [comment]
@sledorze thanks, works like a charm!

**Comment by samywang92** [comment]
Hello! I know this is a 2 year old post however the anchor for https://github.com/gcanti/io-ts#solution-the-clean-and-alias-functions is no longer working.  Is there an updated link to the clean combinator?

**Comment by gcanti** [comment]
@samywang92 https://github.com/gcanti/io-ts/blob/67e302a9d176cc7317d8d131d82ef8c06d16d0bc/README.md#solution-the-clean-and-alias-functions
