### ISSUE TITLE
Overall experience with the library

### ISSUE THREAD

**Issue by gyzerok** [gcanti/io-ts#21]
Hello everyone!

I'd like to wrap up here all the thoughts I have regarding the library so far which I think might worth consideration. They might be valid or not the intention is mostly to open discussion which might lead to some decisions regarding API and roadmap.

### Background

For over a year now I am playing [Elm](http://elm-lang.org/) programming language. It is quite good form different points of view, however is not applicable for every project.

For sometime now I have been developing React Native application and thus had to consider usage of TypeScript to achieve some kind of reliability close to Elm in it. One thing that was still uncovered - API data type safety. In Elm it is solved with [decoders](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Json-Decode) and I always enjoyed being able to caught errors with the data being incorrect early in my code. Thats why I was looking for something in this area and `io-ts` appeared to be brilliant solution for this problem! Than you @gcanti for making it!

### Issues with the library I have so far

Just to underline it a bit: my primary use case is typifying API responses. Especially when API is out of your control.

#### Validation vs Decoding

As I already wrote [here](https://github.com/gcanti/io-ts/pull/9#issuecomment-279629727) it seems like library already go a bit beyond just simple validation. I believe this is a good and useful feature and we can a bit change API direction to support it more seamlessly.

Let's say we do receive date as ISO string from the API. Most of the time string do not make a lot of sense for us because we want to be able work with dates. If we will remove ability to modify data during "validation" one would need to define two types within his program. One type with date being `string` which you can get immediately from your validator and one type with date being `Date` which you will return from your function.

The functionality described above is already possible, however is not really aligned with "validation" meaning and thats why might be not clear/misleading for library consumers.

One the other hand it looks like part of `io-ts` audience as @gcanti himself come to this library in order to have similar "decoding" they have in Elm/PureScript/Haskell/... so decoding will seem more familiar to them.

#### Either vs Promise

Since I am using this library for API data validation I have to use it in `Promise` context. For example:

```ts
axios
  .get(url)
  .then(res => validate(res.data, schema).fold(/* convert to Promise */)
```

Using `Either` might be more aligned to how it is done in functional languages, but in JavaScript/TypeScript land `Promise` seem to be main concept for this kind of cases. I would say that in order to simplify API and being more friendly to JS/TS people we should consider using promises as a default.

#### Make reporting nicer and part of core

I believe that most of the consumers do not need ability to customize error reporting somehow. When validation fails you most likely just want to know exact field where it failed, what was expected and what was given. With reporters as is I had quite bad time figuring out what is the exact issue with my data. So I ended up writing following:

```ts
function decode<T>(value: any, type: t.Type<T>): Promise<T> {
  const validation = t.validate(value, type);
  return validation
    .fold(
      ([e, ..._unused]) => {
        const actualErr = _.last(e.context);
        const errPath = e.context
          .map(c => c.key)
          .filter(key => key.length)
          .join('.');
        return Promise
          .reject(`${errPath} expected ${actualErr.type.name}, but got ${JSON.stringify(_.get(value, errPath))}`);
      },
      value => Promise.resolve(value),
    );
}
```

With this I am able to quickly find what is wrong in my validator definition or in data I receive form the API.

In combination with previous topic I would personally enjoy API close to this:

```ts
axios
  .get(url)
  .then(res => t.decode(res.data, schema))

// Error: some.nested.[0].field is expected to be string, but is given number: 123
```

#### Validator could be chainable

For example in case of data decoding instead of

```ts
const DateFromISOString = new t.Type<Date>(
  'Date',
  (v, c) => {
    const d = new Date(v)
    return isNaN(d.getTime()) ? t.failure<Date>(v, c) : t.success(d)
  }
)
```

one can leverage power of existing decoder

```ts
t.string.then(str => {
  const d = new Date(v)
  return isNaN(d.getTime()) ? t.failure<Date>(str) : t.success(d)
})
```

And there is no need to pass context down.

**Comment by gyzerok** [comment]
Sorry for quite a long read. This is quite rough summary of my thoughts. Feel free to suggest/disagree/correct.

**Comment by gcanti** [comment]
@gyzerok first of all thanks for the great write up

**Validation vs Decoding**

`decode` is nice. Honestly I have no strong opinion on this, I'm fine with both `validate` and `decode`.

**Either vs Promise**

On the contrary here I have a clear preference: I need a synchronous API. There are other use cases for IO validation I'm interested in other than endpoints, for example validating forms or (sync) APIs of "untrusted" libraries, or even for something like [prop types](https://github.com/gcanti/prop-types-ts).

**Make reporting nicer and part of core**

This is the reason why reporters are **not** part of the core :)

I learned from the past (issues on tcomb and flow-io) that how users want errors being displayed is somehow a matter of taste, no matter how good you define the default reporter. For example `some.nested.[0].field is expected to be string, but is given number: 123` is nice, but this would be even nicer for some users (a kind of super reporter!) https://github.com/gcanti/flow-io/pull/14#issuecomment-256295998.

**Validator could be chainable**

`Either` is already `chain`able (is a fantasy-land compliant monad instance)

```ts
const DateFromString = new t.Type<Date>(
  'Date',
  (v, c) => t.string.validate(v, c).chain(s => {
    const d = new Date(v)
    return isNaN(d.getTime()) ? t.failure<Date>(v, c) : t.success(d)
  })
)
```

Overall for now I consider io-ts a low level library you can build upon and/or customize in userland, but I'm open to discussions.

**Comment by gcanti** [comment]
FYI just published a trial version on the `next` channel (is not an official release, just a way to try the new version and iron out possible bugs)

```
npm install io-ts@next
```

**Comment by gyzerok** [comment]
@gcanti thanks! And sorry for silence, just have not had enough time to respond yet.

**Comment by gcanti** [comment]
FYI just released the new version (io-ts@0.1.1)

**Comment by gyzerok** [comment]
I guess your point is pretty clear, so let's close issue for now and come back if there are more things to discuss in the future

**Comment by gcanti** [comment]
Hi @gyzerok, in order to apply some of my last libraries to real world problems, I'm working on [a porting of Elm](https://github.com/gcanti/elm-ts) to TypeScript featuring

- [fp-ts](https://github.com/gcanti/fp-ts) as functional library
- [monocle-ts](https://github.com/gcanti/monocle-ts) for functional optics
- io-ts for decoders
- [rxjs 5](https://github.com/ReactiveX/RxJS) as reactive engine
- React as (pluggable) vdom library

As an Elm user I'd love to hear your feedback

**Comment by gyzerok** [comment]
@gcanti thanks for mentioning me! I will definitely take a look when have some time. You also might want to consider `redux-loop` library and [my work towards new API for it](https://github.com/redux-loop/redux-loop/pull/110). Maybe we can achieve some kind of synergy between efforts :)

P.S.: I guess that `io-ts` would be a bit nicer to have `Decoder` instead of `Validator`.

**Comment by OliverJAsh** [comment]
@gyzerok 



> Make reporting nicer and part of core

I feel you on this one. I started a repository to share the reporter(s) I've been using: https://github.com/OliverJAsh/io-ts-reporters

I'm currently aiming to have some parity with the error messages returned by Elm decoders: https://github.com/OliverJAsh/io-ts-reporters/issues/3

I would love your help on this.

**Comment by gyzerok** [comment]
@OliverJAsh yeah, I implemented something like this. Maybe it would make sense to run some poll around that in Twitter @gcanti? I hardly can imagine why would people need reporting not in that way.

**Comment by gcanti** [comment]
> Make reporting nicer and part of core

Does "core" mean the `index.ts` module? What do you propose? Or are you talking about adding @OliverJAsh 's reporter (or/and other variations) to the default ones? If that's the case, I'm fine with that.

**Comment by OliverJAsh** [comment]
I don't mind where the reporters live—here or elsewhere—but it would be good to combine efforts.
