### ISSUE TITLE
Correct compile time types of refinement types

### ISSUE THREAD

**Issue by cloudify** [gcanti/io-ts#212]
Hello @gcanti ,

I have a question for how to best approach something: I'd like to create a refinement from a type but I also want to have:

```ts
import * as t from "io-ts";

const MyT = t.partial({
  a: t.partial({ b: t.string }),
  c: t.partial({ d: t.number })
});
type MyT = t.TypeOf<typeof MyT>;

const MyRefinedT = t.refinement(MyT, _ => _ !== undefined && _.a !== undefined);
type MyRefinedT = t.TypeOf<typeof MyRefinedT>;

const v = {} as MyRefinedT;

const s: string = v.a.b;
//                           ~~~
//                           v is still partial
``` 

What I'm doing right now to solve the problem is to kind of map the `MyT` type to the `MyRefinedT` type and declare a new io-ts `Type` altogether :

```ts
type MyRefinedT = Pick<MyT, Exclude<keyof MyT, "a">> & {
  a: { b: NonNullable<NonNullable<MyT["a"]>["b"]> };
};

function isMyRefinedT(o: any): o is MyRefinedT {
  return MyT.is(o) && o.a !== undefined && o.a.b !== undefined;
}

const MyRefinedT = new t.Type<MyRefinedT, MyT>(
  "MyRefinedT",
  isMyRefinedT,
  (i, c) => {
    const validation = MyT.validate(i, c);
    if (validation.isLeft()) {
      return validation as t.Validation<MyRefinedT>;
    }
    const value = validation.value;
    return isMyRefinedT(value) ? t.success(value) : t.failure(value, c);
  },
  a => a as any
);

const v = {} as MyRefinedT;

const s: string = v.a.b;
```

But it's very verbose and I don't like the fact that I have to keep the type mappings in sync with the validation and the type guard.

I'd like instead something similar to `refinement` but that somewhat can infer the new type from the refinement (perhaps through a type guard?).

Do you have any suggestion?

thanks!

**Comment by gcanti** [comment]
> perhaps through a type guard?

Maybe

```ts
export const guard = <A, B extends A, O, I>(
  type: t.Type<A, O, I>,
  p: (a: A) => a is B,
  name?: string
): t.Type<B, O, I> => t.refinement(type, p, name) as any

type MyRefinedT = Pick<MyT, Exclude<keyof MyT, 'a'>> & {
  a: { b: NonNullable<NonNullable<MyT['a']>['b']> }
}

const MyRefinedT = guard(MyT, (o): o is MyRefinedT => o.a !== undefined && o.a.b !== undefined)
```

**Comment by cloudify** [comment]
Thanks! do you think there may be a way to construct `type MyRefinedT` by composing multiple `guard`s? What bothers me is that I have to keep the mapped type (compile time check) and the type guard (runtime check) in sync... with non-trivial types, the code I end up with [gets really verbose](https://github.com/teamdigitale/italia-app/pull/575/files#diff-a6806ab8348ff4cee7a739017f920f03R48).

An idea could be to have specialized `guard` functions that replace single props and that update the compile time types as well.

**Comment by cloudify** [comment]
This looks promising:

```ts

type RequiredProp1<T, P1 extends keyof T> = ReplaceProp1<
  T,
  P1,
  NonNullable<T[P1]>
>;

const requiredProp = <A, O, I, P extends keyof A>(
  type: t.Type<A, O, I>,
  p: P,
  name?: string
): t.Type<RequiredProp1<A, P>, O, I> =>
  t.refinement(type, o => o[p] !== undefined, name) as any;
```

**Comment by cloudify** [comment]
And this for replacing the type of a prop:

```ts

type ReplaceProp1<T, P1 extends keyof T, A> = { [K in P1]: A } &
  Pick<T, Exclude<keyof T, P1>>;

export const replaceProp1 = <A, O, I, P extends keyof A, B extends A[P]>(
  type: t.Type<A, O, I>,
  p: P,
  typeB: t.Type<B>,
  name?: string
): t.Type<ReplaceProp1<A, P, B>, O, I> =>
  t.refinement(type, o => typeB.is(o[p]), name) as any;
```

**Comment by cloudify** [comment]
It seems like I'm able to accomplish what I needed with much less code now, closing the issue...
thanks for the suggestion!
