### ISSUE TITLE
Keys expecting values t.any can be omitted

### ISSUE THREAD

**Issue by dubzzz** [gcanti/io-ts#214]
Hello,

I just started to draft some property based tests using [fast-check](https://github.com/dubzzz/fast-check/) over [io-ts](https://github.com/gcanti/io-ts) and discovered what seems to be a bug. The property based tests I have implemented so far are available [here](https://github.com/dubzzz/fast-check-examples/blob/master/test/packages/io-ts/test.js).

Basically it seems that if a type has a key whose value is `t.any`, then this key can be omitted.

```js
const M = t.type({
  key: t.any
});
const obj = {};
M.decode(obj);
// right({})
// I was expecting to have a left(...) in this case
```

Do you confirm the issue?

**Comment by gcanti** [comment]
@dubzzz thanks for the detailed report.

Another repro (using `t.undefined`)

```ts
const M = t.type({
  key: t.union([t.string, t.undefined])
})
const obj = {}

import { PathReporter } from 'io-ts/lib/PathReporter'
console.log(PathReporter.report(M.decode(obj)))
// => [ 'No errors!' ]
```

> Do you confirm the issue?

It might look weird but actually is the intended behaviour: that's how `undefined` is handled and ignoring keys allows some optimization here https://github.com/gcanti/io-ts/blob/82019c10e79fd4d1c676332f707d59885fbc302d/src/index.ts#L550

Here's a related issue in [runtypes](https://github.com/pelotom/runtypes/issues/60) containing an argument in favour of the current behaviour.

Also technically a fix would be a breaking change so it might be considered for io-ts@2.0.0, however I'm not yet convinced that it's worth it.

**Comment by dubzzz** [comment]
@gcanti Let's close the issue. Indeed TypeScript totally agrees with the behaviour stated above:

```typescript
interface WithOpt {
    opt?: number
}
const el: WithOpt = {};
```

Thanks for the details ;)

**Comment by corhere** [comment]
@dubzzz The TypeScript equivalent to
```ts
const M = t.type({
  key: t.union([t.string, t.undefined])
})
```
is actually
```ts
interface M {
  key: string | undefined
}
```

TypeScript does differentiate between properties whose values are `undefined` and those which are missing entirely.
```ts
const m: M = {}
// Type '{}' is not assignable to type 'M'.
//  Property 'key' is missing in type '{}'.
```

@gcanti io-ts diverging from TypeScript in its treatment of undefined vs. omitted props leads to some surprises in the derived static types. Consider the following two io-ts types `P` and `Q`. They have the same runtime validation behaviour but different static types.
```ts
const P = t.partial({ foo: t.string });
const Q = t.type({ foo: t.union([t.string, t.undefined] });
P.is({});  // true
Q.is({});  // true
const p: t.TypeOf<typeof P> = {};  // ok
const q: t.TypeOf<typeof Q> = {};  // compile error
```

It's not merely academic that TypeScript treats the types differently. There are subtle differences in runtime behaviour between a property that is set to `undefined` and one which is omitted entirely. It's a bit of a stretch, but it is not outside the realm of possibility for the mismatch between io-ts and TypeScript's type systems to lead to a subtle bug in someone's code.
```ts
const a = { foo: undefined };
Object.keys(a);  // ['foo']
'foo' in a;  // true

const b = {};
Object.keys(b);  // []
'foo' in b;  // false

Object.seal(a);
a.foo = 3;
a.foo;  // 3

Object.seal(b);
b.foo = 3;
b.foo;  // undefined
```

**Comment by gcanti** [comment]
@teves-castro yes `decode` **may** even change the input type (typically from `O` to `A`)

```ts
import { DateFromNumber } from 'io-ts-types/lib/Date/DateFromNumber'

const T = t.type({
  date: DateFromNumber
})

console.log(T.decode({ date: 0 }))
/*
right({
  "date": "1970-01-01T00:00:00.000Z"
})
*/
```

the original object is not changed though

**Comment by teves-castro** [comment]
@gcanti I see with your point, although in the example I supplied shouldn't decode return left? Check this:
```ts
const C = t.interface({
  key: t.undefined,
})
type C = t.TypeOf<typeof C>

C.decode({}) // yields right({ key: undefined }) and should instead yield left(...)
const c: C = {} // Type '{}' is not assignable to type 'TypeOfProps<{ key: UndefinedType; }>'.
                //   Property 'key' is missing in type '{}'.
                // In this case the compiler behaviour is different from the decode. I feel if the compiler rejects this assignment so should io-ts.
```

**Comment by gcanti** [comment]
No because it's the output of `decode` that must type-check, not its input

```ts
const T = t.type({
  date: DateFromNumber
})

console.log(T.decode({ date: 0 }))
/*
right({
  "date": "1970-01-01T00:00:00.000Z"
})
*/

type T = t.TypeOf<typeof T>
const c1: T = { date: 0 } // error as expected
const c2: T = { date: new Date(0) } // ok
```

**Comment by teves-castro** [comment]
Yes you're right!

**Comment by gcanti** [comment]
> Is it a bad idea to use interface to decode a class?

@FrancescoCioria not sure what's the use case here, if you are just checking that a value `v` is an instance of `Person` I'd use something like

```ts
const PersonType2 = new t.Type<Person>(
  'Person',
  (m): m is Person => m instanceof Person,
  (i, c) => (i instanceof Person ? t.success(i) : t.failure(i, c)),
  t.identity
)
```
