### ISSUE TITLE
Runtime dictionary type with literal domain is more strict than derived static type

### ISSUE THREAD

**Issue by corhere** [gcanti/io-ts#220]
https://github.com/gcanti/io-ts/blob/29737bf1ecaafcde5b92c37bc57e534ef833a04b/test/dictionary.ts#L51-L57

The behaviour in the linked test case does not match TypeScript's handling of the static type.
```typescript
const a = { foo: 'bar', baz: 'bob' };
const b: t.TypeOf<typeof T> = a;  // no compile error
```
The only time TypeScript is as strict is when object literals undergo [excess property checking](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks).
```typescript
// Compile error: Object literal may only specify known properties
const c: t.TypeOf<typeof T> = { foo: 'bar', baz: 'bob' };
```

I would expect this strict validation behaviour to be opt-in, e.g. by applying the `exact` combinator.

**Comment by gcanti** [comment]
I consider this behaviour to be opt-in (i.e. when you specify a domain other than `t.string`)
