### ISSUE TITLE
How to define a partial dictionary?

### ISSUE THREAD

**Issue by corhere** [gcanti/io-ts#221]
I want to define a runtime type which is equivalent to `T` in the following TypeScript code?
```typescript
type K = 'foo' | 'bar';
type T = { [D in K]?: string };
// or
type T = Partial<Record<K, string>>;
```
In other words, how can I define a partial dictionary type with a `keyof` type or union of literals as the domain?

The type
```typescript
const T = t.dictionary(
  t.keyof({ foo: null, bar: null }),
  t.union([t.undefined, t.string]),
);
```
is not the same, as the derived runtime type has `foo` and `bar` as required props.
```typescript
interface /* t.TypeOf<typeof T> */ {
  foo: string | undefined;
  bar: string | undefined;
}
```

**Comment by mattiamanzati** [comment]
Uhm, should'nt this be `t.partial(t.dictionary(t.union([t.literal('foo'), t.literal('bar')]), t.string))`? :)

**Comment by corhere** [comment]
I wish it was that easy. The `partial` combinator is not compatible with `DictionaryType` objects.
```
error TS2345: Argument of type 'DictionaryType<...snip...>' is not assignable to parameter of type 'Props'.
```

**Comment by gcanti** [comment]
The simplest solution is

```ts
const T = t.partial({
  foo: t.string,
  bar: t.string
})
```

Alternatively and more close to the original

```ts
import { map } from 'fp-ts/lib/Record'

const record = <KS extends t.KeyofType<any>, T extends t.Any>(k: KS, type: T): Record<keyof KS['keys'], T> => {
  return map(k.keys, () => type) as any
}

const K = t.keyof({ foo: null, bar: null })
const T = t.partial(record(K, t.string))
```
