### ISSUE TITLE
Unsafe Tagged definition leads to Any type

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#223]
```typescript
interface Foo {
...
}
const foo  = (x:  t.Tagged<'foo', Foo, t.mixed>) : t.TypeOf<typeof x> => 
x.decode({}) // type is inferred as: foo: (x: t.Tagged<"foo", Foo, t.mixed>) => any
```

This is due to that line:
https://github.com/gcanti/io-ts/blob/master/src/index.ts#L1068

The TaggedExact does not capture the A type Param, leading to the Any fallback defined here:
https://github.com/gcanti/io-ts/blob/master/src/index.ts#L1062

Removing `TaggedExact` helps to correctly infer foo to:

```typescript
// foo: (x: t.Tagged<"foo", Foo, t.mixed>) => Foo
```

as Expected.

A possible fix would be to change TaggedExact in order to make it capture the type parameter in a phantom variable like so:

```typescript
export interface TaggedExact<Tag extends string, A> extends ExactType<Tagged<Tag>> {
  readonly _A: A
}
```

And change the Tagged definition accordingly.

I'm not sure about the impact of this change but the current implementation is buggy.

@gcanti what do you think?

**Comment by gcanti** [comment]
@sledorze thanks, not sure why `TaggedExact` is defined differently from the others.. what about

```diff
 export interface TaggedIntersection<Tag extends string, A, O = A>
   extends IntersectionType<TaggedIntersectionArgument<Tag>, A, O> {}
-export interface TaggedExact<Tag extends string> extends ExactType<Tagged<Tag>> {}
+export interface TaggedExact<Tag extends string, A, O = A> extends ExactType<Tagged<Tag>, A, O> {}
 export type Tagged<Tag extends string, A = any, O = A> =
   | InterfaceType<TaggedProps<Tag>, A, O>
   | StrictType<TaggedProps<Tag>, A, O>
   | TaggedRefinement<Tag, A, O>
   | TaggedUnion<Tag, A, O>
   | TaggedIntersection<Tag, A, O>
-  | TaggedExact<Tag>
+  | TaggedExact<Tag, A, O>
   | RecursiveType<any, A, O>
```

**Comment by gcanti** [comment]
@sledorze released

**Comment by sledorze** [comment]
@gcanti Thanks! :)
