### ISSUE TITLE
intersection fails when passed a variable containing an array

### ISSUE THREAD

**Issue by brian-gates** [gcanti/io-ts#225]
`t.intersection` has strange behavior when dealing with dynamic arrays

Example:
```
const x = [t.partial({ foo: t.string })]
t.intersection([ x[0] ]) //works
t.intersection(x) // doesn't work
t.intersection([ ...x ]) // doesn't work
```

**Comment by gcanti** [comment]
That's because `intersection` only accepts tuples while `x` is inferred as an `Array`

**Comment by brian-gates** [comment]
Is there a way to convert an array to a tuple?

**Comment by brian-gates** [comment]
x and [ x[0] ] are essentially identical. I'm not sure what the difference is

**Comment by gcanti** [comment]
@brian-gates they are identical at runtime but they have different types for typescript when used with `intersection`

```ts
x: Array<P> // array
[x[0]]: [P] // tuple
```

where `P` is the type of `t.partial({ foo: t.string })`
