### ISSUE TITLE
io-ts/lib/index.d.ts(75,42): error TS2304: Cannot find name 'unknown'.

### ISSUE THREAD

**Issue by kylepotts** [gcanti/io-ts#228]
Seems like the 1.4.0 release had this change but it seems to break on TS 2. 

I get a bunch of these errors when using version 1.4.0

```
io-ts/lib/index.d.ts(289,193): error TS2304: Cannot find name 'unknown'.
```

**Comment by gcanti** [comment]
@kylepotts if you are running `< typescript@3.0.1` you have to polyfill `unknown`.

You can use [unknown-ts](https://github.com/gcanti/unknown-ts) as a polyfill.

**Comment by kylepotts** [comment]
Gotcha. Can that be put in a release note somewhere?

**Comment by gcanti** [comment]
Yup, just updated the release https://github.com/gcanti/io-ts/releases/tag/1.4.0
and the readme https://github.com/gcanti/io-ts#typescript-compatibility

**Comment by kylepotts** [comment]
Thank for being so responsive!
