### ISSUE TITLE
breaking change in interface type

### ISSUE THREAD

**Issue by mmkal** [gcanti/io-ts#229]
Hi there,

There are a couple of issues that have hit my team as a result of https://github.com/gcanti/io-ts/commit/e120b2b13f9dd08bffb61d657a2c17b1f545e5ee - specifically [this line](https://github.com/gcanti/io-ts/commit/e120b2b13f9dd08bffb61d657a2c17b1f545e5ee#diff-f41e9d04a45c83f3b6f6e630f10117feR519).

First, this was a breaking change. We use `t.union([t.string, t.undefined])` as the type for optional properties in `t.interface` in a lot of places, and those are going to cause ~~validation failures~~ `Type.is(...)` to return `false` unexpectedly in prod if we update to version 1.3.4. It didn't cause an outage for us because we had a test that accidentally caught this.

Second, it looks like it also introduced some inconsistencies between `.is` and `.decode` which I _think_ constitute a bug, if not then at least quite unexpected behaviour. Here's a test reproducing it:

```typescript
import * as t from 'io-ts';

it('test', () => {
  const Thing = t.interface({
      foo: t.union([t.string, t.undefined])
  })
  const inputs = [{ foo: undefined, bar: 'hi' }, { bar: 'hi' }, { foo: 'hi', bar: 'hi' }]

  const ises = inputs.map(i => Thing.is(i))
  const decodes = inputs.map(i => Thing.decode(i))

  expect(decodes.map(d => d.isRight())).toEqual(ises)
})
```

this fails with:
```
● test

    expect(received).toEqual(expected)

    Expected value to equal:
      [true, false, true]
    Received:
      [true, true, true]
```

It seems that `.decode` still has the old behaviour, but `.is` has updated behaviour and checks `hasOwnProperty`.

I'm not sure what the process is for breaking changes, but shouldn't this have been only pushed out in a 2.0 release?

I'm also a little unclear on why https://github.com/gcanti/io-ts/issues/214 required adding a `hasOwnProperty` check to `is`. If it wasn't necessary could it be reverted?

**Comment by gcanti** [comment]
> I'm also a little unclear on why #214 required adding a hasOwnProperty check to is

Let me show you an example, the following runtime type

```ts
const RT = t.type({ foo: t.union([t.string, t.undefined]) })
```

represents the type

```ts
type T = { foo: string | undefined } // foo is required (but can be undefined)
```

this raises an error in TypeScript

```ts
const x: T = {} // error: Property 'foo' is missing in type '{}'
```

so `RT.is({})` should return `false`. That's a bug fix rather than a breaking change.

> We use t.union([t.string, t.undefined]) as the type for optional properties in t.interface

Optional properties should be defined through `partial`, as explained in the [README](https://github.com/gcanti/io-ts#mixing-required-and-optional-props)

> it looks like it also introduced some inconsistencies between .is and .decode

`is` and `decode` have different semantics:

- `Type<A>.is(v)`: returns `true` if `v` is of type `A`?
- `Type<A>.decode(v)`: succeeds if `v` can be decoded to a value of type `A`

See also https://github.com/gcanti/io-ts/issues/214#issuecomment-434617309
