### ISSUE TITLE
More reusable types with Pipe..

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#230]
Currently Pipe signature is:

```typescript
pipe<B>(ab: Type<B, A, A>, name?: string): Type<B, O, I>;
```

This means the ab Type must exactly match `A` type.
I consider that if a Type can handle `unknown` has its input Type, then it should legitimately be used as `ab` type param.

The pipe signature would then become:

```typescript
pipe<B>(ab: Type<B, A, A> | Type<B, A, unknown>, name?: string): Type<B, O, I>;
```

@gcanti what do you think?

**Comment by sledorze** [comment]
not sure if its a Bug or Enhancement..

**Comment by sledorze** [comment]
it does compile, I'm investigating..

**Comment by gcanti** [comment]
what about

```ts
pipe<B, IB, A extends IB, OB extends A>(this: Type<A, O, I>, ab: Type<B, OB, IB>, name?: string): Type<B, O, I>
```

**Comment by sledorze** [comment]
Side note: I've never taken advantage of that `this` typing inside a method params.
Pretty interesting.

**Comment by sledorze** [comment]
Thanks a lot @gcanti !
