### ISSUE TITLE
Can't correctly constraint Types involving intersection based on their member output type

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#234]
This should generate an error due to `b` being a number

```typescript
const q : t.Type<{ a: string, b: number }, { [k: string]: string  } > = t.intersection([
    t.interface({
      a: t.string
    }),
    t.interface({
      b: t.number
    })
  ])
```

**Comment by sledorze** [comment]
Seen https://github.com/gcanti/fp-ts-routing/issues/37

**Comment by sledorze** [comment]
@gcanti I'm puzzled

**Comment by gcanti** [comment]
@sledorze Me too. Looks like an upstream bug

```ts
declare const a: { a: string; b: number }
declare const b: { a: string } & { b: number }
declare function f(x: { [k: string]: string }): void
f(a) // error
f(b) // NO error
```

**Comment by gcanti** [comment]
@sledorze I think I found a workaround (`Compact` helper)

```ts
type Compact<A> = { [K in keyof A]: A[K] }

declare const a: { a: string; b: number }
declare const b: { a: string } & { b: number }
declare const c: Compact<{ a: string } & { b: number }>
declare function f(x: { [k: string]: string }): void
f(a) // error
f(b) // NO error
f(c) // error
```

**Comment by sledorze** [comment]
@gcanti that's Great!
I guess we can take advantage of it in the intersection Type definition!

**Comment by sledorze** [comment]
I've tested it locally on the `io-ts` repo like this and it works perfectly:

```typescript
export function intersection<A extends Mixed, B extends Mixed>(
  types: [A, B],
  name?: string
): IntersectionType<[A, B], Compact<TypeOf<A> & TypeOf<B>>, Compact<OutputOf<A> & OutputOf<B>>, mixed>
```
I'm not sure if there's any drawbacks.

**Comment by sledorze** [comment]
<img width="1183" alt="screenshot 2018-11-22 at 22 20 13" src="https://user-images.githubusercontent.com/416760/48922136-e17e5400-eea4-11e8-898c-f297681ec885.png">

An attempt to enforce wrong detection with the pattern with dtslint reveals an issue with typescript 2.7.
I think we may upgrade to 2.8.
