### ISSUE TITLE
Is there a way to model roughly "extends" which also works with "exact"?

### ISSUE THREAD

**Issue by mnn** [gcanti/io-ts#239]
Pseudo TS-like code of what I mean:

```ts
// file A.ts:
const optionalPartA = t.partial(...);
const requiredPartA = t.interface(...);

export const ASchema = t.exact(t.intersection([optionalPartA, requiredPartA]));
export interface A extends t.TypeOf<typeof ASchema> {}


// file B.ts:
const optionalPartB = t.partial(...);
const requiredPartB = t.interface(...);

export const BSchema = t.exact(t.intersection([optionalPartB, requiredPartB]));
export interface B extends t.TypeOf<typeof BSchema> {}


// file AB.ts:
export const ABSchema = t.exact(t.intersection([ASchema, BSchema]));
export interface AB extends t.TypeOf<typeof ABSchema> {} // should be roughly equivalent to "B extends A"
```

I read https://github.com/gcanti/io-ts/pull/166#issuecomment-386005405, but it is not clear to me how/if it solves this issue. I am getting very complicated type errors like (one error, in this order) `is not assignable to parameter of type 'HasProps'.`, `is not assignable to type 'HasPropsIntersection'.`, `is not assignable to type 'HasProps[]'.`, `is not assignable to type 'HasProps'.` <- this one repeats two times.

I am starting to think that it is not possible to do it in an easy/clean way and I will have to export also helper schemas for `A` and `B` to construct `AB` (the inner `intersection` wrapped by `exact` from both "classes" in order to get non-`exact` schemas which should work when constructing a schema for `AB`). I would prefer some nicer solution.

Sorry for any errors in English, it is not my native language.
Any help would be appreciated :slightly_smiling_face:.

**Comment by gcanti** [comment]
@mnn the intersection of two exact types will always fail while decoding (unless `ASchema` and `BSchema` are equal).

You may want to instect their inner types

```ts
export const ABSchema = t.exact(t.intersection([ASchema.type, BSchema.type]))
```

**Comment by mnn** [comment]
Your solution works nicely in real code :smiley:. Thank you very much.
