### ISSUE TITLE
Reporters doesn't mix well with 'fold'

### ISSUE THREAD

**Issue by OfirArviv** [gcanti/io-ts#241]
Hi,

A question about how reporters are defined (this is also true for the 'io-ts-reporters' package) -
Its seems, to me at least, little awkward using reporter inside a fold of a run time type, code for exapmle:
```
runTimeType.decode(payload).fold( v=> v, error => reporter(left(error)).join("\n")).
```
As the reporter expect an `Either` type. 
Its like the reporters are not expect to be used inside a `fold` even thou it seems, to me at least, the most 'correct' way to use it.

Thoughts?

Thanks,
Ofir

**Comment by sledorze** [comment]
Reporters are designed to report on the status of a decode, which could be *either* a success or failure.
You may define a proxy function to wrap the error in a left to ease your pain.
there's already a https://github.com/gcanti/io-ts/blob/master/src/PathReporter.ts#L19 function accessible for the PathReporter.

**Comment by OfirArviv** [comment]
Didn't notice, I'll use it , thanks!

**Comment by JamesMcMahon** [comment]
[Here is a permanent link to the line of code@sledorze referenced.](https://github.com/gcanti/io-ts/blob/9aaaa4269aab7318870f17cab0ac368967e344ba/src/PathReporter.ts#L19)
