### ISSUE TITLE
Usage of static interface when defining a runtime interface

### ISSUE THREAD

**Issue by leemhenson** [gcanti/io-ts#245]
I've just knocked this up in an attempt to come at the problem of "unreadable" types:

```ts
export type StaticInterface = Record<string, any>;
export type RuntimeTypeOf<S extends StaticInterface> = { [k in keyof S]: t.Type<S[k], any> };

export const interfaceFromRuntimeType = <S extends StaticInterface>(
  props: RuntimeTypeOf<S>,
  name?: string,
) => {
  const inner = t.interface(props, name);
  const outer = new t.InterfaceType<RuntimeTypeOf<S>, S>(
    inner.name,
    inner.is,
    inner.validate,
    inner.encode,
    inner.props,
  );

  return outer;
};

// definition of class elided:
// class Iso8601DateStringType extends t.Type<Date, string>

export const DateRange = interfaceFromRuntimeType<{
  EndTime: Date;
  StartTime: Date;
}>({
  EndTime: Iso8601DateString,
  StartTime: Iso8601DateString,
});

export type DateRange = t.TypeOf<typeof DateRange>;
```

Because the static type is stored as the `_A`, you get simple types in code like:

```ts
DateRange.decode(blob).map(r => {
  // r is { EndTime: Date; StartTime: Date; } here
})
```

Thoughts?

**Comment by gcanti** [comment]
@leemhenson the output type looks wrong

```ts
export const DateRange = interfaceFromRuntimeType({
  EndTime: Iso8601DateString,
  StartTime: Iso8601DateString
})
/*
const DateRange: t.InterfaceType<RuntimeTypeOf<{
    EndTime: Date;
    StartTime: Date;
}>, {
    EndTime: Date;
    StartTime: Date;
}, {
    EndTime: Date; <= should be string
    StartTime: Date; <= should be string
}, unknown>
*/
```

Also looks like there's the usual issue with nested types (try with `typescript@3.1.6`)

```ts
export const Nested = interfaceFromRuntimeType({
  a: interfaceFromRuntimeType({
    b: t.string
  })
})
/*
const Nested: t.InterfaceType<RuntimeTypeOf<{
    a: {
        b: any;
    };
}>, {
    a: {
        b: any;
    };
}, {
    a: {
        b: any;
    };
}, unknown>
*/
```

Actually the types are unreadable bacause of this last issue, as a workaround I'm using type aliases like [`TypeOfProps`](https://github.com/gcanti/io-ts/blob/272a077e193be5d8f6491c72e247e41bf4757322/src/index.ts#L688) which don't produce `any`s (although they make the types unreadable)

**BUT**...

fortunately `typescript@3.2.2` doesn't have this issue anymore! 

I'm working on `io-ts@1.6.0` (branch `1.6`) and we'll finally get decent types.

Example

`io-ts@1.5.2` (current stable)

```ts
const Person = t.type({
  name: t.string,
  age: t.number
})
/*
const Person: t.InterfaceType<{
    name: t.StringType;
    age: t.NumberType;
}, t.TypeOfProps<{
    name: t.StringType;
    age: t.NumberType;
}>, t.OutputOfProps<{
    name: t.StringType;
    age: t.NumberType;
}>, unknown>
*/
```

branch `1.6`

```ts
const Person = t.type({
  name: t.string,
  age: t.number
})
/*
const Person: t.InterfaceType<{
    name: t.StringType;
    age: t.NumberType;
}, {
    name: string;
    age: number;
}, {
    name: string;
    age: number;
}, unknown>
*/
```

**Comment by leemhenson** [comment]
Ah, magic. I'll sit on my hands until 1.6 is born!

**Comment by gcanti** [comment]
@leemhenson the intermediary interfaces can be ported to `1.5.x` (i.e. no `typescript@3.2.2` requirement)

I wrote a candidate patch release (`1.5.3`), need some help to make sure is backward compatible, 
if you have the time you can try it out running `npm i gcanti/io-ts#1.5.3-lib`

**Comment by leemhenson** [comment]
I've changed jobs so I no longer have access to the large project that was using a lot of io-ts types. I've got a small project here and the proposed 1.5.3 branch looks good on here, but it's very basic usage.

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/io-ts/releases/tag/1.6.0
