### ISSUE TITLE
t.taggedUnion doesn't accept array from 1.5.3 (tuple only)

### ISSUE THREAD

**Issue by kunnix** [gcanti/io-ts#261]
Since the 1.5.3 update, `t.taggedUnion()` doesn't accept arrays anymore, only tuples.

Example:

```typescript
const test1 = t.type({
    version: t.literal('1')
});

const test2 = t.type({
    version: t.literal('2')
});

const allTests = [ test1, test2 ];

// Works
const taggedOK = t.taggedUnion(
    'version',
    [
        test1,
        test2
    ]
);

// Doesn't work
const taggedNotOK = t.taggedUnion(
    'version',
    allTests
);

// Doesn't work either
const taggedNotOKEither = t.taggedUnion(
    'version',
    [
        test1,
        test2
    ].map((v) => t.exact(v))
);
```

Error:

```
[ts]
Argument of type '(TypeC<{ version: LiteralC<"1">; }> | TypeC<{ version: LiteralC<"2">; }>)[]' is not assignable to parameter of type '[Tagged<"version", any, any>, Tagged<"version", any, any>, ...Tagged<"version", any, any>[]]'.
  Type '(TypeC<{ version: LiteralC<"1">; }> | TypeC<{ version: LiteralC<"2">; }>)[]' is missing the following properties from type '[Tagged<"version", any, any>, Tagged<"version", any, any>, ...Tagged<"version", any, any>[]]': 0, 1 [2345]
```

**Comment by gcanti** [comment]
@kunnix `taggedUnion` and `union` are now aligned with `tuple` and `intersection`, i.e. you have to prove to the type checker that you are passing a correct number of elements

**Comment by kunnix** [comment]
@gcanti Which would be great if TypeScript had a nice way to hint for tuple types, but it's not the case yet and for now they're typed as variable-lengths arrays when stored in a variable or passed to `.map()` (see <https://github.com/Microsoft/TypeScript/issues/10195> and <https://github.com/Microsoft/TypeScript/issues/16656>)

I understand this is an elegant way to deal with typing, but it currently prevents storing a list of types in a variable, or to automatically enclose a list of types inside a `t.exact()` (so, forces to copy-and-paste code when these patterns were used).

**Comment by gcanti** [comment]
Maybe a couple of helpers can help

```ts
const tuple = <T extends Array<unknown>>(...t: T): T => {
  return t
}

type MakeExact<T extends Array<t.HasProps>> = { [K in keyof T]: T[K] extends t.HasProps ? t.ExactC<T[K]> : never }

const makeExact = <T extends Array<t.HasProps>>(...elements: T): MakeExact<T> => {
  return elements.map(e => t.exact(e)) as any
}

// ok
const TU1 = t.taggedUnion('version', [test1, test2])

const allTests = tuple(test1, test2)

// ok
const TU2 = t.taggedUnion('version', allTests)

// ok
const TU3 = t.taggedUnion('version', makeExact(...allTests))

// ok
const TU4 = t.taggedUnion('version', makeExact(test1, test2))
```

**Comment by kunnix** [comment]
Looks like a great workaround!

**Comment by kunnix** [comment]
@gcanti You probably saw that already, but it might help: https://github.com/Microsoft/TypeScript/pull/29510
