### ISSUE TITLE
null value does not pass voidType validation

### ISSUE THREAD

**Issue by sutarmin** [gcanti/io-ts#273]
According to [typescript docs](https://www.typescriptlang.org/docs/handbook/basic-types.html#void) both `null` and `undefined` can be assigned to the variable of type `void`:

> Declaring variables of type void is not useful because **you can only assign `undefined` or `null` to them**

But now `voidType.decode(null)` returns you Left instance. Was it done intentionally or it is a bug?

**Comment by gcanti** [comment]
@sutarmin perhaps the documentation is outdated

```ts
// typescript@3.2.4

const y: void = undefined // ok
const x: void = null // error Type 'null' is not assignable to type 'void'

declare function f(x: void): void

f(undefined) // ok
f(null) // error Argument of type 'null' is not assignable to parameter of type 'void'
```

**Comment by gcanti** [comment]
See https://github.com/Microsoft/TypeScript/issues/11758

**Comment by sutarmin** [comment]
Thanks for the link, sorry for bothering ;) And thank you for all the things you are doing for typescript community!
