### ISSUE TITLE
Union does not encode last type but returns it non encoded

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#288]
This is due to that line:
https://github.com/gcanti/io-ts/blob/master/src/index.ts#L1135

We discard the last codec and (i < len -1) and just return the value, without encoding it.

**Comment by sledorze** [comment]
@gcanti working on that fix reveals a problem with the `should play well with stripping combinators` test which appears to no pass and is using a wrong check.
It shouldn't it be:

```typescript
    it('should play well with stripping combinators', () => {
      const T = t.union([t.strict({ a: t.number }), t.type({ b: NumberFromString })])
      const x = { a: 1, c: true }
      assert.deepStrictEqual(T.encode(x), {a: 1})
    })
```

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/io-ts/pull/290
