### ISSUE TITLE
NeverType usage

### ISSUE THREAD

**Issue by lostintime** [gcanti/io-ts#292]
## Prelude

http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-2.html

> TypeScript 3.2 makes narrowing easier by relaxing rules for what it considers a discriminant property. Common properties of unions are now considered discriminants as long as they contain some singleton type (e.g. a string literal, null, or undefined), and they contain no generics.

Which allow us to build types like this:

```typescript
export type Success<T> = {
  result: T
  error?: never
}

export type Failure<E> = {
  error: E
  result?: never
}

export type Result<E, T> =
  | Failure<E>
  | Success<T>
```

And then use it like this:

```typescript
const r: Result<string, number> = success(10)
if (r.result) {
    const x: number = r.result
    expect(x).equals(10)
} else {
    console.log(r.error)
}
```

Which was causing compiler error before.

## Exact Decoders

While trying to define decoders for the types above, prior to `io-ts@1.8.0` I used `exact` combinator, to make sure there is no `error` field present in `Success` result and the other way around, but starting with `io-ts@1.8.0` - `exact` behavior changed, and it now my tests fails:

```typescript
export function Success<T>(result: t.Type<T>): t.Type<Success<T>> {
  return t.exact(
    t.interface({
      result: result
    })
  ) // or t.strict({ result: result })
}

expect(Success(t.number).decode({ result: 123, error: null }).isRight()).is.false // fails
expect(Success(t.number).decode({ result: 123, error: undefined }).isRight()).is.false // fails

```

My first idea on how to fix this was to use `never` type, like: 

```typescript
  t.intersection([
    t.interface({
      result: result
    }),
    t.partial({
      error: t.never
    })
  ])
```

But this doesn't work:

```
src/result.ts(27,7): error TS2322: Type 'NeverC' is not assignable to type 'Mixed'.
  Types of property 'encode' are incompatible.
    Type 'Encode<never, never>' is not assignable to type 'Encode<any, any>'.
      Types of parameters 'a' and 'a' are incompatible.
        Type 'any' is not assignable to type 'never'.
```

Is there a way to achieve this with v1.8 and still use `never` type? and what is the intent of NeverType ?

**Comment by gcanti** [comment]
> what is the intent of NeverType

@lostintime used in the `exact` and `tuple` implementation, can be deprecated now

**Comment by lostintime** [comment]
@gcanti can I still prevent a field to be present in an object, ex: if there is `error` field - fail on decode? Like old `exact` behavior (or `strict` was it?)

**Comment by gcanti** [comment]
@lostintime this encoding is weird

```ts
export type Success<T> = {
  result: T
  error?: never
}

export type Failure<E> = {
  error: E
  result?: never
}

export type Result<E, T> =
  | Failure<E>
  | Success<T>
```

should be defined as 

```ts
export type Success<T> = {
  result: T
  error?: undefined
}

export type Failure<E> = {
  error: E
  result?: undefined
}

export type Result<E, T> = Failure<E> | Success<T>
```

(`never` is always absorbed in a union)

**Comment by lostintime** [comment]
Right, I'm using `undefined` now, but just wondering if there is a way to ensure a field is not preset in an object

**Comment by gcanti** [comment]
> if there is a way to ensure a field is not preset in an object

It depends on what you mean by "is not present"

Would this be acceptable?

```ts
t.partial({ myfield: t.undefined })
```

back to your example

```ts
export type Success<T> = {
  result: T
  error?: undefined
}

export function Success<T>(result: t.Type<T>): t.Type<Success<T>> {
  return t.intersection([t.strict({ result }), t.exact(t.partial({ error: t.undefined }))])
}

console.log(Success(t.number).decode({ result: 123, error: undefined }).value) // { result: 123, error: undefined }
console.log(Success(t.number).decode({ result: 123, foo: 'a' }).value) // { result: 123 }
console.log(PathReporter.report(Success(t.number).decode({ result: 123, error: null }))) // fails
console.log(PathReporter.report(Success(t.number).decode({ result: 123, error: 'a' }))) // fails
```

**Comment by lostintime** [comment]
@gcanti I think `t.undefined` will cover most of the cases, let's close this
