### ISSUE TITLE
Type expected?

### ISSUE THREAD

**Issue by Chittipobng014** [gcanti/io-ts#298]
I can not compile when I imported "io-ts"

![image](https://user-images.githubusercontent.com/23081818/53091840-135b9100-354e-11e9-8453-4c097847d35b.png)

**Comment by gcanti** [comment]
It's likely a TypeScript compatibility issue, see https://github.com/gcanti/io-ts#typescript-compatibility

**Comment by Chittipobng014** [comment]
> It's likely a TypeScript compatibility issue, see https://github.com/gcanti/io-ts#typescript-compatibility

I'm using

tsc version 3.2.4
io-ts version 1.6.2

**Comment by gcanti** [comment]
> I'm using tsc version 3.2.4 io-ts version 1.6.2

I can't repro, could you please put a small repo with a repro?
