### ISSUE TITLE
Union From Enum from version 1.5.3

### ISSUE THREAD

**Issue by AlexRex** [gcanti/io-ts#299]
In newer versions of the library we were able to create a union type from a enumerate in the following way: 

```
const unionFromEnum = (enumeration: any) => 
  t.union(Object.keys(enumeration).map((pos) => t.literal(enumeration[pos])));
```

But from version 1.5.3 looks like t.union is expecting more than one input, even if it's an array: 

```
Argument of type 'LiteralC<any>[]' is not assignable to parameter of type '[Mixed, Mixed, ...Mixed[]]'.
  Type 'LiteralC<any>[]' is missing the following properties from type '[Mixed, Mixed, ...Mixed[]]': 0, 1
```
```
[Mixed, Mixed, ...Array<Mixed>]
```

Is this the correct behavior? Are we doing it wrongly?

**Comment by gcanti** [comment]
@AlexRex `taggedUnion` and `union` are now aligned with `tuple` and `intersection`, i.e. you have to prove to the type checker that you are passing a correct number of elements.

`unionFromEnum` looks unsafe though, also it always returns `t.UnionC<any>`

```ts
const unionFromEnum = (enumeration: any) =>
  t.union(Object.keys(enumeration).map(pos => t.literal(enumeration[pos])) as any)

// T1: t.UnionC<any>
const T1 = unionFromEnum('bad') // <= wrong input

// T2: t.UnionC<any>
const T2 = unionFromEnum({ a: 'a', b: 1, c: true })
```

Could you please provide a concrete example of its usage?

**Comment by AlexRex** [comment]
Hi @gcanti, thanks for your quick response. :) 

Agree with you that `unionFromEnum` is probably quite unsafe, and is missing proper typing. 

Let me explain the use-case for this function: 
```
const unionFromEnum = (enumeration: any) => t.union(Object.keys(enumeration).map((pos) => t.literal(enumeration[pos])));

enum Ages {
  SUB_10 = 'SUB_10',
  SUB_21 = 'SUB_21',
  ABOVE_21 = 'ABOVE_21'
}

const Person = t.type({
  name: t.string,
  surname: t.string,
  age: unionFromEnum(Ages)
});

const input = {
  name: 'Marco',
  surname: 'M.',
  age: 'SUB_10'
};

const inputWrong = {
  name: 'Marco',
  surname: 'M.',
  age: 'bad'
};

Person.decode(input); // right
Person.decode(inputWrong); // left
```

Maybe we're doing something wrong here and using the library incorrectly. Should we create a Type instead?

**Comment by gcanti** [comment]
Generic `enum`s are not supported. For string enums you can see [this issue](https://github.com/gcanti/io-ts/issues/216#issuecomment-461275424)
