### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by nnance** [gcanti/io-ts#3]
So I am a big TypeScript fan and have been applying it for a couple of years in my Node projects both personally and professionally.  I am also into Scala and functional programming.  I noticed that this library used FP concepts and it lead me to the your fp-ts project.  Both of these projects are very interesting to me and I would be interested in contributing if you need / want the help.

**Comment by gcanti** [comment]
Hi, 

Yes, I would welcome any ideas / help

**Comment by dmorosinotto** [comment]
Hi @gcanti and @nnance even I'm a big TS-fun and user from a long time, so if you need / want some help or suggestions keep me posted ;-)
