### ISSUE TITLE
Custom helper returning t.TypeC<any> type

### ISSUE THREAD

**Issue by lrdxg1** [gcanti/io-ts#302]
**Do you want to request a _feature_ or report a _bug_?**

A bug, but maybe my typing is wrong

**What is the current behavior?**

I created a helper to create a codec from another codec, with some of its properties transformed into an array of strings (so `t.array(t.string)`). The goal is to get a codec for a complex object transformed with [normalizr](https://github.com/paularmstrong/normalizr).

Here is my helper

```typescript

const normalizeCodec = <T extends t.TypeC<any>, K extends keyof T['props']>(
  codec: T,
  properties: K[],
  name?: string,
) =>
  t.type(
    {
      ...codec.props,
      ...properties.reduce(
        (acc, prop) => ({
          ...acc,
          [prop]: t.array(t.string),
        }),
        {},
      ),
    },
    name,
  );
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

[Here is the code](https://codesandbox.io/s/v6k21qyp67). If you use vs code (in the experimental options of codesandbox) you can clearly see the type of `normalizedListCodec` being `t.TypeC<any>` by hovering the variable.

**What is the expected behavior?**

The returned codec shouldn't be of type `t.TypeC<any>`.

**Which versions of io-ts, and which browser and OS are affected by this issue? Did this work in previous versions of io-ts?**

1.8.2, no browser test necessary

To be frank I don't know if it's a bug or my function typing is incorrect. But I'm not typing the returned value from the function so I would have imagined that the inference will return the correct type.

**Comment by gcanti** [comment]
> To be frank I don't know if it's a bug or my function typing is incorrect

@lrdxg1 that's because of the `any`. If you change the signature to

```ts
export const normalizeCodec = <P extends t.Props, T extends t.TypeC<P>, K extends keyof P>(
  codec: T,
  properties: K[],
  name?: string
) =>
  t.type(
    {
      ...codec.props,
      ...properties.reduce(
        (acc, prop) => ({
          ...acc,
          [prop]: t.array(t.string)
        }),
        {}
      )
    },
    name
  )
```

you can see `t.TypeC<P & {}>` as a result type (which is still not correct but is a step forward).

**Comment by jschr** [comment]
I was also struggling to create a codec helper function that had the correct types until I found this issue and #212. 

Here's my simple decode helper with the correct types in case it's useful for anyone else who might come across this scratching their heads:

```ts
const decode = <P extends t.Props>(codec: t.TypeC<P>, data: unknown) => {
  const result = codec.decode(data);
  return result.getOrElseL(() => {
    throw new Error(PathReporter.report(result)[0]);
  });
};
```

**Comment by lrdxg1** [comment]
It looks like moving the t.TypeC from the generics to the argument of the function (which makes sense) does it. Thanks @jschr !

Here is my current code (omit is from lodash)

```ts
export const normalizeCodec = <P extends t.Props, K extends keyof P>(
  codec: t.TypeC<P>,
  properties: K[],
  name?: string,
) => {
  const keptProps = omit(codec.props, properties);
  return t.type(
    properties.reduce(
      (acc, prop) => ({
        ...acc,
        [prop]: t.array(t.string),
      }),
      keptProps,
    ),
    name,
  );
};
```
