### ISSUE TITLE
Issue with brand operator with strict

### ISSUE THREAD

**Issue by MastroLindus** [gcanti/io-ts#303]
```
interface PositiveOrZeroBrand { readonly PositiveOrZero: unique symbol; }

const PositiveOrZero = t.brand(t.number, (n): n is t.Branded<number, PositiveOrZeroBrand> => n >= 0, "PositiveOrZero");

// using strict with a brand type, fails to infer that the resulting type is a t.Type
const doesntWorkExample = t.strict({foo: PositiveOrZero});
type DoesntWorkExampleType = typeof doesntWorkExample;
type ResultIsNever = DoesntWorkExampleType extends t.Type<infer U> ? U : never;

// using strict with a non-brand type, infers work correctly (resultIsCorrect is inferred as {foo: string}
const workExample = t.strict({foo: t.string});
type WorkExampleType = typeof workExample;
type resultIsCorrect = WorkExampleType extends t.Type<infer U> ? U : never;
```

I just upgraded from 1.3 where I was using refinement instead of branding, and I didn't have issues there.
Note: I need to use the ``extends t.Type<infer U> ? U : never`` construct to extract the underlying type instead of t.TypeOf<typeof runtimeType> because i have many runtimeTypes in one array, and I have something like this: 
``export type ExtractType<T extends keyof myArray> = myArray[T] extends t.Type<infer U> ? U : never``
Not sure if it's the easiest/smartest way, but it's the result of some other stuff in my codebase.

**Comment by gcanti** [comment]
@MastroLindus that's because 

```ts
X extends t.Type<infer U> ? U : never
```

doesn't work when `X = t.Type<A, O, I>` and `O` is not equal to `A` (which is the case with a branded codec)

Try

```ts
X extends t.Type<infer U, any, any> ? U : never
```

instead

**Comment by MastroLindus** [comment]
@gcanti worked perfectly, thank you, I was looking in the wrong direction, I should have realized this myself!
