### ISSUE TITLE
Recursion use case

### ISSUE THREAD

**Issue by Ahryman40k** [gcanti/io-ts#307]
Hi, 

I'm looking some advices that help me to solve my problem.
I have interfaces:
```javascript
interface A {
   id?: string
   extension?: Array<B>
}

interface C {
   id: string
   extension?: Array<B>
   prop1?: A
   prop2?: A
}

interface B {
    id?: string
    extension?: Array<B>
    prop1?: A
    prop2?: A 
}
```

I'm a little bit confusing on how I can manage 
- Recursion in B
- mutual recursion between A and B
- other objects that are dependent of A and B
- optional properties

I'm using io-ts 1.8.2

Please could you help me.
Thanks a lot.

**Comment by gcanti** [comment]
@Ahryman40k you can refer to [Mutually recursive types](https://github.com/gcanti/io-ts#mutually-recursive-types) and [Mixing required and optional props](https://github.com/gcanti/io-ts#mixing-required-and-optional-props)

So in your case:

```ts
import * as t from 'io-ts'

interface A {
  id?: string
  extension?: Array<B>
}

interface B {
  id?: string
  extension?: Array<B>
  prop1?: A
  prop2?: A
}

const A: t.Type<A> = t.recursion('A', () =>
  t.partial({
    id: t.string,
    extension: t.array(B)
  })
)

const B: t.Type<B> = t.recursion('B', () =>
  t.partial({
    id: t.string,
    extension: t.array(B),
    prop1: A,
    prop2: A
  })
)

const C = t.intersection([
  t.type({
    id: t.string
  }),
  t.partial({
    extension: t.array(B),
    prop1: A,
    prop2: A
  })
])
```

**Comment by Ahryman40k** [comment]
Thank you very much for your answer. 
I have read the referred chapters of your doc, but it wasn't clear enough in my mind about multiple mutually recursive types.
Now I can see where my problem is.

**Comment by Ahryman40k** [comment]
The explanation was my union wasn't recursive too ...

**Comment by fasiha** [comment]
@Ahryman40k @gcanti I'd like to ask what I think is a followup question to the above, involving recursive partial types. I'd like to do this:
```ts
import * as t from "io-ts";

interface Foo {
  required: number;
  optional?: Foo[];
}
const Foo: t.Type<Foo> = t.recursion("Foo", () =>
  t.union([
    t.type({ required: t.number }),
    t.partial({ optional: t.array(Foo) }),
  ])
);
```
but this fails:
```
  Types of property 'is' are incompatible.
    Type 'Is<{ required: number; } | { optional?: Foo[] | undefined; }>' is not assignable to type 'Is<Foo>'.
      Type '{ required: number; } | { optional?: Foo[] | undefined; }' is not assignable to type 'Foo'.
        Property 'required' is missing in type '{ optional?: Foo[] | undefined; }' but required in type 'Foo'.ts(2322)
```

I notice that I can succeed in a slightly different version:
```ts
interface Bar {
  required: number;
  optional: undefined | Bar[];
}
const Bar: t.Type<Bar> = t.recursion("Bar", () =>
  t.type({
    required: t.number,
    optional: t.union([t.undefined, t.array(Bar)]),
  })
);
```
This works, the only difference between `Bar` and `Foo` is that `optional` is actually required (no `optional?` in `Bar`). I'd very much like to have `Foo` though, because `optional` might be missing in my payload.

Any tips on how to get `t.union` to accept my recursion+partial? Your comment "my union wasn't recursive" makes me think I need to do some extra calls to `t.recursion` somewhere…?

**Comment by fasiha** [comment]
Oooooops, I see my mistake! I was using `t.union` instead of `t.intersection`! Sorry for the spam 🙇!
