### ISSUE TITLE
TypeDoc support for properties

### ISSUE THREAD

**Issue by prescottprue** [gcanti/io-ts#314]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
Given the following codec/type:

```ts
export const TeamCodec = t.partial({
  createdAt: t.number,
  createdBy: t.string,
  name: t.string
}, 'Team')

export type TeamType = t.TypeOf<typeof TeamCodec>
```

results in the following Typedoc documentation:

![image](https://user-images.githubusercontent.com/2992224/55116465-92d80500-50a4-11e9-9ed4-3909125cbbe5.png)

![image](https://user-images.githubusercontent.com/2992224/55115287-640c5f80-50a1-11e9-810b-50d2c74c1b6d.png)

`TypeOf` is great, but it would be even better if the type appeared with the actual values just like an interface normally does:

![image](https://user-images.githubusercontent.com/2992224/55116578-f8c48c80-50a4-11e9-932d-5b801cfa78f0.png)

**OR**

Maybe I just missed it, but if there was a way to create a codec directly from an interface, then it could be left up to the developer to export their `interface`. That same interface could be used to make the codec:

```ts
export interface TeamValue {
  createdAt?: number
  createdBy?: string
  name?: string
}

export const TeamCodec = t.CodecFromInterface(TeamValue, 'Team')
```

I realize this might be counter to the original value proposition of the library, but it seems possible since it appears [that is what ts-interface-builder does](https://github.com/gristlabs/ts-interface-builder).

Not sure if it would be possible/harder/easier, but it might also work if an interface could come from a codec:

```ts
export const TeamCodec = t.partial({
  createdAt: t.number,
  createdBy: t.string,
  name: t.string,
}, 'Team')

export t.InterfaceFromCodec<TeamCodec>
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

**What is the expected behavior?**
Either
* properties of codecs and/or types are correctly exported to Typedoc
* Codecs able to be created directly from an interface

**Which versions of io-ts, and which browser and OS are affected by this issue? Did this work in previous versions of io-ts?**

No, proposing a new feature

**Comment by bayareacoder** [comment]
Any update on this? 
Agreed this would be very useful to have. I also use TypeDoc but lost the properties in each Object type when adopting io-ts.

**Comment by gcanti** [comment]
> TypeOf is great, but it would be even better if the type appeared with the actual values just like an interface normally does

Looks like a TypeDoc issue

> if there was a way to create a codec directly from an interface

That's not possible without code generation
