### ISSUE TITLE
Function is deprecated without a clear alternative

### ISSUE THREAD

**Issue by dylanseago** [gcanti/io-ts#324]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
Usage of `t.Function` is marked as deprecated without a clear alternative.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
Look at the docs to see that `t.Function` is deprecated. Or run tslint with `tslint-config-standard` on code using `t.Function` to see it complain about `deprecation`.

**What is the expected behavior?**
`t.Function` should not be marked deprecated, or an alternative type for validating functions should be added.

**Which versions of io-ts, and which browser and OS are affected by this issue? Did this work in previous versions of io-ts?**
Current version: 1.8.7, worked in versions prior to 1.8.3

**Comment by gcanti** [comment]
There's no sensible alternative (you can't really validate a function, i.e. its domain and codomain, at runtime) and is deprecated because will be removed in io-ts@2.

**Comment by dylanseago** [comment]
@gcanti Why is it an all or nothing scenario? There are many use cases for validating that a value is, at the very least, a function even if there's no way to check the signature.

For example, we have libraries written in typescript that are used in plain javascript runtimes and `io-ts` is used to validate that the arguments passed in conform to the static typescript types. A common occurrence would be passing in an options object containing a callback or event handler attribute. `t.Function` would be used inside the options object type to verify at runtime that the attribute really is a function and our library can safely use it as one. Even if the signature is incorrect that responsibility would fall on the consumer of the library which is in line with expectations of existing nodejs libraries with function parameters.

Considering 'function' is a fundamental type in javascript it doesn't seem sensible to remove it.

**Comment by jeremyswann** [comment]
I found this confusing at first and I'm still trying to understand. I guess I'm under the impression that you're suggesting the type and the return value are the purposes of io-ts and/ FP libraries, not the interface or pipeline that got you there? I feel like TypeScript has been messing with me haha, e.g. `( ) => void` @gcanti  you're saying just use `t.void`?

**Comment by samhh** [comment]
If you can establish that something is a function (e.g. baseline `(...xs: unknown[]) => unknown`), what use is it if you still don't know what its domain is i.e. what input it takes? The codomain/output is less of a concern as you can just mark it `unknown`, but marking the domain as `unknown` still leaves a whole wide open in the type system given the function was originally probably designed with a specific input type.
