### ISSUE TITLE
ES Modules to better support tree-shaking?

### ISSUE THREAD

**Issue by osdiab** [gcanti/io-ts#326]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
No ESModules output for this library; when I try to include anything in the library in my Create React App codebase and then call `react-scripts build`, it seems to include the whole library - about 6.5kb, which matches the estimated minified size of the repo on [BundlePhobia](https://bundlephobia.com/result?p=io-ts@1.8.5)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**
N/A

**What is the expected behavior?**
My code only requires a few members of `io-ts`, so I expect most of the library should be dead-code eliminated. The `fp-ts` library seems to have this implemented (separate `tsconfig.es6.json` and an ESModules output) but this one doesn't.

**Which versions of io-ts, and which browser and OS are affected by this issue? Did this work in previous versions of io-ts?**
All of them - I'm using 1.8.5

**Comment by osdiab** [comment]
Here is the relevant issue there: https://github.com/gcanti/fp-ts/issues/813

**Comment by gcanti** [comment]
@osdiab patch released
