### ISSUE TITLE
Error messages for optional fields

### ISSUE THREAD

**Issue by alcuadrado** [gcanti/io-ts#330]
First of all, I'm blown away by this library 🤯Congratulations on the excellent work here, Giulio!

**Do you want to request a _feature_ or report a _bug_?**

I want to know if something is possible with the built-in codecs, or some hints to implement it myself.

**What is the current behavior?**

I have many optional fields in the types I want to validate. For example:

```ts
const OptionalNumber = t.union([t.number, t.undefined])

const Config = t.type(
  {
    n: OptionalNumber
  },
  "Config"
);

const res = Config.decode({ n: "A" });
console.log(PathReporter.report(res));
```

And they return two errors when an invalid value is provided.

```js
[
  'Invalid value "A" supplied to : Config/n: (number | undefined)/0: number',
  'Invalid value "A" supplied to : Config/n: (number | undefined)/1: undefined'
]
```

**What is the expected behavior?**

I want to somewhat unify them and show a single one. Something like:

`'Invalid value "A" supplied to Config.n. Expected a value of type number | undefined'`

I created this reporter based on `PathReporter`

```ts
function stringify(v: any): string {
  if (typeof v === 'function') {
    return getFunctionName(v)
  }
  if (typeof v === 'number' && !isFinite(v)) {
    if (isNaN(v)) {
      return 'NaN'
    }
    return v > 0 ? 'Infinity' : '-Infinity'
  }
  return JSON.stringify(v)
}

function getContextPath(context: Context): string {
  return context[0].type.name + "." + context.slice(1).map(c => c.key).join('.')
}

function getMessage(e: ValidationError): string {
  const lastContext = e.context[e.context.length - 1]
  return e.message !== undefined
    ? e.message
    : `Invalid value ${stringify(e.value)} for ${getContextPath(e.context)}. Expected a value of type ${lastContext.type.name}.`
}

export function failure(es: Array<ValidationError>): Array<string> {
  return es.map(getMessage)
}

export function success(): Array<string> {
  return ['No errors!']
}

export const DotPathReporter: Reporter<Array<string>> = {
  report: validation => validation.fold(failure, success)
}
```

But of course I'm getting two error messages:

```js
[
  'Invalid value "A" for Config.n.0. Expected a value of type number.',
  'Invalid value "A" for Config.n.1. Expected a value of type undefined.'
]
```

I think the `.0` and `.1` can be especially confusing.

I probably have to preprocess the `validation` array inside `DotPathReporter#report` before folding it. Is this approach correct? Is there any example of this?

**Which versions of io-ts, and which browser and OS are affected by this issue? Did this work in previous versions of io-ts?**

io-ts: 1.8.6
typescript: 3.4.5
ts-node: 8.2.0
Node:  v12.2.0
npm: 6.9.0
MacOs: 10.14.5

**Comment by gcanti** [comment]
@alcuadrado you could define a custom combinator

```ts
function optional<A, O>(
  codec: t.Type<A, O, unknown>,
  name: string = `${codec.name} | undefined`
): t.Type<A | undefined, O | undefined, unknown> {
  return new t.Type(
    name,
    (u: unknown): u is A | undefined => u === undefined || codec.is(u),
    (u, c) => (u === undefined ? t.success(u) : codec.validate(u, c)),
    a => (a === undefined ? a : codec.encode(a))
  )
}

const Config = t.type(
  {
    n: optional(t.number)
  },
  'Config'
)

const res = Config.decode({ n: 'A' })
console.log(PathReporter.report(res))
// => [ 'Invalid value "A" supplied to : Config/n: number | undefined' ]
```

**Comment by alcuadrado** [comment]
That's so neat! This library is really well designed!

I think this would make for a nice example in the README. If you think so, I can create a PR adding it to the tip and tricks section.

**Comment by gcanti** [comment]
> I think this would make for a nice example in the README. If you think so, I can create a PR adding it to the tip and tricks section

Ok, thanks

**Comment by alcuadrado** [comment]
Thank you! I'll send the PR later today.
