### ISSUE TITLE
Support to exclude/omit properties

### ISSUE THREAD

**Issue by 2beaucoup** [gcanti/io-ts#338]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
It's not possible to remove properties from defined types.

**What is the expected behavior?**
Desired behaviour would be something like:
```ts
const AB = t.type({
  a: number,
  b: string,
})
const B = t.omit(AB, 'a')
```

Maybe there's a simple workaround I'm missing but playing around with the type defs as well as searching online didn't reveal anything.

Please note that `Omit` will be [included in Typescript 3.5](https://devblogs.microsoft.com/typescript/announcing-typescript-3-5/) and is defined as
```ts
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
```

In any case: Thanks a lot for this nice project!

**Comment by gcanti** [comment]
@2beaucoup assuming a well-typed implementation of `omit` (or similar helpers)

```ts
declare function omit<O, K extends keyof O>(o: O, k: K): Omit<O, K>
```

you can do

```ts
const B = t.type(omit(AB.props, 'a'))
```

**Comment by 2beaucoup** [comment]
Thanks! That looks good. Do you think that makes sense as a standard function?

**Comment by gcanti** [comment]
I think I would prefer to keep it external to the core library

**Comment by mohsensaremi** [comment]
@gcanti
Your solution for omitting only works on `t.type` codecs.
What if we want to omit fields from `t.intersection` codec or `t.strict` codec?
For example:
```
const Codec1 = t.intersection([
    t.type({
        field1: t.string,
        field2: t.string,
    }),
    t.type({
        field3: t.string,
        field4: t.string,
    }),
]);

const Codec2 = omit(Codec1, 'field2', 'field3')
```

**Comment by field123** [comment]
@mohsensaremi Did you find a solution or workaround for this?

**Comment by mohsensaremi** [comment]
@field123 Unfortunately NO :(

**Comment by StefanoA1** [comment]
@mohsensaremi @field123 
The solution would be (a little messy, but solution nonetheless), to get types from your intersection and re-build the type object:
```
const Codec1 = t.intersection([
    t.type({
        field1: t.string,
        field2: t.string,
    }),
    t.type({
        field3: t.string,
        field4: t.string,
    }),
]);
// Codec1.types[0].props contains field1 & field2
const Codec2 = t.type(omit({...Codec1.types[0].props, ...Codec1.types[1].props}, 'field2', 'field3'));
```
I'd argue there should be a function that converts an intersection to a type though (to avoid the `{...Codec1.types[0].props, ...Codec1.types[1].props}` step.

**Comment by sarakusha** [comment]
```ts
function getProps<T extends t.HasProps>(codec: T): t.TypeOf<T> {
  switch (codec._tag) {
    case 'RefinementType':
    case 'ReadonlyType':
      return getProps(codec.type);
    case 'InterfaceType':
    case 'StrictType':
    case 'PartialType':
      return codec.props;
    case 'IntersectionType':
      return codec.types.reduce<t.TypeOf<T>>(
        (props, type) => Object.assign(props, getProps(type)),
        {}
      );
    default:
      throw new TypeError('Invalid codec');
  }
}

export const omit = <C extends t.HasProps, O extends keyof t.TypeOf<C>>(
  codec: C,
  k: O
): t.TypeC<Omit<t.TypeOf<C>, O>> => {
  const { [k]: prop, ...props } = getProps(codec);
  return t.type(props);
};
```

**Comment by mathieulb** [comment]
I can't really understand why you'd want to leave that feature out of io-ts. Which features of TypeScript shouldn't have a rather direct equivalent in io-ts and why ? (I don't mean enumerating all those features, just where the line should be drawn between accepted features and rejected features)

**Comment by jpdenford** [comment]
For passing travellers, a tweak I had to make on @sarakusha's code (thank you btw) was to change the return type of `omit` to `t.Type<Omit<t.TypeOf<C>, O>>` instead of `t.TypeC<t.Ty...`. Otherwise the generated type had the correct keys but all the values were of type `unknown`.

```ts
function getProps<T extends t.HasProps>(codec: T): t.TypeOf<T> {
  switch (codec._tag) {
    case 'RefinementType':
    case 'ReadonlyType':
      return getProps(codec.type);
    case 'InterfaceType':
    case 'StrictType':
    case 'PartialType':
      return codec.props;
    case 'IntersectionType':
      return codec.types.reduce<t.TypeOf<T>>(
        (props, type) => Object.assign(props, getProps(type)),
        {}
      );
    default:
      throw new TypeError('Invalid codec');
  }
}

export const omit = <C extends t.HasProps, O extends keyof t.TypeOf<C>>(
  codec: C,
  k: O
): t.Type<Omit<t.TypeOf<C>, O>> => {
  const { [k]: prop, ...props } = getProps(codec);
  return t.type(props);
};
```

**Comment by jpdenford** [comment]
It turns out that the `omit` function also needs to match on the `_tag` of the codec parameter and return the same type. Say if it's a _PartialType_ we want to retain that behaviour with the newly constructed one e.g.
```ts
if (codec._tag === 'PartialType') return t.partial(props)
// if (...) return Readonly, Strict etc...
return t.type(props)
```
 the same goes for readonly etc.
