### ISSUE TITLE
t.keyof produces errors on typescript 3.5.x

### ISSUE THREAD

**Issue by pgebheim** [gcanti/io-ts#343]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
In Typescript 3.5 the behavior of 
`{ [k: string]: unknown } ` changed, which now results in using `keyof` on enums to produce an error.

Changing this signature to `{ [k: string]: any }` produces the same effect for the underlying type deduction (I think)

For more information:
https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#-k-string-unknown--is-no-longer-a-wildcard-assignment-target

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

Example that compiles in 3.5.x:
https://www.typescriptlang.org/play/#code/AQUwdgrgtsCCwG8BQxXAPIDkCiwC8wARFtoQDQpoAqA6uvkbeoUgL5JIBmEYAxgC4BLAPZhgAd2HCAFAEMAXIgDaAaxABPRQGd+AJ0FgA5gF1FssOtYBKRB3ZJJM2FYDcSIA

Example the compiles in 3.4.x but not 3.5.x:
https://www.typescriptlang.org/play/#code/AQUwdgrgtsCCwG8BQxXAPIDkCiwC8wARFtoQDQpoAqA6uvkbeoUgL5JIBmEYAxgC4BLAPZhgAd2HCAFAEMAXIgDaAaxABPRQGd+AJ0FgA5gF1FPFWGHiwrAJSIO7JJJmxbAbiRA

**What is the expected behavior?**

I would expect keyof to work on enum types as the keys are constant.

**Which versions of io-ts, and which browser and OS are affected by this issue? Did this work in previous versions of io-ts?**

This effects all current versions of io-ts but breaks with a typescript upgrade.

NOTES:

Should we be using something like: 
https://github.com/gcanti/io-ts/issues/216

instead for enum verification?

**Comment by gcanti** [comment]
Actually that's a good thing, `keyof` doesn't support `enum`s

```ts
enum A {
  A = 'a',
  B = 'b'
}

// this codec validates the keys "A", "B" instead of the values "a", "b"
const T = t.keyof(A)

console.log(T.decode('A')) // ok
console.log(T.decode('a')) // error
```

**Comment by pgebheim** [comment]
Well you're right that IS a good thing -- my bad -- I was heads down in the typescript and I didn't notice that decode wouldn't validate values that didn't match the keys.

Really, in our specific case the `enum` is there as a syntactic sugar around string values, so the key and the value of the resulting object is always the same.

I would think that since I'm explicitly requesting the keys, and an enum is fundamentally a typed object in the TS land, that `t.keyof` would still work, as it did in pre-3.5.x.

That said, is #216 the proper way to handle enums with the current framework?

**Comment by gcanti** [comment]
I'm sorry, honestly I've never used `enum`s so I do not have any good advice about them

**Comment by sledorze** [comment]
Never used enums too, had way too much issues when evaluating them.

**Comment by pgebheim** [comment]
They're ultimately simple objects on the TS side, and `keyof` for them should just enumerate the keys of that object.

Simply changing the `keyof` defintion to use `{[key: string]: any}` keeps the previous behavior of io-ts which when running on TS < 3.5.x just enumerates the keys.

Since there is an explicit `keyof` this isn't actually doing anything unexpected, since the codec above isn't expected to do anything with the values.
