### ISSUE TITLE
Breaking change in v1.10.2

### ISSUE THREAD

**Issue by alcuadrado** [gcanti/io-ts#344]
### Current Behavior

I have a project that uses `io-ts`. It stopped working because of a new version of `io-ts`.

It has some code similar to this one

```ts
import * as t from "io-ts";

const Config = t.type(
  {
    a: t.string
  },
  "Config"
);

const result = Config.decode({a:123})

console.log(result.isRight());
```

This code used to work but now throws `isRight is not a function`.

### Expected behavior

It should still work, ie print `false`.

The last working version is `v1.9.0`.

`v1.10.0` and `v1.10.1` throw `Cannot find module 'fp-ts/lib/Either'`

### Reproducible example

See **Current Behavior**

### Suggested solution(s)

I can fix this in my local installation by running `npm i io-ts@1.9.0`, but I can't do that for my users. For them, my project just stopped working.

### Your environment

As I mention, this seems to have been introduced in `v1.10.2`. 
`v1.10.0` and `v1.10.1` just don't run because of an unmet peerDependency.

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |   v1.10.2     |
| fp-ts      |      v2.0.0      |
| TypeScript | v3.5.2       |

**Comment by alcuadrado** [comment]
Also, I wanted to mention that IMO `fp-ts` being a `peerDependency` is the right way of doing this. I really like [this article about it](https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/).

I'd just release `io-ts` `2.x` with `fp-ts` as a peer dep.

**Comment by gcanti** [comment]
@alcuadrado could you please check out which version of `fp-ts` you get in `node_modules`?

**Comment by gcanti** [comment]
@alcuadrado thanks for the bug report, I forgot to publish a patch before releasing `fp-ts@2.0.0`, I'm sorry for the inconvenience.

**Comment by alcuadrado** [comment]
Thanks for fixing this quickly!
