### ISSUE TITLE
Simple stupid validation example

### ISSUE THREAD

**Issue by steida** [gcanti/io-ts#348]
FP is nice and all, but 80 % of users will fail to use this lib without a super simple example of how to extract decoded value. There was a fold method at least. No there is nothing.

**Comment by steida** [comment]
OK, it's this:

```ts
import { either } from 'fp-ts/lib/Either';
either.map(AppHrefIO.decode(routerAppHref), value => {
  maybeAppHref = value;
});
```

**Comment by giogonzo** [comment]
In general you can use `pipe` + `fold` to handle the two possible results:

```ts
import * as t from 'io-ts';
import { pipe } from 'fp-ts/lib/pipeable';
import { fold } from 'fp-ts/lib/Either';

pipe(
  t.string.decode('asd'),
  fold(
    errors => {
      // handle validation errors
    },
    value => {
      // value has type `string` here
    }
  )
);
```

Here's a side-effectful function helper (if throwing is more of your jam):
```ts
import { identity } from 'fp-ts/lib/function';

function valueOrThrow<A, O, I>(codec: t.Type<A, O, I>, value: I): A {
  return pipe(
    codec.decode(value),
    fold(() => {
      throw Error('invalid value');
    }, identity)
  );
}
const s: string = valueOrThrow(t.string, 'asd');
```

**Comment by mlegenhausen** [comment]
I use a the following code

```ts
import * as E from 'fp-ts/lib/Either';
import { pipe } from 'fp-ts/lib/pipeable';
import * as t from 'io-ts';
import { failure } from 'io-ts/lib/PathReporter';

export const cast = <I, A>(codec: t.Decoder<I, A>) => (value: I): A =>
  pipe(
    codec.decode(value),
    E.getOrElse<t.Errors, A>(err => {
      throw new Error(failure(err).join('\n'));
    })
  );
```

```
cast(t.Int)(42) // 42
cast(t.Int)(Math.PI) // Uncaught Error: Invalid value 3.141592653589793 supplied to : Int
```

Little side note I use the same function in combination with branded types to create static branded instances, which are defined at the top of each module. This allows me to combine the power of branded types during compile time and the safety that my program will immediately crash on startup when a branded type was defined wrong.

**Comment by Frikki** [comment]
@mlegenhausen 

> I use the same function in combination with branded types to create static branded instances, which are defined at the top of each module. This allows me to combine the power of branded types during compile time and the safety that my program will immediately crash on startup when a branded type was defined wrong.

Could you show an example of how you do this?

**Comment by mlegenhausen** [comment]
@Frikki as simple as the usage example something like:

```ts
import { cast, t } from 'prelude'

export const myInt = cast(t.Int)(42)

// some other stuff that uses my `myInt`
```

This would be impure code, but it should fail immediately in any testing environment and I find it more reliable than an unsafe cast like

```ts
export const myInt: t.Int = ((42 as any) as t.Int)
```

which gives you no feedback at all.
