### ISSUE TITLE
is there a way to turn the checks off in production code?

### ISSUE THREAD

**Issue by aleksey-bykov** [gcanti/io-ts#35]
this lib is useful at testing and development stages, but in production these checks might hurt performance, is there a way to turn them all off?

**Comment by gcanti** [comment]
No, however you can define your own logic for that (if you *really* trust the input), for example

```ts
import * as t from 'io-ts'
import { pathReporterFailure } from 'io-ts/reporters/default'

function validate<T>(value: any, type: t.Type<T>): T {
  if (process.env.NODE_ENV !== 'production') {
    return t.validate(value, type)
      .fold<T>(
        errors => { throw new Error(pathReporterFailure(errors).join('\n')) },
        x => x
      )
  }
  return value as T
}

console.log(validate(1, t.string)) // throws Invalid value 1 supplied to : string

process.env.NODE_ENV = 'production'

// unsafe
console.log(validate(1, t.string)) // 1
```

**Comment by gyzerok** [comment]
I guess the whole purpose of the library is to be used in production to prevent runtime crashes.

**Comment by aleksey-bykov** [comment]
true in case you cant trust your production data, we can

**Comment by gyzerok** [comment]
Then why would you use the library?

JSON.parse(trustedData) as MyType

**Comment by aleksey-bykov** [comment]
for ongoing development when unexpected database changes are likely

**Comment by gcanti** [comment]
> unexpected database/serverside changes are likely

At buildo, in order to tame unexpected changes, we are going to generate client side schemas and static types from Scala models, see

- https://github.com/gcanti/gen-io-ts (WIP)
- https://github.com/buildo/metarpheus-io-ts (WIP)
- https://github.com/buildo/metarpheus

Likely this will allow to catch breaking changes between server and client statically

**Comment by aleksey-bykov** [comment]
yes, generating both server and client schema from the same definition is the best way foraward for a project where a local database/server side team is a friend to the consultants who were hired to write the frontend

**Comment by aleksey-bykov** [comment]
https://en.wikipedia.org/wiki/Conway%27s_law
