### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SAnDAnGE** [gcanti/io-ts#354]
### Current Behavior

`RangeError: Maximum call stack size exceeded`

### Expected behavior

No error

### Reproducible example

https://stackblitz.com/edit/typescript-3kmxjd

### Suggested solution(s)

Memoisation, Tail Call Optimisation, Trampolining
https://blog.logrocket.com/using-trampolines-to-manage-large-recursive-loops-in-javascript-d8c9db095ae3/

### Additional context

The code in this example is generated using io-ts-codegen.
This code is used to decode forms that are shown to the user to be filled using angular components.

### Your environment

Which versions of io-ts are affected by this issue?

io-ts@2.0.0

Did this work in previous versions of io-ts?

Not as far as I know.

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |      2.0.0      |
| fp-ts      |      2.0.3      |
| TypeScript |  3.4.5+          |

**Comment by gcanti** [comment]
@SAnDAnGE thanks for the bug report

**Comment by SAnDAnGE** [comment]
@gcanti Thank you for the quick fix ! Keep up the great work ! :)
