### ISSUE TITLE
Building a simple dictionary codec

### ISSUE THREAD

**Issue by mikedloss** [gcanti/io-ts#362]
Hi, new to `io-ts`. Trying to create a codec for a simple dictionary:

```
interface Dictionary<T> {
  [k: string]: T;
}
```

I know I can get _kind of_ close with this:

```
const Dictionary = t.UnknownRecord
```

but that isn't exactly what I'm looking to build. I know `t.dictionary` exists in some regard but I have no idea how to use it 😅

Any suggestions or help would be great!

**Comment by giogonzo** [comment]
Hi @mikedloss , you can use the `record` combinator to obtain it:
```ts
t.record(t.string, t.number)
```

If you want to make it generic, as it is in your example, you have to use a function (this applies to every generic type expressed with `io-ts`):

```ts
function MyDictionary<T extends t.Mixed>(T: T) {
  return t.record(t.string, T)
}
```

The "Dictionary" name (`t.dictionary`) has been deprecated a while back in favor of "Record" to better align with the built-in TypeScript type `Record`:
<img width="714" alt="Screenshot 2019-09-04 at 14 30 28" src="https://user-images.githubusercontent.com/2643520/64255337-7678a800-cf21-11e9-8f8e-60eb214e9194.png">

**Comment by mikedloss** [comment]
@giogonzo perfect, exactly what I was looking for. I was headed in the direction of using `t.record` but, again being new to `io-ts`, I wasn't really sure what was being generated from `t.record` 😬

Thank you!

**Comment by mikedloss** [comment]
@giogonzo actually, I might've spoken too soon... when implementing it in this codec:

```
const Request = t.interface({
  path: t.string,
  params: t.union([Dictionary, t.string])
})
```

it's complaining about this:

```
Type '<T extends Mixed>(v: T) => RecordC<StringC, T>' is missing the following properties from type 'Mixed': is, validate, encode, _A, and 6 more.ts(2740)
```

(btw, this is the interface I'm recreating:
```
interface Request {
  path: string;
  params: Dictionary<any> | string;
}

//
const Dictionary = <T extends t.Mixed>(v: T) => t.record(t.string, v);
```
)

**Comment by giogonzo** [comment]
yeah sorry, I didn't provide a "usage" example in my previous answer. Anyway, since a generic type is encoded with a function in `io-ts`, you'll always have to call the function to obtain a proper type:
```
const Request = t.interface({
  path: t.string,
  params: t.union([Dictionary(t.any), t.string])
})
```

What you're trying to do above would be equivalent in plain TS to:
```ts
interface Request {
  path: string;
  params: Dictionary | string; // Error: Generic type 'Dictionary<T>' requires 1 type argument(s).
}
```

**Comment by mikedloss** [comment]
Oh my gosh 🤦🏻‍♂️ of course - Dictionary is a function. Completely slipped my mind, I think because this is the first time I had to do something like this with `io-ts`.
