### ISSUE TITLE
Defining types with arbitrary keys

### ISSUE THREAD

**Issue by alecgibson** [gcanti/io-ts#365]
### Current Behavior

At the moment, I think you have to define every key in a type?

### Desired Behavior

In TypeScript, you can define interfaces like:

```typescript
interface IThing {
  [key: string]: IOtherThing;
}
```

I can't figure out how / if this is possible in `io-ts`.

### Suggested Solution

I sadly don't know enough about the library to propose a suggestion. Please do let me know if this is already possible, and I've just missed some docs (or the docs aren't there - always happy to raise a PR for doc improvement)

### Who does this impact? Who is this for?

Useful for TypeScript users who would like to validate objects with arbitrary keys (eg storing objects by ID).

### Describe alternatives you've considered

Could use `t.any` and manually validate the sub-objects, which is certainly doable, just not ideal.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |    2.0.1        |
| fp-ts      |            |
| TypeScript |   2.7.2         |

**Comment by giogonzo** [comment]
@alecgibson I think you are looking for `t.record(t.string, MyCodomainType)`? Which is the `io-ts` counterpart of `Record<string, MyCodomainType>` in TS

**Comment by giogonzo** [comment]
please see also https://github.com/gcanti/io-ts/issues/362

**Comment by alecgibson** [comment]
Awesome. Thanks for the fast response. I'll have a play around with it later today. Might try to raise a small PR to clarify in the docs (I've been using TS for a while, and yet the more technical names of things like `Record` don't really come up that often).
