### ISSUE TITLE
Benchmark testing

### ISSUE THREAD

**Issue by moltar** [gcanti/io-ts#368]
Hi Giulio,

I have been using `io-ts` and other similar runtime type checking libraries on various projects.

I decided to run some benchmarks on all of these libraries and do a write up about all of the options and pros and cons of each.

My preliminary results are [published in this repo](https://github.com/moltar/typescript-runtime-type-benchmarks).

I was wondering if you could take a look at that repo and see if the usage is fair and if I am not using the library in some disadvantaged way.

Here is `io-ts` specific test: https://github.com/moltar/typescript-runtime-type-benchmarks/blob/master/cases/io-ts.ts

The goal is to get the object validated and type guarded or returned type established.

Thanks!

**Comment by giogonzo** [comment]
Hi @moltar , the `io-ts` test looks 👍 to me at a first glance.

Comparing the `io-ts` test with the `runtypes` one, one minor inconsistency I could spot is that for runtypes, the `Record` combinator is being tested, while for `io-ts` you are using `t.strict`.
I doubt this will impact the test significantly, but `strict/exact` in `io-ts` have additional logic to [strip all the "excess" fields](https://github.com/gcanti/io-ts/blob/master/src/index.ts#L1564-L1577), while `Record` from runtypes [apparently doesn't](https://github.com/pelotom/runtypes/blob/master/src/types/record.ts#L22-L48).

**Comment by moltar** [comment]
Great observation, thanks. Fixed! I'll close the issue then, but if anyone has any other details, feel free to add them even after the fact. I will try to address them in my benchmark repo. Or just open issues in the [benchmark repo](https://github.com/moltar/typescript-runtime-type-benchmarks/issues) right away.
