### ISSUE TITLE
Is it possible to write a codec whose output type properties names differ from the input?

### ISSUE THREAD

**Issue by loxs** [gcanti/io-ts#369]
Because of code style requirements I'm in the situation where I can't use the default behaviour of object types in io-ts. I'd like to be able to specify the property name to be decoded into my own property name. How can I do that?

Basically I need something like: 

```
const MyCodec = t.type({
  fullName: t.string({key: 'full_name'})
})
```

Is this possible with the current io-ts or will I have to write some glue code where I first rename the object keys?

**Comment by giogonzo** [comment]
Yes. In general, the types of output (`O`) and runtime (`A`) can differ in io-ts. For more complex scenarios you'd have to implement your own validations by creating a new codec using `new Type(...)`, but for this simple mapping it should be possible to use `mapOutput` from `io-ts-types`:

```ts
const T: t.Type<
  {
    full_name: string;
  },
  {
    fullName: string;
  }
> = mapOutput(t.type({ full_name: t.string }), o => ({ fullName: o.full_name }));
```
(annotation is not strictly needed, I put it there just to make the example clear)

**Comment by mohaalak** [comment]
> Yes. In general, the types of output (`O`) and runtime (`A`) can differ in io-ts. For more complex scenarios you'd have to implement your own validations by creating a new codec using `new Type(...)`, but for this simple mapping it should be possible to use [`mapOutput`](https://github.com/gcanti/io-ts-types/blob/master/src/mapOutput.ts) from `io-ts-types`:
> 
> ```ts
> const T: t.Type<
>   {
>     full_name: string;
>   },
>   {
>     fullName: string;
>   }
> > = mapOutput(t.type({ full_name: t.string }), o => ({ fullName: o.full_name }));
> ```
> 
> (annotation is not strictly needed, I put it there just to make the example clear)

I don't get how can I create  a codec that behaves like this
```
const MyCodec = t.type({
  fullName: t.string({key: 'full_name'})
})
```
cause if I create a new type for  `t.string` in`validate` function I don't have access the object so I get the field with the provided `key`

**Comment by mlegenhausen** [comment]
@mohaalak you can't. `t.string` has no access to its parent. The transformations needs to happen in the `t.type` thats what `mapOutput` is for.

**Comment by tkreis** [comment]
Sorry to stir up this old ticket, but would `mapOutput` really work here? 

Unless I'm super mistaken `mapOutput` is only invoked on `encode` but not `decode`.

**Comment by angeloashmore** [comment]
For anyone else coming across this, indeed the above `mapOutput` example does not work with `decode`, unless I'm misunderstanding how to properly use it.

I'm using this function to map input properties. It could be combined with `mapOutput` if you need to go in both directions:

```ts
import * as t from 'io-ts'
import * as tt from 'io-ts-types'

function mapInput<A, O, I, H>(
  codec: t.Type<A, O, I>,
  f: (p: H) => I,
  name: string = codec.name,
): t.Type<A, O, H> {
  return new t.Type(
    name,
    codec.is,
    (i, c) => codec.validate(f(i), c),
    codec.encode,
  )
}

const T: t.Type<
  { fullName: string },
  { fullName: string },
  { full_name: string }
> = mapInput(
  t.type({
    fullName: t.string,
  }),
  (i) => ({
    fullName: i.full_name,
  }),
)

const U: t.Type<
  { fullName: string },
  { full_name: string },
  { full_name: string }
> = tt.mapOutput(
  mapInput(
    t.type({
      fullName: t.string,
    }),
    (i) => ({
      fullName: i.full_name,
    }),
  ),
  (o) => ({ full_name: o.fullName }),
)
```

I'm not sure if the newer `Decoder` and `Encoder` modules simplifies this. If not, would this be helpful to include in `io-ts-types` @gcanti?

**Comment by gcanti** [comment]
> I'm not sure if the newer Decoder and Encoder modules simplifies this

@angeloashmore with the newer modules would be something like

```ts
import { pipe } from 'fp-ts/function'
import * as D from 'io-ts/lib/Decoder'

const MyDecoder = pipe(
  D.type({
    fullName: D.string
  }),
  D.map((o) => ({ full_name: o.fullName }))
)
```

or

```ts
import * as C from 'io-ts/lib/Codec'

const MyCodec = pipe(
  C.type({
    fullName: C.string
  }),
  C.imap(
    (o) => ({ full_name: o.fullName }),
    (o) => ({ fullName: o.full_name })
  )
)
```

**Comment by angeloashmore** [comment]
@gcanti Thanks, that's beautiful 👌

**Comment by CMCDragonkai** [comment]
Is my understanding correct here that `new t.Type` is only intended to be used for types that have serialized inputs that match exactly the same data shape, but type is unknown?

And then if we are meant to be transforming the data shape of input/output, we are meant to be creating our own encoders/decoders/codec? This was quite confusing for me, since the README.md put these into the "unstable" section.

**Comment by lambdahands** [comment]
Hello! I was also interested in the use cases mentioned here, so I took what @angeloashmore had put together with `mapInput` and came up with a function `sequenceCodecs` (the name could probably be better!):

```ts
function sequenceCodecs<A, B, O, P, H, I>(
  inputCodec: t.Type<A, O, H>,
  transform: (decoded: A) => I,
  outputCodec: t.Type<B, P, I>,
  name: string = outputCodec.name
): t.Type<B, P, H> {
  return new t.Type(
    name,
    outputCodec.is,
    (input, context) =>
      e.chain((decoded: A) => {
        return outputCodec.validate(transform(decoded), context);
      })(inputCodec.validate(input, context)),
    outputCodec.encode
  );
}
```

I wanted to validate some input, transform it, and then validate the output of the transformation. For changing a key, it may look something like:

```ts
const Person = sequenceCodecs(
  t.type({ full_name: t.string}),
  decoded => ({ fullName: decoded.full_name }),
  t.type({ fullName: t.string })
);
```

For my use case, the real challenge was accepting two different fields that represent the same value and consolidating them into one. For example:

```ts
const Person = sequenceCodecs(
  t.partial({ full_name: t.string, legacy_full_name: t.string}),
  decoded => ({ fullName: decoded.full_name || decoded.legacy_full_name }),
  t.type({ fullName: t.string })
);
```

I'm also new to this library, so I'm not entirely sure if this function results in some information loss on the type level, but I thought I'd share if anyone found this useful.

**Comment by mlegenhausen** [comment]
@lambdahands try to narrow down your `inputCodec` when at least one of the attributes should exists. You should define it as follows:

```ts
t.union([t.type({ full_name: t.string }), t.type({ legacy_full_name: t.string })])
```

then `outputCodec` should not be needed anymore cause at least one of the properties need to exist or you get a validation error.

**Comment by lambdahands** [comment]
Hi @mlegenhausen, thanks for the response! I'm not sure if that satisfies my requirements since the data I'm passing in is unknown, and I want to _only_ expose `full_name` to the consumers of my resulting type, which may also include additional fields beyond the input type. So maybe I should have illustrated it a bit better like so:

```ts
type Person = t.TypOf<typeof Person>;
const Person = sequenceCodecs(
  t.partial({ full_name: t.string, legacy_full_name: t.string}),
  decoded => ({ fullName: decoded.full_name || decoded.legacy_full_name }),
  t.type({
    fullName: t.string,
    age: t.number,
    numberOfPets: t.number
  })
);
```

**Comment by mlegenhausen** [comment]
Even then the second validation is redundant. Lets define what data you expect to enter your program and the model you want to process further:

```ts
const UnknownPerson = t.intersection([
  t.type({
    age: t.number,
    numberOfPets: t.number
  }),
  t.union([
    t.type({ full_name: t.string }),
    t.type({ legacy_full_name: t.string })
  ])
])
export type UnknownPerson = t.TypeOf<typeof UnknownPerson>

interface Person {
  fullName: string
  age: number
  numberOfPets: number
}

const transform = (p: UnknownPerson): Person =>
  ({ ...p, fullName: decoded.full_name || decoded.legacy_full_name })
```

I know the temptation to put everything in codecs that look like data transformation but it is recommended to just describe what data enters your program and then write simple transformation functions that map the data to your target definition.

**Comment by lambdahands** [comment]
Thanks for clarifying further @mlegenhausen. One thing concerning this point, though:

> Even then the second validation is redundant.

The second validation does still check that the resulting `fullName` passed in from the transformation function is a `string` - since the `t.partial` checks that the input data is an "object" whose fields `full_name` and `legacy_full_name` are either undefined or strings. That is, the transformation function could still provide an undefined `fullName` value in which case the validation should fail.

I think what you provided is much simpler, but maybe the real issue I'm having is using a union type with unknown input data, as the resulting TypeScript type is:

```ts
{ full_name: string } | { legacy_full_name: string }
```

...which unfortunately leads to an awkward situation where neither field can be referenced as it doesn't exist in both types in the union. For example, the transform function you provided won't compile:

```
Property 'full_name' does not exist on type '{ age: number; numberOfPets: number; } & { legacy_full_name: string; }'.

Property 'legacy_full_name' does not exist on type '{ age: number; numberOfPets: number; } & { full_name: string; }'.
```

Thank you again for your patience - I'd also be happy to move this to a Discord/Slack chat so as not to veer this issue too far off topic.

**Comment by levino** [comment]
> ```ts
> import * as C from 'io-ts/lib/Codec'
> 
> const MyCodec = pipe(
>   C.type({
>     fullName: C.string
>   }),
>   C.imap(
>     (o) => ({ full_name: o.fullName }),
>     (o) => ({ fullName: o.full_name })
>   )
> )
> ```

I hope it is okay to resurrect this old issue for a question: I am using a lot of other `t` methods like `t.exact`, `t.Type` (mind the capital T) etc. When I try to use `Codec` this all breaks down and I am struggling to get it working again because Codec does not have `C.exact` for example. What to do?
