### ISSUE TITLE
How to construct a runtime type from a static type

### ISSUE THREAD

**Issue by stephen-ciq** [gcanti/io-ts#374]
I am trying to find a way to build a non-custom runtime `io-ts` type from a static Typescript type.  I understand that one can extract a static type from a runtime type, but I'd like to keep my type definitions separate from the use of any library.

I understand that

> The advantage of using io-ts to define the runtime type is that we can validate the type at runtime, and we can also extract the corresponding static type, so we don’t have to define it twice.

but essentially I would like to be able to do the reverse without defining `encode` and `decode` methods.  

In other words, instead of 

```
const RuntimeUserType = t.type({
    userId: t.number,
    name: t.string
});

```

I would like to be able to do 
```
type User = {
    userId: t.number,
    name: t.string
};
```

and then make `RuntimeUserType` from the static type `User`.  Maybe I overlooked it, but I can't find a way to do this without building a custom type.

**Comment by mlegenhausen** [comment]
There is no typescript at runtime, so there is no type information. The only other way would be to use a code generator that uses your type and generates `io-ts` out of it. This way was discussed several times here in the issue tracker.
