### ISSUE TITLE
t.type.is() doesn't match TypeScript behavior for optional fields

### ISSUE THREAD

**Issue by ChaosinaCan** [gcanti/io-ts#381]
### Current Behavior

`t.type.is()` returns `false` if fields are missing, even if `t.undefined` is a valid type for those fields.

### Expected behavior

Type guards should treat a missing field and `undefined` the same way.

```ts
// TypeScript treats these as equivalent:
interface Test1 {
    foo: string;
    bar?: string;
}
interface Test2 {
    foo: string;
    bar: string | undefined;
}

// But these are not equivalent in io-ts:
// This works as expected but produces complex type names in error messages.
const Test1 = t.intersection([
    t.type({
        foo: t.string,
    }),
    t.partial({
        bar: t.string,
    }),
});
// This produces nice type names in error messages, but doesn't work as expected.
const Test2 = t.type({
    foo: t.string,
    bar: t.union([t.string, t.undefined]),
});
```

### Reproducible example

```ts
const TestType = t.type({
    foo: t.string,
    bar: t.union([t.string, t.undefined]),
});
TestType.is({ foo: 'foo', bar: 'bar' }); // true
TestType.is({ foo: 'foo', bar: undefined }); // true
TestType.is({ foo: 'foo' }); // false
```

### Suggested solution(s)

I think this could be fixed by removing the `hasOwnProperty()` check from https://github.com/gcanti/io-ts/blob/fec4c47c144943a67550cccf6c601b30ec55e345/src/index.ts#L776 so that `undefined` is passed to `types[i].is()` when a key is missing.

### Additional context

Related: #328

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |  2.0.1          |
| fp-ts      | 2.1.2           |
| TypeScript | 3.7.2           |

**Comment by gcanti** [comment]
> TypeScript treats these as equivalent

Looks like it doesn't

```ts
interface Test1 {
  foo: string
  bar?: string
}
interface Test2 {
  foo: string
  bar: string | undefined
}

const x = { foo: 'foo' }
const y: Test1 = x // ok
const z: Test2 = x // error: Property 'bar' is missing in type '{ foo: string; }' but required in type 'Test2'
```

**Comment by ChaosinaCan** [comment]
Hmm. I assumed that since `bar?: string` is treated as `string | undefined`, the reverse was also true. Is it correct then that this happens?

```ts
const Test = t.type({
    foo: t.union([t.string, t.undefined]),
});
Test.is({}); // false
Test.decode({}); // { _tag: 'Right', right: { foo: undefined } }
```

I would have also expected `decode()` to require that the key exists.

What I'm really after is a type that shows up like `{ foo: string, bar?: string }` in errors instead of `{ foo: string } & Partial<{ bar: string }>`. I'll try making a custom type that wraps `t.intersection([t.type(), t.partial()])` to give it a nice name and hide away the extra path components in errors.
