### ISSUE TITLE
Provide a Type from a known alias?

### ISSUE THREAD

**Issue by mikecann** [gcanti/io-ts#382]
Apologies if this is the wrong place for this, its more of a question than a bug or feature request. 

I was wondering if there is a way that I can tell io-ts 'trust me, its this type' sort of thing?

So for example I have the following:

```
export const Subscription = t.strict({
  stripeSubscription: t.union([t.null, t.unknown]),
});
export type Subscription = t.TypeOf<typeof Subscription>;
```

I is there a way to tell io-ts that the type of stripeSubscription isnt `null | unknown` it actually will be `Stripe.subscriptions.ISubscription | unknown` without me having to define the full runtime type? 

I know I could just do:

`export type Subscription = t.TypeOf<typeof Subscription> & { stripeSubscription: Stripe.subscriptions.ISubscription | null  }` 

But I was wondering if there was a different approach that would make it work with t.TypeOf

**Comment by mlegenhausen** [comment]
Take a look at [mapOutput](https://github.com/gcanti/io-ts-types/blob/master/src/mapOutput.ts)

```ts
mapOutput(t.any, a => a as Stripe.subscriptions.ISubscription)
```

**Comment by mikecann** [comment]
@mlegenhausen Hmm.. `mapOutput` isnt available in the latest library, but when I copy the function to my project I get the following:

![image](https://user-images.githubusercontent.com/215033/69588074-7a98fb00-1022-11ea-95b3-9fc7795cd26b.png)

**Comment by mikecann** [comment]
Nevermind, I decided my approach was probably wrong anyways.
