### ISSUE TITLE
transformation for types

### ISSUE THREAD

**Issue by mohaalak** [gcanti/io-ts#383]
I want to know if there is an easy way that changes the key name so
 think it this way that we have some data like 
```
{
 customer_id: 2
customer_name: 'hadi'
}
```

we could set a type like

```
const Customer = t.type({
  id: t.number('customer_id'),
 name: t.string('customer_name')
})
```

now keys that something we support, I know this way is not compatible with what we have but if in `Context` there was the whole object that is going to be decoded and every part that comes here we can create a new decoder that transforms data then create the type and check runtime.

**Comment by mlegenhausen** [comment]
Duplicate https://github.com/gcanti/io-ts/issues/369
