### ISSUE TITLE
How to I check the type of a plain object at runtime?

### ISSUE THREAD

**Issue by ArondeParon** [gcanti/io-ts#384]
I feel that I am overlooking something, so if this question has already been answered somewhere, feel free me to point in the right direction.

I created a somewhat generic JSON parser that basically looks like this:

```js
parse(): FooType | BarType {
    switch (this.data.action) {
        case 'foo':
            return FooType.decode(this.data);        
        case 'bar':
            return BarType.decode(this.data);
}
```

I would like to have call this `parse()` function from somewhere else and determine wether the decoded type is of type `FooType` or `BarType` without doing introspection on the object, but I am having a really hard time getting it to work.

The idea behind it is to make the implementing code care less about the structure of the object and to benefit from the type hint that would be provided by the result:

```js
doStuffWithData(data: any) {
    const data = (new Parser(data).parse());

    // This is what I would _like_ to do. 
    // "instanceof" should probably be some kind of helper function
    if (data instanceof FooType) {
        doFooStuff();
    } else if (data instanceof BarType) {
        // you get the point
    }
}
```

Any help would be  greatly appreciated.

**Comment by giuscri** [comment]
If I understand this, you're missing that `.decode()` returns an `Either<Errors, A>`. Also, you should extract the _static type_ from the runtime type: `type IFooType = t.TypeOf<typeof FooType>`.

Then `data.right instanceof IFooType` should be valid syntax -- assuming decoding has been successful.

**Comment by ArondeParon** [comment]
Thanks for getting back to me this soon.

I just tested this, but would `instanceof iFooType` not break because it refers to a TypeScript type that is not available during runtime?

**Comment by mlegenhausen** [comment]
I would try to solve it this way

```ts
const FooType = t.interface({
  action: t.literal('foo')
})
const BarType = t.interface({
  action: t.literal('bar')
})
const FooBarType = t.union([FooType, BarType])
type FooBarType = t.TypeOf<typeof FooBarType>

const data: Either<t.Errors, FooBarType> = FooBarType.decode(this.data)

if (E.isRight(data)) {
  switch (data.right.action) {
    case 'foo':
      // data.right equals your FooType
    case 'bar':
      // data.right equals your BarType
  }
}
```

Don't use `instanceof` instead use a literal value on your data structure.

**Comment by ArondeParon** [comment]
@mlegenhausen thanks for the input!

That is pretty much what I do right now as well: inspect a property inside a `switch` statement.

I still feel that this is not ideal though, because I have to do inspection on my object contents instead of checking the type of my object.

**Comment by mlegenhausen** [comment]
This only applies when you use OOP. `io-ts` comes from FP where checking the type by a property is totally common. This is why it works so great with literal values on objects.

**Comment by ArondeParon** [comment]
Fair enough. Thanks for the feedback!
