### ISSUE TITLE
unsafeDecode

### ISSUE THREAD

**Issue by steida** [gcanti/io-ts#395]
## 🚀 Feature request

It's pretty rare but sometimes useful to throw instead of returning Either. 

### Suggested Solution

```ts
/**
 * Unsafe version of `decode` which returns value or throws. In functional programming,
 * we never throw, but it can be ok for statically defined values. In such a case, an app
 * will throw on start, which is safe enough. It can be handy for tests, localization
 * messages, or error values. Or anything else which is statically defined like configuration etc.
 */
unsafeDecode(i: I): A {
  // TODO:
}
```

I suppose it could be useful addition to io-ts, if well explained why it exists.

**Comment by cyberixae** [comment]
@steida I created a package called [ruins-ts](https://www.npmjs.com/package/ruins-ts) for such cases.

**Comment by cyberixae** [comment]
@steida you may wish to validate to my new io-ts specific package [io-ts-validator](https://www.npmjs.com/package/io-ts-validator). It should provide you with simpler error messages. It is used as follows.

```typescript
import * as t from 'io-ts';
import { validator } from 'io-ts-validator';

const testInput: unknown = ['foo', 'bar'];
const valid: Array<string> = validator(t.array(t.string)).decodeSync(testInput);
```
The above code will throw on error.
