### ISSUE TITLE
Transpile TS code to JS with embedded type-safe assertions/warnings

### ISSUE THREAD

**Issue by niieani** [gcanti/io-ts#4]
Hi @gcanti. Fantastic idea. I was just wondering if you saw the Flow-equivalent project?

https://github.com/codemix/flow-runtime/

It would be great if there was a way to transpile TS-code to JS with type-safe assertions/warnings, similar to how flow-runtime works. Do you think it's within the scope of your project?

**Comment by gcanti** [comment]
Relevant https://github.com/gcanti/flow-io/issues/19

**Comment by goodmind** [comment]
@niieani hey, it looks that https://github.com/Microsoft/TypeScript/pull/13940 is what you need. It allows writing AST transformations so you can replace interfaces/types with runtime representation like `flow-runtime` does

**Comment by gcanti** [comment]
@goodmind Interesting, thanks for the link

> so you can replace interfaces/types with runtime representation

@niieani what's the main use case for this?

**Comment by niieani** [comment]
@gcanti best use case currently is ensuring the points-of-contact of typed and untyped code are valid, i.e. the contracts that the types are, hold up in practice. Another one would be points-of-contact for deserializers, or when verifying that interfaces for external data (e.g. JSON from the server) are correct. 

We currently use `flow-runtime` for the very same reasons in development (naturally this is _off_ in production builds), but helps to find subtle bugs in both of these cases.

**Comment by gcanti** [comment]
@niieani Indeed IO validation is the main goal of io-ts, though validations must be defined "by hand"

```ts
import * as t from 'io-ts'
import { pathReporterFailure } from 'io-ts/reporters/default'

function validateEndpoint<T>(value: any, type: t.Type<T>): Promise<T> {
  if (process.env.NODE_ENV !== 'production') {
    return t.validate(value, type)
      .fold<Promise<T>>(
        errors => Promise.reject(pathReporterFailure(errors)),
        x => Promise.resolve(x)
      )
  }
  return Promise.resolve(value)
}

function validate<T>(value: any, type: t.Type<T>): T {
  if (process.env.NODE_ENV !== 'production') {
    return t.validate(value, type)
      .fold<T>(
        errors => { throw new Error(pathReporterFailure(errors).join('\n')) },
        x => x
      )
  }
  return value
}

const RTPerson = t.interface({
  name: t.string
})

// can be extracted from RTPerson
type Person = {
  name: string
}

function untrustedEndpoint(id: string): Promise<{ data: Person }> {
  return Promise.resolve({ data: {} })
}

function untrustedLibraryAPI(a: number, b: number): number {
  return a + 'wrong' as any // should be a sum
}

untrustedEndpoint('id')
  .then(res => validateEndpoint(res.data, RTPerson))
  .then(
    person => console.log(person),
    error => console.error(error) // => [ 'Invalid value undefined supplied to : { name: string }/name: string' ]
  )

validate(untrustedLibraryAPI(1, 2), t.number) // throws Invalid value "1wrong" supplied to : number
```

Now back to this issue (Transpile TS code to JS), what would you like to have or what do you do with flow-runtime in order to get the same behavior? I'd love to see some pratical example in order to understand correctly what you mean

**Comment by niieani** [comment]
@gcanti I think this behavior is pretty much the ideal, given it supports all the TS-specific features: https://codemix.github.io/flow-runtime/#/try

**Comment by gcanti** [comment]
@niieani How do you use flow-runtime in order to validate API payloads? This doesn't raise any error

```ts
type Person = {
  name: string
}

function untrustedEndpoint(id: string): Promise<{ data: Person }> {
  return Promise.resolve(null) // <= wrong
}

untrustedEndpoint('id')
```

**Comment by niieani** [comment]
@gcanti good catch, it's probably something `flow-runtime` should handle in the future. To tell the truth we still haven't had the time to migrate from [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck) to `flow-runtime`, but we also don't expect it to work perfectly, since we only treat it as a debug/coding-helper tool -- to catch errors faster, not as the ultimate source of truth.

The place where the above problem would be caught would be once it is passed to another function, e.g.

```ts
type Person = {
  name: string
}

type Endpoint = { data: Person }

function untrustedEndpoint(id: string): Promise<Endpoint> {
  return Promise.resolve(null) // <= wrong
}

function processPersonNameFromEndpoint(response : Endpoint) {
  return response.data.name
}

untrustedEndpoint(1).then(processPersonNameFromEndpoint)
```
