### ISSUE TITLE
Document Context type

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/io-ts#40]
Hi there, thanks for the fantastic library.

I observe that, when validation fails, the last item in the `Context` array will be the key that failed. Is this correct?

I wonder if the data structure could be more obvious here?

Alternatively, could we add some docs to note this behaviour?

Thanks!

**Comment by gcanti** [comment]
> Alternatively, could we add some docs to note this behaviour?

Yes, please.

> the last item in the Context array will be the key that failed

Correct (and the array allows to retrieve the whole path)

```ts
const Person = t.interface({
  name: t.string
})

t.validate({ name: 1 }, Person).fold(
  errors => console.log(JSON.stringify(errors, null, 2)),
  () => {}
)
```

Output

```ts
[
  {
    "value": 1, // the actual value
    "context": [
      {
        "key": "", // the first key is always empty
        "type": { // the expected type (Person) for the input
          "name": "{ name: string }",
          "props": {
            "name": {
              "name": "string"
            }
          }
        }
      },
      {
        "key": "name", // the actual key (in case we are validating compound types)
        "type": { // the expected type (t.string) for the key `name`
          "name": "string"
        }
      }
    ]
  }
]
```

**Comment by gcanti** [comment]
@OliverJAsh closing this, feel free to send a PR though, will be much appreciated
