### ISSUE TITLE
Can `t.partial` imply `{}`, not all JS objects

### ISSUE THREAD

**Issue by jloleysens** [gcanti/io-ts#407]
### Current Behavior

To create a type that _disallows_ arrays but permissively _allows_ objects (using `t.partial`) I need to:

```ts
// There may be another way...
t.intersection([
    t.partial({
      my: t.string,
      permissive: t.string,
      type: t.string,
    }),
    t.brand(
      t.UnknownRecord,
      (v: any): v is t.Branded<any, NotArray> => !Array.isArray(v),
      'NotArray'
    ),
  ])
```

Without using `t.brand` and `t.intersection`, `t.partial` will allow arrays to pass "decode" step at runtime :c .

### Desired Behavior

I would like a way to be able to _negate_ certain runtime types (not static types) _or_ `t.partial` should imply objects `{}`, not arrays `[]`, even though:

```
 😅
typeof []
=> "object"
```

### Suggested Solution

Can `t.partial` by default not allow non-object types? If I would like to use an array type I can reach for `t.array`.

Or, less good:
```ts
// this seems not great, but less verbose than we currently have?
t.intersection([
    t.partial({
      my: t.string,
      permissive: t.string,
      type: t.string,
    }),
   t.not.array
  ])
```

### Who does this impact? Who is this for?

Everyone!

### Describe alternatives you've considered

See above

### Additional context

None

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |       2.0.1     |
| fp-ts      |       2.3.1     |
| TypeScript |      3.7.2      |

**Comment by gcanti** [comment]
@jloleysens this is a bug, `partial` shouldn't allow arrays:

```ts
type X = Partial<{ my: string; permissive: string; type: string }>

const x: X = [1, 2, 3] // Error: Type 'number[]' has no properties in common with type 'Partial<{ my: string; permissive: string; type: string; }>'
```

so

```ts
const T = t.partial({ my: t.string, permissive: t.string, type: t.string })

T.decode([1, 2, 3]) // should fail
```

**Comment by jloleysens** [comment]
@gcanti Thanks for the explanation, and the great lib(s)! I'd be keen to contribute in future :+1:
