### ISSUE TITLE
Question: One source of truth for types and custom validations.

### ISSUE THREAD

**Issue by Lzok** [gcanti/io-ts#411]
Hello, how are you?
I want to ask for guidance on what I want to achieve if it's possible. Until now I use Joi to validate the requests my server receives.
This week I set up a new TS project from scratch and use io-ts to declare my interfaces. I want to use that interfaces as a single source of truth but also I want to kind of "extends" those declarations to validate the requests like I do with Joi. For example some number.min(10).max(20).

Pseudocode:
```javascript
// types.ts
export const IUserInput = t.interface(
  username: t.string(),
  password: t.string(),
);

// Middleware to validate the input request
const UserInputValidate = {
  username: IUserInput.username.min(3),
  password: IUserInput.password.min(8).max(128),
}
```
Regarding the simple pseudocode example, it would apply for validations of arrays or even custom validations, like an array of unique values.
My goal is to have that one source of truth and avoid "rewriting as much code as possible" for those exact validations. I have been surfing the io-ts and related libraries but I didn't find some clear way to achieve something like I want.

Let me know if you have questions on my doubt. If you can guide me to the right path to use this awesome library to perform exact/custom validations would be nice!

Best regards.

**Comment by steida** [comment]
I wrote an article about io-ts used as generic validation https://dev.to/steida/how-to-forms-with-react-and-typescript-4icb

I made an example lib: https://github.com/typescript-fun/typescript-fun/tree/master/packages/typescript-fun/src

You will probably have to learn what branded types are: https://www.youtube.com/watch?v=UwCLmHQOWoY

As far as I know, generic branded types like min(3) are not possible. Note I am using branded types names for Validation Errors. Check examples mentioned in the article.

Hope this helps.

**Comment by Lzok** [comment]
@steida Thank you! So nice resources. I will check them tonight.

>As far as I know, generic branded types like min(3) are not possible.

Yeah I don't know that yet but it isn't necessary to be that way (.min().max() etc). If I can reach a way to customize and even compose those validators, my goal will be accomplished for sure.
Maybe I cannot compose but definitely I can do sort of `minMax` brand type. 

Every other resource is welcome.

**Comment by christianbradley** [comment]
```ts
import * as E from 'fp-ts/lib/Either'
import { pipe } from 'fp-ts/lib/pipeable'
import * as t from 'io-ts'
import * as PathReporter from 'io-ts/lib/PathReporter'

export type HasMinMax = t.TypeOf<typeof hasMinMax>

const hasMinMax = t.union([t.string, t.number], 'HasMinMax')

export type Min<n extends number> = t.Branded<
  HasMinMax,
  { readonly Min: unique symbol; readonly gte: n }
>

export type Max<n extends number> = t.Branded<
  string,
  { readonly Max: unique symbol; readonly lte: n }
>

function isMin<n extends number>(n: n) {
  return (s: HasMinMax): s is Min<n> =>
    typeof s === 'string' ? s.length >= n : s >= n
}

function min<n extends number>(n: n) {
  return t.brand(hasMinMax, isMin(n), 'Min')
}

function isMax<n extends number>(n: n) {
  return (s: string | number): s is Max<n> =>
    typeof s === 'string' ? s.length <= n : s <= n
}

function max<n extends number>(n: n) {
  return t.brand(hasMinMax, isMax(n), 'Max')
}

type CreateUserInput = t.TypeOf<typeof createUserInputCodec>

// by adding `t.string` to the intersection, it reduces the type down to string & Min<n> / string & Min<n> & Max<n> 
const createUserInputCodec = t.strict({
  username: t.intersection([min(6), t.string]),
  password: t.intersection([min(8), max(128), t.string])
})

function createUser(input: CreateUserInput) {
  console.log(input)
}

// The following will cause a type error:
// createUser({ username: 'foo', password: 'bar' })

pipe(
  createUserInputCodec.decode({
    username: 'abcdef',
    password: '12345678'
  }),
  E.mapLeft(PathReporter.failure),
  E.fold(errors => console.error(errors), createUser)
)

```

**Comment by christianbradley** [comment]
If you want generic `min`/`max` "codecs", start by defining what can have min or max.
You can add properties to the brand like above for the `min` or `max` values, further reducing the brand's specificity. 

When designing your interfaces, you can use `intersection` to combine all the codecs.

**Comment by Lzok** [comment]
@christianbradley Nice example, thank you!
With it basically I can construct the same validations as the Joi library if I want to.

Have a good day.
