### ISSUE TITLE
Changes in v2.0.5 to how UnknownRecord is validated break previously valid decodes of window object

### ISSUE THREAD

**Issue by weliver** [gcanti/io-ts#413]
### Current Behavior

Changes in io-ts v2.0.5 to how UnknownRecord is validated break for previously valid window object types.

Updates now check unknown records via: `Object.prototype.toString.call(u) === '[object Object]'` which now fails, as `Object.prototype.toString.call(window)` returns `[object Window]`

Changes I'm looking at are on line 419 of `src/index.ts` in commit: https://github.com/gcanti/io-ts/commit/231b9f58218fc5e3f64ce28a183c81afff1fb642#diff-f41e9d04a45c83f3b6f6e630f10117feR419

### Expected behavior

I'm highlighting the impact of this change in 2.0.5 so that I can gain clarity on if this was an intended change in behavior by the author, and if so the purpose behind it.

If the consequence of this change was unintended, I hope this provides a concrete reason for reverting.

### Reproducible example

In v2.0.4 and previous, the following code would return a decode of type right when the window object has the property GlobalProps:

```typescript
import { globalProps } from "./globalProps"; // an io-ts type

export const  expectedGlobal = t.typeof({
  GlobalProps: globalProps
});

export type ExpectedGlobal = t.TypeOf<typeof expectedGlobal>;
export const windowWithExpectedGlobal = expectedGlobal.decode(<unknown>window as ExpectedGlobal);                      
```

Since v2.0.5, I've needed to update this code to look something like this:

To make this decode return a right, we now must change this code to look like this:

```typescript
export const windowWithExpectedGlobal = expectedGlobal.decode(Object.assign({}, <unknown>window as ExpectedGlobal));
```

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

Version 2.0.5 of io-ts cause this issue for me. It worked in v2.0.5 and below.

Software | Version(s)
-- | --
io-ts | 2.0.5
fp-ts | 2.0.5
TypeScript | 3.7.3

**Comment by gcanti** [comment]
@weliver thanks for the report 

> so that I can gain clarity on if this was an intended change in behavior by the author, and if so the purpose behind it

This was an intended change in order to fix the following bugs

```ts
import * as t from 'io-ts' // <= io-ts@2.0.4

// all the following values are not valid for the type checker
// but UnknownRecord doesn't fail

console.log(t.UnknownRecord.decode([1, 2, 3])) // Right
// t.UnknownRecord.encode([1, 2, 3]) // type-check error

console.log(t.UnknownRecord.decode(new Date())) // Right
// t.UnknownRecord.encode(new Date()) // type-check error

console.log(t.UnknownRecord.decode(new Number())) // Right
// t.UnknownRecord.encode(new Number()) // type-check error

console.log(t.UnknownRecord.decode(new String())) // Right
// t.UnknownRecord.encode(new String()) // type-check error

console.log(t.UnknownRecord.decode(new Boolean())) // Right
// t.UnknownRecord.encode(new Boolean()) // type-check error
```

For what concerns `window`, looks like in `typeScript@3.5` this code doesn't type-check

```ts
const x: Record<string, unknown> = window
```

with the following error

```
Type 'Window' is not assignable to type 'Record<string, unknown>'.
  Index signature is missing in type 'Window'.ts(2322)
```

however in `typeScript@3.6` and `typeScript@3.7` **is fine**.

I guess we can whitelist `window`.

**Comment by weliver** [comment]
@gcanti Awesome, makes sense to me. Thanks so much for the super fast response and patch.

**Comment by gcanti** [comment]
@weliver patch released

**Comment by OliverJAsh** [comment]
> For what concerns `window`, looks like in `typeScript@3.5` this code doesn't type-check
> 
> ```ts
> const x: Record<string, unknown> = window
> ```
> 
> with the following error
> 
> ```
> Type 'Window' is not assignable to type 'Record<string, unknown>'.
>   Index signature is missing in type 'Window'.ts(2322)
> ```
> 
> however in `typeScript@3.6` and `typeScript@3.7` **is fine**.

This seems to error in 3.9.2, so maybe we should remove it from `UnknownRecord` after all?

(For context, I just ran into this when I was trying to write a runtime type for `{ statusCode: number }`, but the decode would fail if I passed an `Error` object which happened to contain this property.)
