### ISSUE TITLE
`t.type` allows additional properties

### ISSUE THREAD

**Issue by jloleysens** [gcanti/io-ts#416]
### Current Behavior

Given the following:

```ts
i = t.type({a: t.number})
```

I would expect this to return a `Left`:

```ts
i.decode({b: 2, a: 1})
{ _tag: 'Right', right: { b: 2, a: 1 } }
```

### Expected behavior

In Typescript the following is invalid:

```ts
interface A {
  a: number;
}

const a: A = { a: 1, b: 2 }
```

I would expect the same behaviour here.

### Your environment

Did not test on other versions.

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |     2.0.5       |
| fp-ts      |      2.3.1      |
| TypeScript |    3.7.2       |

**Comment by DenisFrezzato** [comment]
See https://github.com/gcanti/io-ts/issues/322.

**Comment by jloleysens** [comment]
Happy to close this for now (adds no new info) and continue the conversation there.
