### ISSUE TITLE
Is there an equivalent for typescript index signatures

### ISSUE THREAD

**Issue by dibell** [gcanti/io-ts#424]
e.g. How would I best model the following ts in io-ts?

`type Example = {
  [key: string]: number
}`

**Comment by DenisFrezzato** [comment]
There is `t.record`, in your spefic case it would be `t.record(t.string, t.number)`.

**Comment by dibell** [comment]
Thanks. That seems useful if a property contains records e.g. `{ values: t.record(t.string, t.number) }` but I still don't see how to use that for index signatures in the example above with the square bracket notation and notional 'key'.

**Comment by gcanti** [comment]
Ad suggested by @DenisFrezzato you can use `record`

```ts
import * as t from 'io-ts'

//                   keys --v         v-- values
const Example = t.record(t.string, t.number)

type Example = t.TypeOf<typeof Example>
/*
Same as:

type Example = {
    [x: string]: number;
}
*/
```
