### ISSUE TITLE
Question: Rercord type with a special case

### ISSUE THREAD

**Issue by alcuadrado** [gcanti/io-ts#426]
Hi,

I'm trying to validate one of my project's config using io-ts, and I'm struggling to get a part of it to work properly.

My config is an object with different fields. One of them, the one I'm struggling with, has this non-expressable-in-ts type:

```ts
interface ComplicatedConfig {
    special: SpecialType;
    [everyOtherField: string]: NormalType;
}
```

Now, I have something like:

```ts
const eitherType = t.union([specialType, normalType]);

const complicatedConfig = t.record(t.string, eitherType);
```

The problem is that users can pass a `SpecialType` to other fields, and the other way round. Also, error messages get really complicated.

Is there a way to express this in io-ts? Any hint?

Thanks!

**Comment by gcanti** [comment]
> Is there a way to express this in io-ts? 

@alcuadrado no, `SpecialType` must be a subtype of `NormalType`, as is the case in TypeScript
