### ISSUE TITLE
codec.type is undefined for RecursiveType

### ISSUE THREAD

**Issue by SAnDAnGE** [gcanti/io-ts#433]
### Current Behavior

![image](https://user-images.githubusercontent.com/2596509/77909916-d1dffe00-7296-11ea-86a3-e84b6e7cc1d2.png)

![image](https://user-images.githubusercontent.com/2596509/77910163-5468bd80-7297-11ea-8f94-42007fe5152c.png)

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

It worked in io-ts 2.0.1

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |     2.1.2       |
| fp-ts      |            |
| TypeScript |            |

**Comment by SAnDAnGE** [comment]
After a better testing, this regression occurred in version 2.0.4

**Comment by DenisFrezzato** [comment]
Do you have further information on how to reproduce the issue? A code example  might be helpful.

**Comment by SAnDAnGE** [comment]
Pretty hard to make one, I am using this in an angular app, and the error occurs only when compiling for production, not when running the application in development mode.

**Comment by steida** [comment]
@SAnDAnGE If it happens only when compiling for production, your code is probably wrong. Tree shanking probably removed something.

**Comment by SAnDAnGE** [comment]
The regression was introduced in version 2.0.4 to fix #404.
This issue seems very similar to what was signaled in https://github.com/rollup/rollup/issues/1130
Currently I will be stuck on version 2.0.3, which seems to work.
I am hoping you will revert the change done in 2.0.4 in one of the next versions. Thank you very much.

**Comment by SAnDAnGE** [comment]
Any workaround for the:
```
Object.defineProperty(RecursiveType.prototype, 'type', {
  get: function () {
    return this.runDefinition()
  },
  enumerable: true,
  configurable: true
})
```
?

**Comment by SAnDAnGE** [comment]
Fixed in newer versions of typescript/angular.
