### ISSUE TITLE
New version 2.1.3 breaks t.undefined behavior

### ISSUE THREAD

**Issue by Christofrage** [gcanti/io-ts#439]
### Current Behavior
 Since version 2.1.3
```typescript
const Interface = t.interface({
  optional: t.undefined
});

Interface.is({}); // False

```

### Expected behavior
I expect it to be true because in my code I use
```typescript
const Interface = t.interface({
  optional: t.union([t.undefined, t.string])
});
```
To reproduce

```typescript
interface Interface {
  optional?: string
}
```

I have not a lot of legacy code so if I am using it the wrong way I can fix it.

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

Only last version (2.1.3) is affected 2.1.2 is fine

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts        | 2.1.3        |
| fp-ts        | 2.5.3        |
| TypeScript | 3.8.3      |

**Comment by gcanti** [comment]
In v2.1.2 there was a regression, see https://github.com/gcanti/io-ts/pull/436

The type

```ts
interface Interface {
  optional?: string
}
```

can be obtained from

```ts
const Interface = t.partial({
  optional: t.string
})
```

**Comment by Christofrage** [comment]
Ok so to get

```
interface Interface {
  optional?: string
  required: string
}
```
I need to make an intersection of multiple interfaces ?
on 2.1.2 I created a function

```
export function orUndefined(type: iots.Type<any>): iots.UnionC<any> {
    return iots.union([iots.undefined, type]);
}
```
and declared the interface as 

```
const Interface = t.interface ({
  optional: orUndefined(t.string)
  required: t.string
})
```

But maybe I am asking for a new feature

**Comment by gcanti** [comment]
> I need to make an intersection of multiple interfaces ?

Yes, as documented [here](https://github.com/gcanti/io-ts#mixing-required-and-optional-props)
