### ISSUE TITLE
The inferred type of a inner-type is unknown 

### ISSUE THREAD

**Issue by nthypes** [gcanti/io-ts#446]
### Current Behavior

The inferred type of a sub-type is _**unknown**_ 

`type PersonB = {
    name: string;
    age: number;
    personA: unknown;
}`

### Expected behavior

Should infer the inner-type correctly as **_PersonA_**

### Reproducible example

```
import * as S from 'io-ts/lib/Schema'

export const PersonA = S.make((S) =>
  S.type({
    name: S.string,
    age: S.number
  })
)

export const PersonB = S.make((S) =>
  S.type({
    name: S.string,
    age: S.number,
    personA: S.type(PersonA)
  })
)

type PersonB = S.TypeOf<typeof PersonB>;
```

### Suggested solution(s)

IDK

### Additional context

None

### Your environment

io-ts @ 2.2.0

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |  2.2.0          |
| fp-ts      |     2.5.3       |
| TypeScript |    3.8.3        |

**Comment by gcanti** [comment]
@nthypes `personA: S.type(PersonA)` is supposed to be `personA: PersonA(S)` I guess

**Comment by nthypes** [comment]
Perfect, it worked.

```
type PersonB = {
    name: string;
    age: number;
    personA: {
        name: ...;
        age: ...;
    };
}
```

It's possible to show the type alias instead of the full type when inferring? i.e:

```
type PersonB = {
    name: string;
    age: number;
    personA: PersonA;
}
```

**Comment by gcanti** [comment]
> It's possible to show the type alias instead

No, because there's no type alias being defined.

You could define an `interface` explicity (kind of verbose though)

```ts
import * as S from 'io-ts/lib/Schema'

export const _PersonA = S.make((S) =>
  S.type({
    name: S.string,
    age: S.number
  })
)

interface PersonA extends S.TypeOf<typeof _PersonA> {}
const PersonA: S.Schema<PersonA> = _PersonA

export const PersonB = S.make((S) =>
  S.type({
    name: S.string,
    age: S.number,
    personA: PersonA(S)
  })
)

type PersonB = S.TypeOf<typeof PersonB>
/*
type PersonB = {
    name: string;
    age: number;
    personA: PersonA;
}
*/
```
