### ISSUE TITLE
A partly partial with io-ts

### ISSUE THREAD

**Issue by james2mid** [gcanti/io-ts#450]
I just posted a new question [on StackOverflow](https://stackoverflow.com/questions/61311182/a-partly-partial-with-io-ts) regarding making a partial from an existing schema.

Any help would be appreciated.

---

I'm having some issues with using `io-ts`. I've found that its really lacking documentation, most of the progress I've made is through GitHub issues. And no I don't understand the HKTs so no help there.

Basically I'm creating a type elsewhere, `type` which has a certain set of keys:
```ts
import * as S from 'io-ts/lib/Schema'

const someType = S.make(S => S.type({
  id: S.string,
  foo: S.string,
  bar: S.boolean
}))

type T = S.TypeOf<typeof someType>
```

And I need to transform this to a *partial* where some keys are still required. Say just the `id` key is still required, defining the type in TS would be like:
```ts
type PartlyPartial <T> = Partial<T> & { id: string }
```
Simple!

Now, I want to be able to do this at runtime through `io-ts` so that I can create a validator function with the `Guard` module. This is what I've got so far:
```ts
import * as G from 'io-ts/lib/Guard'

const propsBase = S.make(S => S.type({
  id: S.string
}))

const partial = S.make(S => S.intersection(
  someType(S) // needs to be partial,
  propsBase(S)
))

// So that this returns `true`
partial(G.guard).is({
  id: 'some id',
  bar: true
})
```

But the `someType(S)` defines the type as having all keys required, but none of them should be required.

**Comment by gcanti** [comment]
> making a partial from an existing schema

That's not possible

**Comment by james2mid** [comment]
I appreciate you getting back to me.

Is there no workaround that I could create temporarily? All I need to do it validate with these conditions.

Could the `properties` be attached as a property to the Schema fn produced by `make` for future manipulation. I understand it seems you've tried to get away from the whole `props` idea after dealing with io-ts' initial `Type` but in my case it seems necessary.

**Comment by RemiLelaidier** [comment]
Found that
https://stackoverflow.com/questions/61311182/a-partly-partial-with-io-ts

**Comment by james2mid** [comment]
> Found that
> https://stackoverflow.com/questions/61311182/a-partly-partial-with-io-ts

Yes, that's my post which I linked at the beginning, although I didn't reply saying that I found a workaround.

If anybody has the same issue, then its possible to create a wrapper around `make` which provides the features I'm talking about.
