### ISSUE TITLE
type decoder doesn't strip additional fields when decoding

### ISSUE THREAD

**Issue by eivindml** [gcanti/io-ts#454]
### Current Behavior

I'm trying out `io-ts` for the first time. In the [documentation](https://github.com/gcanti/io-ts/blob/master/Decoder.md#the-type-combinator) it says that:

> The `type` combinator will strip additional fields while decoding

But when I try this, it doesn't remove the extra `remeberMe` field.

<img width="821" alt="Skjermbilde 2020-04-23 kl  21 56 18" src="https://user-images.githubusercontent.com/202450/80143560-4adc2800-85ad-11ea-8992-7d67943cbd0a.png">

<img width="473" alt="Skjermbilde 2020-04-23 kl  21 56 07" src="https://user-images.githubusercontent.com/202450/80143571-4f084580-85ad-11ea-8b08-0ad581e51b4b.png">

### Expected behavior

To strip out the `remeberMe: true` field before printing the result, as stated in the documentation sample code.

### Reproducible example

```javascript
  const Person = t.type({
    name: t.string,
    age: t.number
  })

  // type Person = t.TypeOf<typeof Person>

  console.log(Person.decode({ name: 'name', age: 42, remeberMe: true }))
  // What I expect: => { _tag: 'Right', right: { name: 'name', age: 42 } }
  // What I get: => { _tag: "Right", right: {name: "name", age: 42, remeberMe: true}}
```

### Suggested solution(s)

Either change the code if it's a bug, or update documentation. 

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      | 2.2.1  |
| fp-ts      | 2.5.3   |
| TypeScript |  3.8.3  |

**Comment by DenisFrezzato** [comment]
See https://github.com/gcanti/io-ts/issues/322.

**Comment by gcanti** [comment]
> In the documentation it says that

@eivindml the link points to the `Decoder` module documentation, I guess you are importing from the root instead

```ts
import * as t from 'io-ts' // <= this is missing in your repro

const Person = t.type({
  name: t.string,
  age: t.number
})

// type Person = t.TypeOf<typeof Person>

console.log(Person.decode({ name: 'name', age: 42, remeberMe: true }))
// What I expect: => { _tag: 'Right', right: { name: 'name', age: 42 } }
// What I get: => { _tag: "Right", right: {name: "name", age: 42, remeberMe: true}}
```

If you import from the `Decoder` module you get the expected result

```ts
import * as t from 'io-ts/lib/Decoder'

const Person = t.type({
  name: t.string,
  age: t.number
})

console.log(Person.decode({ name: 'name', age: 42, remeberMe: true }))
// => { _tag: 'Right', right: { name: 'name', age: 42 } }
```

**Comment by eivindml** [comment]
Thanks for clarifying, that was my issue! :)

There probably is a reason, but to a newcomer this behaviour is a bit confusing.
