### ISSUE TITLE
Refinement function similar to is type guard

### ISSUE THREAD

**Issue by jleider** [gcanti/io-ts#456]
## 🚀 Feature request

I find myself falling into familiar patterns such as the following:

```typescript
pipe(
  optionOfStringOrNumber,
  filter(getRefinement(a => t.string.is(a) ? some(a) : none)),
  map((s: string) => ...)
)
```

It would be nice to have a helper function that returned a `refinement` function similar to the built in type guard `is`. 

```typescript
pipe(
  optionOfStringOrNumber,
  filter(t.string.refinement),
  map((s: string) => ...)
)
```

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |     2.1.2       |
| fp-ts      |     2.5.3       |
| TypeScript |       3.7     |

**Comment by gcanti** [comment]
@jleider not sure I'm following, the built in type guard is a refinement (by definition)

```ts
import { filter, map, Option, some } from 'fp-ts/lib/Option'
import { pipe } from 'fp-ts/lib/pipeable'
import * as t from 'io-ts'

const optionOfStringOrNumber: Option<string | number> = some('foo')

console.log(
  pipe(
    optionOfStringOrNumber,
    filter(t.string.is),
    map((s) => s + 'bar') // <= here `s` has type `string`
  )
) // => some('foobar')
```

**Comment by jleider** [comment]
@gcanti Ah, you are correct, I believe what happened when I first started trying to use the type guard in this fashion is that I needed the functionality of `filterNot` implemented as `filter(a => !t.string.is(a))` which TypeScript does not infer correctly.
