### ISSUE TITLE
JSON parsing

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/io-ts#46]
Hey!

Would it make sense for this library to include a function equivalent to `t.validate`, but accepting a string instead of a parsed object?

Perhaps:
``` js
<T>(type: t.Type<T>, value: string) => Either<ValidationErrors | ParsingError, T>
```

Currently I am wrapping `t.validate` to do this myself, but it could be useful to other people. Most often, when performing IO validation, you start with a string?

Thanks,
Olly

**Comment by gcanti** [comment]
`validate` accepts `value`s of type `any`

```ts
export type Validate<T> = (value: any, context: Context) => Validation<T>
```

so with `io-ts` you can build types for any input: strings, numbers, objects, ...

Here's a gist

```ts
import * as t from 'io-ts'
import { tryCatch } from 'fp-ts/lib/Either'

export type JSONObject = { [key: string]: JSON }
export interface JSONArray extends Array<JSON> {}
export type JSON = null | string | number | boolean | JSONArray | JSONObject

// string -> JSON
const JSONFromString = t.prism(t.string, s => tryCatch<JSON>(() => JSON.parse(s)).toOption(), 'JSONFromString')

// JSON -> Person
const Person = t.interface({
  name: t.string
}, 'Person')

function compose<A, B>(fa: t.Type<A>, fb: t.Type<B>, name: string): t.Type<B> {
  return new t.Type<B>(
    name,
    (v, c) => fa.validate(v, c).chain(a => fb.validate(a, c))
  )
}

// string -> Person
const PersonFromString = compose(JSONFromString, Person, 'PersonFromString')


console.log(t.validate(1, PersonFromString)) // Left([{"value":1,"context":[{"key":"","type":{"name":"PersonFromString"}}]}])
console.log(t.validate('{}', PersonFromString)) // Left([{"context":[{"key":"","type":{"name":"PersonFromString"}},{"key":"name","type":{"name":"string"}}]}])
console.log(t.validate('{"name":"Giulio"}', PersonFromString)) // Right({"name":"Giulio"})
```

**Comment by OliverJAsh** [comment]
For context, I'm working on [twitter-api-ts](https://github.com/OliverJAsh/twitter-api-ts), and I want parsing to be safe, i.e. return an `Either` `Left` instead of throwing an exception.

I'm already using io-ts to validate the API responses match what we expect.

When io-ts validation fails, we return a `ValidationErrorsErrorResponse`. When parsing fails, we could return the same thing, or we could return a separate `ParsingErrorErrorResponse`. I'm not sure what makes more sense here.

Related issue: https://github.com/OliverJAsh/twitter-api-ts/issues/2

**Comment by gcanti** [comment]
Well, there are many options, you can customize the errors messages managing the context

```ts
function compose<A, B>(fa: t.Type<A>, fb: t.Type<B>, name: string): t.Type<B> {
  return new t.Type<B>(
    name,
    (v, c) => fa.validate(v, c.concat({ key: 'parse', type: fa })).chain(a => fb.validate(a, c))
  )
}

import { PathReporter } from 'io-ts/lib/reporters/default'

console.log(PathReporter.report(t.validate('bad', PersonFromString))) // [ 'Invalid value "bad" supplied to : PersonFromString/parse: JSONFromString' ]
console.log(PathReporter.report(t.validate('{}', PersonFromString))) // [ 'Invalid value undefined supplied to : PersonFromString/name: string' ]
```

or define your own little validation framework

```ts
type DecodeResult<A> = Either<string, A>

function json(value: any): DecodeResult<JSON> {
  return t.validate(value, JSONFromString).mapLeft(() => 'Parsing error')
}

function type<A>(type: t.Type<A>): (value: JSON) => DecodeResult<A> {
  return value => {
    const validation = t.validate(value, type)
    return validation.mapLeft(() => PathReporter.report(validation).join('\n'))
  }
}

type Person = t.TypeOf<typeof Person>

function personFromString(value: any): DecodeResult<Person> {
  return json(value).chain(type(Person))
}

console.log(personFromString('bad')) // Left("Parsing error")
console.log(personFromString('{}')) // Left("Invalid value undefined supplied to : Person/name: string")
```

`io-ts` is kind of a low-level library you can build upon

**Comment by OliverJAsh** [comment]
Looking at `JSONFromString`, we lose the error object from `JSON.parse` because we're converting from `Either` to `Option`:

``` ts
const JSONFromString = t.prism(t.string, s => tryCatch<JSON>(() => JSON.parse(s)).toOption(), 'JSONFromString')
```

It would be good if io-ts allowed you to provide additional information (context?) for an error.

For example, `JSON.parse` has errors such as:

- Unexpected token u in JSON at position 0
- Unexpected end of input

**Comment by OliverJAsh** [comment]
For anyone who happens to land here: I made a little helper module that wraps `JSON.parse` and io-ts validation: https://github.com/OliverJAsh/decode-ts

You have the choice of using the raw error objects returned or using the provided reporter.

**Comment by gobengo** [comment]
@gcanti Is this still possible without `iots.prism`, which has been removed?

**Comment by silasdavis** [comment]
Since I stumbled upon it myself and haven't seen it documented recent versions of `io-ts` have this functionality with something like:

```typescript
const PersonFromString = JSONFromString.pipe(person)
```

**Comment by OliverJAsh** [comment]
Here's a new version of `JSONFromString` that uses the new `Either.json` in fp-ts.

I'm not sure how to implement the `is` function though 🤔 

```ts
export const JSONFromString = new t.Type<E.Json, string, string>(
  'JSONFromString',
  // TODO:
  (x): x is E.Json => true,
  (s, c) =>
    pipe(
      s,
      // TODO:
      E.json((_e) => 'whatever'),
      E.fold(() => t.failure(s, c), t.success),
    ),
  JSON.stringify,
);
```

**Comment by mlegenhausen** [comment]
@OliverJAsh I think you need to port the `Json` Type from TypeScript to `io-ts`. Something like (untested)

```ts
export const JsonArray = t.recursion('JsonArray', () => t.readonlyArray(Json))

export const JsonRecord = t.recursion('JsonRecord', () => t.record(t.string, Json))

export const Json = t.union([t.boolean, t.number, t.string, t.null, JsonArray, JsonRecord], 'Json')
```

Then you can use `Json.is`
