### ISSUE TITLE
Attempting to use DateFromString in examples results in type error

### ISSUE THREAD

**Issue by CMCDragonkai** [gcanti/io-ts#470]
### Current Behavior

In https://github.com/gcanti/io-ts/blob/master/Type.md#custom-types, it demonstrates a `DateFromString` type.

When attempting to extract the static type from `DateFromString` and using it on an encoded instance, typescript outputs a type error.

### Expected behavior

It should not have a type error.

### Reproducible example

```ts
import * as t from 'io-ts';
import { either } from 'fp-ts/lib/Either'

const DateFromString = new t.Type<Date, string, unknown>(
  'DateFromString',
  (u): u is Date => u instanceof Date,
  (u, c) =>
    either.chain(t.string.validate(u, c), (s) => {
      const d = new Date(s)
      return isNaN(d.getTime()) ? t.failure(u, c) : t.success(d)
    }),
  (a) => a.toISOString()
);

const UserGetResBody = t.type({
  id: t.number,
  group_id: t.number,
  username: t.string,
  created_on: DateFromString
});

type UserGetResBodyT = t.TypeOf<typeof UserGetResBody>;

const body: UserGetResBodyT = UserGetResBody.encode({
  id: 1,
  group_id: 2,
  username: "abc",
  created_on: new Date()
});

// this results in a type error
// complaining that created_on should be a string
// but if were to set created_on: '1973-11-29T23:00:00.000Z'
// this would result in a runtime error
```

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      | 2.2.2           |
| fp-ts      | 2.6.1           |
| TypeScript | 3.8.3           |

**Comment by gcanti** [comment]
> using it on an **encoded** instance

You should use `OutputOf`

```diff
-type UserGetResBodyT = t.TypeOf<typeof UserGetResBody>
+type UserGetResBodyT = t.OutputOf<typeof UserGetResBody>
```
