### ISSUE TITLE
Brand Type:  "is not assignable to type 'Branded<number, PositiveBrand>'

### ISSUE THREAD

**Issue by coulonxyz** [gcanti/io-ts#476]
## 🐛 Bug report

I'm trying to use Brand to define custome types (string based on regex for instance).
I've used the example in the document, and still I have a TS2322 error.

I'm pretty sure I used this feature successfully in the past, but who knows, I'm getting old.

### Current Behavior
![image](https://user-images.githubusercontent.com/22661426/83177124-d30a9b80-a11e-11ea-823a-6dfddcf8dd0e.png)

### Expected behavior
I would expect to get TS232 error on the negativeValue but not on the positive

### Reproducible example

Yes.

### Your environment

| Software    | Version(s) |
| ----------      | ----------     |
| io-ts           |    ^2.2.4     |
| fp-ts           |     ^2.6.1    |
| TypeScript |      3.7.3     |

**Comment by tal-joffe** [comment]
Having the same issue. have tried many different variations of similar code and couldn't get it to work. I also used examples from [typescript-fun](https://github.com/typescript-fun/typescript-fun) and had the same error.

**Comment by gcanti** [comment]
A "branded type" of a type `A` is just an intersection `A & Brand`

```ts
type Positive = number & t.Brand<PositiveBrand>
```

So you can't assign any `number` to it (that's the point of defining a branded type) so you are forced to parse the input through `decode`.

```ts
const unsafeInput = 12
const result = Positive.decode(unsafeInput)
if (isRight(result)) {
  // positive: Positive
  const positive = result.right
}
```

**Comment by tal-joffe** [comment]
@gcanti Let's say I want to create a function that has a Positive parameter:

`const squareRoot = (number: Positive) => Math.sqrt(positive)`

How would a test for this function look like?
```
const result = Positive.decode(9)
let actual = 0
if (isRight(result)) {
  actual = squareRoot(result.right)
}
expect(actual).toEqual(3)
```

The premise of being able to simply call the function like this:

`squareRoot(9)`

was very appealing if I need all that boilerplate around the branded type I'm not sure what
is the value over simply using any validation framework that returns an Either.
