### ISSUE TITLE
How to represent rest type in io-ts?

### ISSUE THREAD

**Issue by vedantroy** [gcanti/io-ts#477]
How do I represent a rest type in io-ts? For example `[string, ...number[]`?

**Comment by enricopolanski** [comment]
Very ugly implementation with Decoder api:
`ts
const GenerateRestTupleDecoder = <FirsType, SecondType>(
  headDecoder: D.Decoder<FirsType>,
  tailDecoder: D.Decoder<SecondType>
) => ({
  decode: (u: unknown) =>
    pipe(
      u,
      D.refinement(
        D.array(D.union(headDecoder, tailDecoder)),
        D.isNotEmpty,
        "error"
      ).decode,
      E.chain((as) => {
        const [a, ...bs] = as
        return pipe(
          headDecoder.decode(a),
          E.chain((first) =>
            pipe(
              D.array(tailDecoder).decode(bs),
              E.map((rest) => [first, ...rest] as [FirsType, ...SecondType[]])
            )
          )
        )
      })
    ),
})

const stringNumberTupleDecoder = GenerateRestTupleDecoder(D.string, D.number)

stringNumberTupleDecoder.decode(foo)
`

**Comment by vedantroy** [comment]
Thank you for the explanation! I'll see if I can improve upon this.
