### ISSUE TITLE
Type information lost from nested decoder types in 2.2

### ISSUE THREAD

**Issue by sambs** [gcanti/io-ts#479]
### Current Behavior

When outputting typescript declarations for nested type decoders (in v2.2), the type information is lost for sublevels, which end up with a type of any.

```
// src/index.ts
import * as t from 'io-ts/lib/Decoder'

export const query = t.type({
  a: t.number,
  b: t.type({
    c: t.number,
  }),
})

// build/index.d.ts
export declare const query: t.Decoder<{
    a: number;
    b: {
        c: any;
    };
}>;
```

### Reproducible example

https://github.com/sambs/io-ts-decoder-bug

Specifically see: https://github.com/sambs/io-ts-decoder-bug/blob/master/build/index.d.ts

### Additional context

Strangley, the correct types are displayed in VS Code, its only when outputting declarations that the type information seems to be lost.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      | 2.2.4    |
| fp-ts      | 2.6.5      |
| TypeScript | 3.9.5      |

**Comment by gcanti** [comment]
> Strangley, the correct types are displayed in VS Code, its only when outputting declarations that the type information seems to be lost.

This is pretty disappointing, @sambs thanks for the bug report

**Comment by gcanti** [comment]
@sambs patch released

**Comment by sambs** [comment]
Great, thanks @gcanti!
