### ISSUE TITLE
How to model objects regardless of their constructor?

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/io-ts#485]
### Current Behavior

I am trying to create a runtime type for `{ statusCode: number }`, however if I use `t.type`/`t.interface` it won't work if I try to use it to decode an object that has type `Error & { statusCode: number }`:

```ts
import * as t from 'io-ts';

const StatusCodeObject = t.type({ statusCode: t.number });

{
    const error = { statusCode: 200 };
    console.log(StatusCodeObject.is(error)); // => true
}

{
    const error = new Error('foo') as Error & { statusCode: number };
    error.statusCode = 200;
    console.log(StatusCodeObject.is(error)); // => false
}
```

Is there any way to write `StatusCodeObject` so that this will work? Essentially I want the runtime type to work with objects of any type, including things like `Error`, `Date`, or anything else that could have the property I'm looking for.

Reading https://github.com/gcanti/io-ts/issues/413, I understand that io-ts is designed so that `t.type` should not work with `Error`. In that case, perhaps we need another way to model this?

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |            |
| fp-ts      |            |
| TypeScript |            |

**Comment by VanTanev** [comment]
@OliverJAsh As a stopgap, you could write a `typeAny()` variation of `t.type()` that is something like:

```typescript
const toSimpleObj = (o: any): object => JSON.parse(JSON.stringify(o))

export const typeAny = <P extends t.Props>(
    props: P,
    name = `${getNameFromProps(props)}`,
): t.TypeC<P> => {
    const type = t.type(props)

    return new t.InterfaceType(
        name,
        (u): u is {[K in keyof P]: t.TypeOf<P[K]>} => type.is(toSimpleObj(u)),
        (u, c) => type.validate(toSimpleObj(u), c),
        a => type.encode(a),
        props,
    )
}

const getNameFromProps = (props: t.Props): string =>
    Object.keys(props)
        .map(k => `${k}: ${props[k].name}`)
        .join(', ')
```
