### ISSUE TITLE
Map is removed?

### ISSUE THREAD

**Issue by dexx086** [gcanti/io-ts#491]
Hello, I'm new to this library, I'm trying to figure out in advance whether I could use it or not.
Most features I've seen so far look veeery promising, there's one blocking problem I cannot move forward with.

And it is: couldn't find a way to handle Map type!

Found a previous issue (https://github.com/gcanti/io-ts/issues/108) regarding my problem, but a workaround solution was given to it, but the basic 'map' issue was not answered. However, I've seen a strange sentence: "Are you interested in a generic map (I'm afraid we can't bring it back..)...".
Does it mean there were "map" type previously and it was just removed?
But why?

But even if exact Map type is not supported anymore, how can I achieve a type checking which has map type, like this:

```typescript
const Window = t.type({
    title: t.string,
    color: t.string
});

const Windows = t.type({
    activeWindowId: t.number,
    windows: t.MAP(t.string, Window) // <-- t.MAP doesn't exists
})

type IWindow = t.TypeOf<typeof Window>;
type IWindows = t.TypeOf<typeof Windows>;

const W: IWindows = {
    activeWindowId: null,
    windows: new Map<string, IWindow>() // <-- how to initialize a simple ES6 Map to make typescript handle it correctly?
};
```

The example is just a simplified one, the main point is how to specify the "windows" property so with objects of this type I could use regular (but generic) Map instances?

Is there any way I can cover Map type with io-ts?
Thanks in advance.

**Comment by gcanti** [comment]
@dexx086 the `map` we were talking about in the linked issue was a function with a signature similar to

```ts
declare function map<A, B>(f: (a: A) => B, codec: Type<A>): Type<B>
```

so it was not related to your use case.

> Is there any way I can cover Map type with io-ts?

You need to define a suitable custom combinator from the ground up (`Map` is not supported in the core), so something along the lines of

```ts
import * as t from 'io-ts'

function map<DA, CA>(
  domain: t.Type<DA>,
  codomain: t.Type<CA>,
  name: string = `Map<${domain.name}, ${codomain.name}>`
): t.Type<Map<DA, CA>> {
  return new t.Type(
    name,
    (u): u is Map<DA, CA> => ...,
    (u, c) => ...,
    t.identity
  )
}
```

**Comment by dexx086** [comment]
@gcanti thanks for your quick response, and for the initial solution!

Didn't really think I could implement it for myself. But to be honest: I'm rather surprised that nobody else needed to handle Maps before? :) It's quite a basic structure, and all other important basic types (even object, tuple, array, etc.) is handled by io-ts from its core, don't know how others don't need maps as well.

But OK, if I can fill the gap and could implement it for myselft, that's a solution to me, because besides the missing map problem, io-ts seems very promising to me. I'll try to dive into the library and implement it.

Btw.: is there a particular reason why previous map implementation was removed from io-ts?

**Comment by gcanti** [comment]
> I'm rather surprised that nobody else needed to handle Maps before?

`io-ts` is a decoder / encoder library, when you decode from JSON (likely the most common use case) the built-in `record` combinator is enough

**Comment by dexx086** [comment]
@gcanti You're right, possibly this library is mostly used with APIs and custom user inputs, where `map` is quite rare I think.

However, I needed it to serialize/deserialize component states of my (react) client app, and type safety at deserialization was crucial. In this scenario, I use maps very widely, that's why I was missing it from this library.

But whoever needs map for io-ts, here's what I came up with, based on your initial help. Thanks again.
```typescript
// Generic map
const map = <K, V>(
    domain: t.Type<K>,
    codomain: t.Type<V>,
    name = `Map<${domain.name}, ${codomain.name}>`
): t.Type<Map<K, V>> => {
    return new t.Type(
        name,
        (u): u is Map<K, V> => {
            return u instanceof Map;
        },
        (u, c) => {
            const map = u as Map<unknown, unknown>;

            let validationResult;
            let validationError: string = null;
            Array.from(map).some(([key, value]) => {
                // Validate key
                if (!isRight((validationResult = domain.validate(key, c))))
                    validationError = `Invalid type for key: '${key}'. Error: ${PathReporter.report(validationResult)}`;
                // Validate value
                if (!isRight(validationResult = codomain.validate(value, c)))
                    validationError = `Invalid type for value at key: '${key}'. Error: ${PathReporter.report(validationResult)}`;

                // If validation failed, return true to stop processing further items
                return validationError !== null;
            });

            return validationError !== null ? t.failure(u, c, validationError) : t.success(u as Map<K, V>);
        },
        t.identity
    )
}
```
