### ISSUE TITLE
Optimize decoding for union/taggedUnions types

### ISSUE THREAD

**Issue by kpritam** [gcanti/io-ts#494]
Currently, decoding for **union/taggedUnion** types tries all the variations in case of invalid data.
Can it behave like following
1. Read **tag** and try decoding using corresponding decoder
2. Read **tag**, if invalid then fail fast without trying any variation (I think this is how it currently behaves in this case)

**Note:** This seems to be possible with taggedUnion when tag is provided but not sure why it is deprecated.

Ex.
```typescript
const Cat = t.type({
 tag: t.literal('Cat'),
 name: t.string
})

const Dog = t.type({
 tag: t.literal('Dog'),
 name: t.string
})

const Animal = t.taggedUnion('tag', [Cat, Dog])

// ===== Test ====
const input = {
tag: 'Dog',
name1: 'Tommy'
}

// following should just attempt to decode using Dog and fail with name key missing
Animal.decode(input)
```

**Comment by kpritam** [comment]
Was just looking at the implementation of decoder for unionType and it seems like this is already optimised.
**Could you please confirm if decoding is done based on the tag?**

Also how **tag** is determined in case of union where we don't provide tag explicitly?

**Comment by gcanti** [comment]
> Could you please confirm if decoding is done based on the tag?

I can confirm

> how tag is determined in case of union where we don't provide tag explicitly?

By reflection (see the `getIndex` / `getTags` functions in the source)
