### ISSUE TITLE
Opt-in to freeze behavior for `readonly` and `readonlyArray` 

### ISSUE THREAD

**Issue by krisdages** [gcanti/io-ts#497]
## 🚀 Feature request
Make the `Object.freeze` in non-production mode an opt-in behavior

### Current Behavior
Using `readonly` or `readonlyArray` codecs without process.env.NODE_ENV="production" always results in a frozen object.

I'm curious if the process.env check would flat out break if I used the lib in a non-Webpack project that didn't polyfill process.env?

### Desired Behavior
Make this development mode behavior opt-in.

### Suggested Solution
Expose a configuration property on an export to enable this behavior globally, or an opt-in on a codec-by-codec basis,
but disable the behavior by default.

### Who does this impact? Who is this for?
Anyone who may use `readonly [] / Readonly<>` to prevent themselves from modifying arrays/objects but use them with libraries that don't work with frozen arrays/objects. (e.g. Vega - chart Views set Symbol properties on data arrays)

### Describe alternatives you've considered
Creating an alias `arrayAsReadonly` for `t.array` that declares the output type as ReadonlyArray<C>

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |   2.2.8 / 1.8.5        |
| fp-ts      |      compatible      |
| TypeScript |     3.9.5       |

**Comment by gcanti** [comment]
> Suggested Solution: Expose a configuration property on an export to enable this behavior globally, or an opt-in on a codec-by-codec basis,
but disable the behavior by default.

I'm just going to remove the `Object.freeze` calls, that's a weird behavior anyway for a `TypeScript`-first library like `io-ts`
