### ISSUE TITLE
How to extract array element codec

### ISSUE THREAD

**Issue by keabarnes** [gcanti/io-ts#521]
## 📖 Documentation
I might have missed it, but I don't see a way to extract the codec of an element in an array? Any guidance would be appreciated.

Typescript:
```typescript
type MyArray = Array<string>
type MyArrayElement = MyArray[number] // == string
```

io-ts:
```typescript
const myArray = t.array(t.string)
const myArrayElement = ... // == t.string
```

**Comment by mlegenhausen** [comment]
There is a `type` Attribute: https://github.com/gcanti/io-ts/blob/master/src/index.ts#L781

```ts
const myArrayElement = myArray.type
```

**Comment by keabarnes** [comment]
Sorry, I should have been clearer with my terminology - I updated the description but not the title. I'm looking for the **codec** for the element in the array, in the example above, `const myArrayElement = t.string`.

**Comment by gcanti** [comment]
@keabarnes the solution provided by @mlegenhausen should be fine

**Comment by keabarnes** [comment]
Sorry all, totally right, above works as expected - thank you!
