### ISSUE TITLE
Readonly by default

### ISSUE THREAD

**Issue by steida** [gcanti/io-ts#525]
As I understand, fp-ts 3 will be readonly only. Should experimental io-ts decode to readonly types as well?

**Comment by gcanti** [comment]
@steida IMO yes, they definitely should.

**Comment by gcanti** [comment]
A first consideration: the following pattern (which can be used to clean a `Decoder` signature)

```ts
import * as D from 'io-ts/Decoder'

const _Person = D.type({
  name: D.string,
  age: D.number
})

interface Person extends D.TypeOf<typeof _Person> {}

const Person: D.Decoder<unknown, Person> = _Person
```

can be slightly modified to support readonly types

```ts
import * as D from 'io-ts/Decoder'

const _Person = D.type({
  name: D.string,
  age: D.number
})

interface Person extends Readonly<D.TypeOf<typeof _Person>> {}

const Person: D.Decoder<unknown, Person> = _Person
```

so we may not have to do anything.

The built-in `Readonly` type can also be used to define a `readonly` combinator

```ts
import { identity } from 'fp-ts/function'

export const readonly: <I, A>(decoder: D.Decoder<I, A>) => D.Decoder<I, Readonly<A>> = identity

const Person = readonly(
  D.type({
    name: D.string,
    age: D.number
  })
)
```

**Comment by steida** [comment]
> can be slightly modified to support readonly types
> so we may not have to do anything.

It looks weird to define all models like that.

**Comment by gcanti** [comment]
https://github.com/gcanti/io-ts/pull/567
