### ISSUE TITLE
Deno support?

### ISSUE THREAD

**Issue by andykais** [gcanti/io-ts#529]
### Current Behavior

this module is available for nodejs

### Desired Behavior

making this module available for [deno](https://deno.land/). Deno is a javascript runtime similar to node but with different tooling, different runtime, and a different module system.

### Suggested Solution

use [denoify](https://github.com/garronej/denoify) to package a deno compatible version of io-ts. io-ts only has a single dependency (fp-ts) so porting this module isnt terribly complicated as far as denoify is concerned. Glueing the two pieces together will take a bit more research than I have done so far (I could stand to understand denoify a little better, and I need to understand the build system of io-ts a little better) but it should be as simple as adding the `denoify` and adding some configuratin to package.json.

### Who does this impact? Who is this for?

This would impact developers using deno as a nodejs alternative. There are currently only a few limited options for schema validation in deno https://deno.land/x?query=schema

### Describe alternatives you've considered
the alternative is to roll my own schema or extend one of the existing schemas. Most other libraries do not have good support for unions and recursive schemas.

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      | N/a         |
| fp-ts      |   N/a         |
| TypeScript |    N/a        |

**Comment by waynevanson** [comment]
@andykais If you're planning to do this (or to anyone), it may be better to port support to `fp-ts` first.

**Comment by brad-jones** [comment]
FWIW I didn't have to do anything special. Just imported from https://esm.sh
see: https://deno-playground.mahardi.me?id=YTI5ODg1NDB

**Comment by andykais** [comment]
this can probably be closed, especially with the introduction of `npm:<package_name>` specifiers in deno 1.25:
```ts
import * as fpts from 'npm:fp-ts'
import * as t from 'npm:io-ts'

const User = t.type({
  userId: t.number,
  name: t.string
})
const user = User.decode({ userId: 1, name: 'test' })
console.log(user)
```

Note that `import * as fpts from 'npm:fp-ts'` was necessary, as otherwise I was hit with the error:
```
error: Uncaught Error: Cannot find module 'fp-ts/lib/Either'
```
I suspect this will be improved in the future though
