### ISSUE TITLE
type name instead of interferred type info from the TypeScript compiler service in Webstorm

### ISSUE THREAD

**Issue by sandrozbinden** [gcanti/io-ts#536]
Hi there,

I hope this is the right way of asking a question. 

I've already asked this question on stackoverflow (see [https://stackoverflow.com/questions/65104703/io-ts-object-typename-is-lost-in-webstorm/65110609#65110609](url)) and also got an answer from a support engineer at jetbrains but wanted to know if someone has a workarround for this. 

Basically what happens is that i am losing the typename when working with io-ts.
Let's assume i have the following code: 

```typescript
const UserType = t.type({
    name: t.string,
});
type User = t.TypeOf<typeof UserType>;
const myUserIoTs: User = { name: 'Luna' };
```
When I want to see the information for the type `User`, Webstorm shows me the inferred type info but not the type name. `const myUserIoTs: {name: string;}` instead of `const myUserIoTs:User`

![typecript_tooltio](https://user-images.githubusercontent.com/1227824/101088469-10f7e900-35b4-11eb-9234-ea460de84f62.png)

It can get really difficult to see what type you are working on when you have complex union types. 
Do you know a workarround to get the type name?

Is there maybe a way we could push the typescript issue [https://github.com/microsoft/TypeScript/issues/25894](url) that was linked in the stackoverflow answer?

Best regards

**Comment by mlegenhausen** [comment]
You need to use `interface User extends t.TypeOf<typeof User> {}` instead.

**Comment by sandrozbinden** [comment]
Hi @mlegenhausen 

Thanks a lot. This works perfectly fine except for the es-lint warning 👍
