### ISSUE TITLE
Why choose `FreeSemigroup` to represent `DecodeError`

### ISSUE THREAD

**Issue by jituanlin** [gcanti/io-ts#538]
## 📖 Documentation
From Source code:
> `export type DecodeError = FS.FreeSemigroup<DE.DecodeError<string>>`

As the title, I don't understand why `FreeSemigroup` matter.
I think of `FreeSemigroup` is just something like *binary tree*(although after `ap`, it will be very "unbalance").

**Comment by gcanti** [comment]
@jituanlin because I need a semigroup for `DE.DecodeError<E>` (for any `E`).
What would you use instead?

**Comment by jituanlin** [comment]
@gcanti 
I know why `Semigroup` matter now.
However,  handle this `Semigroup`  is not *conveniently*(or just for me?).
For example, *io-ts* use this function for get all leaves(`DE.DecodeError`)
```ts
const toForest = (e: DecodeError): ReadonlyArray<Tree<string>> => {
  const stack = []
  let focus = e
  const res = []
  while (true) {
    switch (focus._tag) {
      case 'Of':
        res.push(toTree(focus.value))
        if (stack.length === 0) {
          return res
        } else {
          focus = stack.pop()!
        }
        break
      case 'Concat':
        stack.push(focus.right)
        focus = focus.left
        break
    }
  }
}
```
Why not implement `FreeSimigroup` somehow like the following:
```ts
interface FreeSemigroup<A> {
  container: FreeSemigroup<A>[];
}

const concat = (l: FreeSemigroup<A>, r: FreeSemigroup<A>): FreeSemigroup<A> => {
  return {
    container: l.container.concat(r.container),
  };
};
```
And then, we can *conveniently* get all leaves just `se.container`?

**Comment by safareli** [comment]
Original version of `toForest` was [much simpler](https://github.com/gcanti/io-ts/pull/520/files#diff-16dbc5e69787775b89623a833818bd88951fe3fdf77c49e2161c14459e5e3717L552-L555), current version was introduced for stack safety reasons in #520.

Probably Binary Tree is used for perf reasons. as append/prepend on Binary Tree is constant time. and you pay the cost once when you are formatting the errors.

**Comment by jituanlin** [comment]
> Original version of `toForest` was [much simpler](https://github.com/gcanti/io-ts/pull/520/files#diff-16dbc5e69787775b89623a833818bd88951fe3fdf77c49e2161c14459e5e3717L552-L555), current version was introduced for stack safety reasons in #520.
> 
> Probably Binary Tree is used for perf reasons. as append/prepend on Binary Tree is constant time. and you pay the cost once when you are formatting the errors.

You are right.
