### ISSUE TITLE
Type '"UnionType"' is not assignable to type '"IntersectionType"'

### ISSUE THREAD

**Issue by cs4inctec** [gcanti/io-ts#548]
## 🐛 Bug report

`exact` does not work on `union`, even when in an `intersection`.

### Current Behavior

Wrapping an `intersection` containing a `union` with `exact` produces the following error:

    Type '"UnionType"' is not assignable to type '"IntersectionType"'

(also when directly wrapping a union).

Using `strict` types in the `union` is a workaround for the `union` itself, but does not work, when the `intersection` should be `exact`.

### Expected behavior

Combining `intersection` and `union` works as expected.
Wrapping it with `exact` should additionally strip any values that are not specified in the matched types.

### Reproducible example
this works, without `exact`:

    const aType = t.type({
      type: t.literal('a'),
      a: t.number,
    });
    const bType = t.type({
      type: t.literal('b'),
      b: t.string,
    });

    t.intersection([
      t.type({
        commonAttributes: t.string,
      }),
      t.union([aType, bType]),
    ]);

but this does not work:

    const aType = t.type({
      type: t.literal('a'),
      a: t.number,
    });
    const bType = t.type({
      type: t.literal('b'),
      b: t.string,
    });

    t.exact(t.intersection([
      t.type({
        commonAttributes: t.string,
      }),
      t.union([aType, bType]),
    ]));

### Additional context

Our usage here is for payload validation with types that have different fields based on the type field.
We would like to strip any fields that should not be in the payload.

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |      2.2.10      |
| fp-ts      |      2.9.3      |
| TypeScript |     4.0.3       |

**Comment by gcanti** [comment]
> Using strict types in the union is a workaround for the union itself, but does not work, when the intersection should be exact

If all members are exact then you should get an exact intersection

```ts
const a = t.strict({
  type: t.literal('a'),
  a: t.number
})
const b = t.strict({
  type: t.literal('b'),
  b: t.string
})
const c = t.strict({
  commonAttributes: t.string
})
const d = t.intersection([c, t.union([a, b])])
console.log(
  d.decode({
    commonAttributes: 'a',
    type: 'a',
    a: 1,
    b: 'b'
  })
)
// => { _tag: 'Right', right: { commonAttributes: 'a', type: 'a', a: 1 } }
```

**Comment by cs4inctec** [comment]
:thinking: you are right.
I must have not tried this combination, my bad. :sweat_smile: 
thanks :+1:
