### ISSUE TITLE
Clarification on AnyType deprecation

### ISSUE THREAD

**Issue by Zikoel** [gcanti/io-ts#549]
Hi guys, first of all many thanks for this spectacular library!

I have notices that `AnyType` type is now deprecated and the suggestion is to use `UnknownType` type. No problem for me but I noticed that `UnknownType` behave different from `AnyType` and that broke a part of my codebase, so I am here searching a suggestion for my use case. This is a minimal snippets that raise the difference (sorry I'm unable to find something more synthetic):

```typescript
import { isLeft } from 'fp-ts/lib/These'
import * as t from 'io-ts'

const myDecoder = t.type({
  var1: t.number,
  var2: t.array(t.any),
  // var2: t.array(t.unknown),
})

const validObj = {
  var1: 1,
  var2: [{ foo: 1, bar: 2}, {foo: 'a', bar: 'b'}]
}

const decodingResult = myDecoder.decode(validObj)

if (isLeft(decodingResult)) {
  throw Error('Ooops wrong format')
}

const decodedObj = decodingResult.right

const myStangeArray = decodedObj.var2.map( element => {
  return {...element}
})
```

This code is correct and typescript is happy, now if you try to use the commented line `ts` give this error on the spreading line:

```
Spread types may only be created from object types.ts(2698)
```

Where is my error? What is the best practice here ?

**Comment by gcanti** [comment]
> What is the best practice here ?

You could try to narrow down the type of `var2` as much as you can, using `t.UnknownRecord` for example.

**Comment by Zikoel** [comment]
Thank you for the suggestion! In this case I can't assume nothing for var2 because this is a passthrough for data not under my direct control.

But why to deprecate the `AnyType` in favour of `UnknownType` ? They cannot live both ? This case is a demonstration the there is at least one case covered by the first ones but not by the second.

**Comment by gcanti** [comment]
> this is a passthrough for data not under my direct control

If this is really the case then `t.unknown` is fine.

In your snippet you are spreading though:

```ts
const myStangeArray = decodedObj.var2.map( element => {
  return {...element}
})
```

which is the reason why ts complains.

> But why to deprecate the AnyType in favour of UnknownType ?

I'm not against removing the `@deprectaed` tag, however keep in mind that unknown data is better modeled by `unknown` rather than `any`.

**Comment by Zikoel** [comment]
Thank you for the clarifications. I think the `AnyType` should be continue to stay into the future versions of the library due the fact that best modelled or not here we have two different behaviours! In any case I haven't the right deep knowledge about the whole design and the long term plans to be in the position to say something about that! If the `AnyType` will be removed in the future I suppose I can add it personally inside my own project.
