### ISSUE TITLE
Wrong type inference?

### ISSUE THREAD

**Issue by vegansk** [gcanti/io-ts#55]
While trying to create an example of the issue #54, I created repo https://github.com/vegansk/io-ts-type-issue with some parts of the bigger application. And I ran into another issue: the code [in this line](https://github.com/vegansk/io-ts-type-issue/blob/bc01db84f62c10fb5e40d3facdf4b30a9a640c41/src/index.ts#L25) compiles ok despite the fact that it lacks the required field `taInfo`.  [Here is the link to it's description](https://github.com/vegansk/io-ts-type-issue/blob/bc01db84f62c10fb5e40d3facdf4b30a9a640c41/src/types.ts#L789)

The function `mkType` is implemented in src/adapters.ts like this:
```ts
export function mkType<R extends t.Props, O extends t.Props>(
    required: R, optional: O, name?: string
) {
    return t.readonly(t.intersection([t.interface(required), t.partial(optional)]), name)
}
```

But if I change the value of another required field, for example `taDocNum` of type string to some number, the compiler fails with error:
```
src/index.ts(5,11): error TS2352: Type '{ version: string; uid: string; msgHeader: { sender: { id: string; participantType: "REG"; name: ...' cannot be converted to type 'Readonly<InterfaceOf<{ version: StringType; msgHeader: ReadonlyType<IntersectionType<[InterfaceTy...'.
  Type '{ version: string; uid: string; msgHeader: { sender: { id: string; participantType: "REG"; name: ...' is not comparable to type 'Readonly<InterfaceOf<{ version: StringType; msgHeader: ReadonlyType<IntersectionType<[InterfaceTy...'.
    Types of property 'taDocInfo' are incompatible.
      Type '{ taDocNum: number; taDocDate: Date; }' is not comparable to type 'Readonly<InterfaceOf<{ taInfo: ReadonlyType<IntersectionType<[InterfaceType<{ taInfo: ReadonlyTyp...'.
        Property 'taInfo' is missing in type '{ taDocNum: number; taDocDate: Date; }'.
```

Is it the problem in my code, in io-ts (version 0.5.0 is used), or in the typescript compiler?

UPDATE: checked with typescript 2.3.4 and 2.4.0, both behaves the same.

**Comment by gcanti** [comment]
@vegansk thanks for putting up a repro. In `index.ts` you are casting `v` to `P.Document` which is, in general, an unsafe operation. 

```ts
// no error
const v = <P.Document>{
  ...
}
```

If you add a type annotation instead you can see the expected error

```ts
// error: Property 'taInfo' is missing in type '{ taDocNum: string; taDocDate: Date; }'.
const v: P.Document = {
  ...
}
```

p.s.
If you convert the string literal unions into using `keyof` you'll also see a (possible) bug, a duplicated value (`"0"`) in the `RegionEtType` type
