### ISSUE TITLE
TypeOf yields no type information for intersection-based codecs (in WebStorm)

### ISSUE THREAD

**Issue by craPkit** [gcanti/io-ts#550]
### Current Behavior

I'm trying to [mix required and optional props](https://github.com/gcanti/io-ts/blob/master/index.md#mixing-required-and-optional-props) using `t.intersection([...])`, but whenever I get the `t.TypeOf<typeof myIntersection>`, the resulting type shows as `unknown` (and objects' props cannot be autocompleted) in Webstorm.

![image](https://user-images.githubusercontent.com/4995671/104480834-505b2180-55c5-11eb-99d2-6727ce7f0b28.png)

### Expected behavior
I would expect `t.TypeOf` to yield some useful type based on my inputs to `t.intersect`. 

Something like this (but based on the pre-Decoder API's types, obviously):
![image](https://user-images.githubusercontent.com/4995671/104481977-ada3a280-55c6-11eb-9291-1d6869adfad7.png)

### Reproducible example

```ts
const requiredProps = t.type({
  name: t.string,
  id: t.string,
});
const optionalProps = t.partial({
  optionalDescription: t.string,
  neverMindMissing: t.string,
});

// eslint-disable-next-line @typescript-eslint/naming-convention
export const MyCodec = t.intersection([requiredProps, optionalProps]);
export type MyModel = t.TypeOf<typeof MyCodec>;`
```

### Suggested solution(s)

Point out my error, please.

### Additional context
I'm using WebStorm, so I cannot completely rule out an issue with the TypeScript integration there. Types are displayed as expected though, when I'm not using `t.intersections` (e.g. for a plain `t.partial`-codec-based type) or when I [implement an intersecting Decoder](https://github.com/gcanti/io-ts/blob/master/Decoder.md#the-intersect-combinator) (using the new 2.2 APIs).

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |      2.2.13      |
| fp-ts      |       2.9.3     |
| TypeScript |    4.0.5      |

**Comment by kahnc** [comment]
I've seen the same issue, and it seems to be specific to either WebStorm, or the language server used by WebStorm, because when I open the same file with intersection types in VS Code, the type is inferred correctly.

**Comment by kahnc** [comment]
I've also noticed, in WebStorm, if you hold command (or control in Windows) and hover over the type, the more detailed type popup does indeed resolve the type.
