### ISSUE TITLE
Generate io-ts version based on plain TypeScript type

### ISSUE THREAD

**Issue by alamothe** [gcanti/io-ts#551]
Writing types with `t` is tedious, compared to plain TypeScript types. We are working in a codebase where 50% of the types need to be type-checked at runtime.

Is thee a way to integrate `io-ts` during compile time, and automatically generate runtime type-checked version based on plain `type`? I imagine this could be more performant too.

It doesn't even need to be during compile time, as long as we can invoke a script which will update type-checked version.

Sorry if this has been asked before.

**Comment by samhh** [comment]
I highly suspect this won't be possible without compiler plugins (for the official compiler, anyway), for which there's been very little progress over in the TypeScript repo.

**Comment by gcanti** [comment]
https://github.com/gcanti/io-ts/issues/516
