### ISSUE TITLE
Branded Types Breaks Schema Piping

### ISSUE THREAD

**Issue by danielstoa** [gcanti/io-ts#552]
### Current Behavior

![image](https://user-images.githubusercontent.com/60572569/104633501-e7000f00-56a7-11eb-8544-27beb114c94b.png)

### Expected behavior

Types should match.

### Reproducible example
```
import * as t from 'io-ts';

const SchemA = t.type({
  name: t.union([t.null, t.string]),
  version: t.Int
});

export const SchemaB = SchemA.pipe(
  t.type({
    name: t.string,
    version: t.Int
  })
);
```

### Suggested solution(s)

I think the type definition of 'Schema.pipe' should change, or alternatively, the way 'branded' types works should change. 

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |      2.2.12      |
| TypeScript |    4.1.2        |

**Comment by gcanti** [comment]
@danielstoa the current behavior looks correct

```ts
const SchemA = t.type({
  name: t.union([t.null, t.string]),
  version: t.Int
})

const C = t.type({
  name: t.string,
  version: t.Int
})

export type COutput = t.OutputOf<typeof C>
/*
type COutput = {
    name: string;
    version: number;
}
*/

export const SchemaB = SchemA.pipe(C)
```

`C` will encode `version` as a `number` which cannot be passed to `SchemA` which expects an `Int`.

`t.Int` has type `t.Type<Int, number, unknown>`, you'd need a `t.Type<Int, Int, unknown>` instead

```ts
const SchemA = t.type({
  name: t.union([t.null, t.string]),
  version: t.Int
})

const Int: t.Type<t.Int> = new t.Type(t.Int.name, t.Int.is, t.Int.validate, t.identity)

const C = t.type({
  name: t.string,
  version: Int
})

export const SchemaB = SchemA.pipe(C) // ok
```

**Comment by danielstoa** [comment]
@gcanti
Do you think it's a good idea to modify the original version of 't.Int'? 
I guess if some type can encode a 'number', it should be able to encode an 'Int' as well - because 'Int' is a subset of 'number'.

BTW - we use both io-ts and fp-ts at [stoa.fund](https://www.stoa.fund/), and enjoy them very much, thanks!

**Comment by gcanti** [comment]
> Do you think it's a good idea to modify the original version of 't.Int'?

@danielstoa it would be a breaking change I'm afraid
