### ISSUE TITLE
String union io-ts type

### ISSUE THREAD

**Issue by afonsopbarros** [gcanti/io-ts#554]
## 🚀 Feature request

`type Group = "A" | "B" | "C"`

I would like to declare an io-ts type to do runtime checks on a string union type.

I'm not sure if this is already possible with the current implementation of io-ts, so please enlighten me if that's the case

### Current Behavior

Group: t.string

### Desired Behavior

Group: t.stringUnion(["A", "B", "C")

### Your environment

| Software   | 
| ---------- | 
"io-ts": "^2.1.3",
"io-ts-promise": "^2.0.2",
"typescript": "3.9.7"

**Comment by DenisFrezzato** [comment]
With the stable API, you can create a union of literals using `keyof`. [From the readme](https://github.com/gcanti/io-ts/blob/master/index.md#union-of-string-literals), [documentation](https://gcanti.github.io/io-ts/modules/index.ts.html#keyof).

**Comment by gcanti** [comment]
> With the experimental API, you can use union and literal:

@DenisFrezzato FYI the experimental `D.literal` takes one or more literals

```ts
import * as D from 'io-ts/Decoder'

const Group = D.literal('A', 'B', 'C')
```
