### ISSUE TITLE
Record<string,unknow> fails on non object literals

### ISSUE THREAD

**Issue by waynevanson** [gcanti/io-ts#559]
### Current Behavior

Returns `Left` when using the `decode` function.

### Expected behavior

Returns `Right` when using the `decode` function.

### Reproducible example
```ts
const element = document.body

const result = c.UnknownRecord.decode(element)
// returns: `Left`
```

### Suggested solution(s)

1.
```diff
 exports.UnknownRecord = {
-    is: function (u) { return Object.prototype.toString.call(u) === '[object Object]'; }
+    is: function (u) { return Object.prototype.toString.call(u).startsWith('[object '); }
 };
```

### Additional context

I'm not using `io-ts` to deal with HTTP responses, I'm using it to validate some `Event`'s that have been created with the custom event API.

```
const event = new Event()

const result = Object.prototype.toString.call(event)
// returns: "[Object Event]"
```

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |            |
| fp-ts      |            |
| TypeScript |            |

**Comment by DenisFrezzato** [comment]
We can argue that an `Event` object is not an unknown record and this is the intended behaviour. Perhaps it would be a better idea to have a codec for `Event`? Maybe in `io-ts-types`?

**Comment by waynevanson** [comment]
We cannot use the `type` constructor because it intersects `UnknownRecord` with key/value pairs.

Another solution may be to remove the intersection of `UnknownRecord` from the `type` constructor.

**Comment by mlegenhausen** [comment]
> We can argue that an Event object is not an unknown record and this is the intended behaviour.

We also support the `[object Window]` via `UnknownRecord` why is this an exception?

**Comment by gcanti** [comment]
@waynevanson AFAIK the suggested solution doesn't work (node v12.7.0)

```ts
export const UnknownRecord = {
  is: (u: unknown): u is Record<string, unknown> => Object.prototype.toString.call(u).startsWith('[object ')
}

console.log(UnknownRecord.is(1)) // => true
console.log(UnknownRecord.is('a')) // => true
console.log(UnknownRecord.is(true)) // => true
console.log(UnknownRecord.is(null)) // => true
console.log(UnknownRecord.is(undefined)) // => true
```

**Comment by waynevanson** [comment]
I have a feeling that `Object.prototype.toString.call(u) === '[object Object]')` is 

The goal of this issue for me is to get the following to work:

```ts
import * as g from "io-ts/guard"

const customEvent = new CustomEvent({ myproperty: "value" })
const guard = g.type({ myproperty: g.string })
const result = guard.is(customEvent)

expect(result).toBe(true)
// returns false
```

Solution for this would be to remove `UnknownRecord` from `type` guard, or replace it with `(u) => typeof u === "object"` so primitives return `false`.

**Comment by gcanti** [comment]
I'd go for

```ts
export const UnknownRecord: Guard<unknown, Record<string, unknown>> = {
  is: (u: unknown): u is Record<string, unknown> => u !== null && typeof u === 'object' && !Array.isArray(u)
}
```
