### ISSUE TITLE
Stricter input types

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/io-ts#564]
I am trying to write an io-ts runtime type that represents my URL query parameters.

The input is going to be Node's `ParsedUrlQuery` type:

```ts
interface ParsedUrlQuery {
  [key: string]: string | string[] | undefined;
}
```

We can define `MyQueryParams` using `t.partial`:

```ts
const AnyParam = t.union([t.string, t.array(t.string), t.undefined]);

// unknown -> { foo?: string | string[] | undefined; bar?: string; }
const MyQueryParams = t.partial({
  foo: AnyParam,
  bar: t.string,
});
```

Example usage:

```ts
const parsedUrlQuery: ParsedUrlQuery = {
  foo: 'bar',
};

const myQueryParamsEither = MyQueryParams.decode(parsedUrlQuery);

pipe(
  myQueryParamsEither,
  E.fold(
    () => {},
    (myQueryParams) => {
      const parsedUrlQuery2: ParsedUrlQuery = MyQueryParams.encode(myQueryParams);
    },
  ),
);
```

Unfortunately, the input type (generic `I`) of a type generated by `t.partial` is always `unknown` which means you can make mistakes such as:

- Trying to decode a non-object type, e.g. `MyQueryParams.decode('string here')`.
- Trying to decode an object type whose properties have incorrect types, e.g. `MyQueryParams.decode({ foo: 'bar', bar: 100 })`.

In both of these cases, these are clearly mistakes because the decode will always fail. I would like to be able to catch these mistakes at compile time.

Furthermore, I am trying to write a wrapper around `t.partial` that requires all properties to accept a `Param` as their input type:

```ts
type Param = ParsedUrlQuery[keyof ParsedUrlQuery]; // string | string[] | undefined

const queryParams = <
  R extends {
    [key: string]: t.Type<any, Param, Param>;
  }
>(
  r: R,
) => t.partial(r);
```

The reason I want to do this is that I can restrict which codecs can be used inside of the type, for example:

```ts
const AnyParam = t.union([t.string, t.array(t.string), t.undefined]);

const AnyParamIdentity = new t.Type<Param, Param, Param>(
  'AnyParamIdentity',
  AnyParam.is,
  (p, _c) => t.success(p),
  identity,
);

const StringParamFromAnyParam = AnyParamIdentity.pipe(t.string);

const MyQueryParams = queryParams({
  foo: AnyParamIdentity,
  bar: StringParamFromAnyParam,

  // This should error
  baz: t.number,
});
```

Unfortunately this is not currently possible because `t.partial` requires all codecs to accept `unknown` as their input type, so the definition of the `queryParams` function above produces an error.

### Proposal

`t.partial` should return a type whose input is: an object (not `unknown`) where the properties reflect the input types of the codecs provided.

For example, given:

```ts
declare const NumberFromString: t.Type<number, string, string>;

// unknown -> { bar?: number }
const MyQueryParams = t.partial({
  // Note: currently this errors
  bar: NumberFromString,
});
```

`MyQueryParams` currently has type `t.PartialC<t.Props>`. With my proposal it would have type `t.PartialC<{ bar: t.Type<number, string, string>; }>`.

This means we can catch the mistakes I mentioned previously:

```ts
declare const NumberFromString: t.Type<number, string, string>;

// { bar?: string } -> { bar?: number }
const MyQueryParams = t.partial({
  bar: NumberFromString,
});

MyQueryParams.decode({ bar: '100' }); // doesn't error ✅
MyQueryParams.decode('string here'); // errors ✅
MyQueryParams.decode({ bar: 100 }); // errors ✅
```

In this case we're decoding from a type that is already semi-structured, but decoding from `unknown` is very useful when we're dealing with something external like an API response.

If we want to allow `unknown` as the input type, we can create another runtime type that decodes `unknown` to the required input type, and then compose the two types:

```ts
// unknown -> ParsedUrlQuery
declare const ParsedUrlQueryFromUnknown: t.Type<
    ParsedUrlQuery,
    unknown,
    unknown
>;

// unknown -> ParsedUrlQuery -> { bar?: number; }
const MyQueryParamsFromUnknown = ParsedUrlQueryFromUnknown.pipe(MyQueryParams);

MyQueryParamsFromUnknown.decode({ bar: '100' }); // doesn't error ✅
MyQueryParamsFromUnknown.decode('string here'); // doesn't error ✅
MyQueryParamsFromUnknown.decode({ bar: 100 }); // doesn't error ✅
```

---

Side notes:
- This proposal could also be applied to other combinators like `t.type`.
- I realise this would be a breaking change so we would have to wait until the next major version.
- Related: https://github.com/gcanti/io-ts-types/issues/135

**Comment by mlegenhausen** [comment]
In generell as you already mentioned in #135 a more granular type conversion would be great but this would of cause introduce a breaking change. In this case it seems we would change `I` to `UnknownRecord`. This would introduce an additional step where we go from `UnknownRecord` via `pipe` to our `t.partial` or `t.type` definition.

I already encountered the same problem and came up with a little helper signature that simply uses the fact that we normally want the `O` instead of `I` when seeing a `t.Type` instance. If you want a more stricter version you can use this helper `decode` function.

```ts
export function decode<O, A>(type: t.Type<A, O>): (value: O) => Either<t.Errors, A>
export function decode<I, A>(codec: t.Decoder<I, A>): (value: I) => Either<t.Errors, A>
export function decode<I, A>(codec: t.Decoder<I, A>): (value: I) => Either<t.Errors, A> {
  return codec.decode
}
```

When we then apply your example code we get the wanted error also when `I` is `unknown`

```ts
const MyQueryParams = t.partial({
  // The already existing codec from io-ts-types
  bar: tt.NumberFromString
})

decode(MyQueryParams)({ bar: '100' }) // doesn't error ✅
decode(MyQueryParams)('string here') // errors ✅
decode(MyQueryParams)({ bar: 100 }) // errors ✅
```

**Comment by OliverJAsh** [comment]
> helper `decode` function.

This is useful, thank you! We could also write helper that wraps a given `Type`:

```ts
const _MyQueryParams = t.partial({
    // The already existing codec from io-ts-types
    bar: tt.NumberFromString,
});

const useOutputAsInput = <A, O>(type: t.Type<A, O, any>): t.Type<A, O, O> =>
    new t.Type(
        'fo',
        type.is,
        (i: t.OutputOf<typeof type>, c) => type.validate(i, c),
        type.encode,
    );

const MyQueryParams = useOutputAsInput(_MyQueryParams);

MyQueryParams.decode({ bar: '100' }); // doesn't error ✅
MyQueryParams.decode('string here'); // errors ✅
MyQueryParams.decode({ bar: 100 }); // errors ✅
```

Unfortunately I still have the other problem I described (section: "I am trying to write a wrapper around `t.partial` that requires all properties to accept a `Param` as their input type").

> In this case it seems we would change `I` to `UnknownRecord`.

As I mentioned in my proposal, could we not go one step further and [make `I` reflect the codecs passed in to `t.partial`](https://github.com/gcanti/io-ts/issues/564#issue-805702520-permalink:~:text=t.partial%20should%20return%20a%20type%20whose,input%20types%20of%20the%20codecs%20provided.)? That would allow us to catch those errors/mistakes without an extra helper `decode` function like the one you suggested. It would also solve the other problem I described with regards to writing a wrapper around `t.partial` to restrict the codecs of the properties.

**Comment by mlegenhausen** [comment]
> As I mentioned in my proposal, could we not go one step further and make I reflect the codecs passed in to t.partial? IIUC, if we only changed it to UnknownRecord we would still not catch errors such as

IMHO this will make `decode` useless cause I use it most of the time to go from `unknown` to some defined type. Currently we do the following `I -> A` conversion in case of `partial` with our `MyQueryParams` example `unknown -> { bar: number }`. When we would use `UnknownRecord` we can go from `unknown -> UnknownRecord -> { bar: number }` but how could we build up this pipe when `I` is `{ bar: string }` which is equal to `O`? Then we would need something like `unknown -> UnknownRecord -> { bar: string } -> { bar: number }` and when we restrict `t.partial` or `t.type` to `{ bar: string } -> { bar: number }` we would nee a new type to go from `UnknownRecord -> { bar: string }` or am I missing something?

**Comment by OliverJAsh** [comment]
> we would nee a new type to go from `UnknownRecord -> { bar: string }` or am I missing something?

That is correct. I mentioned that in my proposal above:

> In this case we're decoding from a type that is already semi-structured, but decoding from `unknown` is very useful when we're dealing with something external like an API response.
> 
> If we want to allow `unknown` as the input type, we can create another runtime type that decodes `unknown` to the required input type, and then compose the two types:
> 
> ```ts
> declare const ParsedUrlQueryFromUnknown: t.Type<
>     ParsedUrlQuery,
>     unknown,
>     unknown
> >;
> const MyQueryParamsFromUnknown = ParsedUrlQueryFromUnknown.pipe(MyQueryParams);
> 
> MyQueryParamsFromUnknown.decode({ bar: '100' }); // doesn't error ✅
> MyQueryParamsFromUnknown.decode('string here'); // doesn't error ✅
> MyQueryParamsFromUnknown.decode({ bar: 100 }); // doesn't error ✅
> ```

Maybe we could have two versions of `t.partial`—one that decodes from `unknown` and one that decodes from `O`?

For example:

```ts
declare const NumberFromString: t.Type<number, string, string>;

// { bar: string } -> { bar: number }
const A = t.partialStrict({
  bar: NumberFromString,
});

// unknown -> { bar: string }
const B = t.partial({
  bar: t.string,
})

// unknown -> { bar: string } -> { bar: number }
const C = B.pipe(A)
```

This gives us the most flexibility—we can use `A` on its own which will allow us to catch errors when we're decoding from a type that already has some structure, or we can use `C` to decode from `unknown`.

**Comment by mlegenhausen** [comment]
Or we could add a new function to `t.Type` that has the signature `(o: O) => Either<t.Errors, A>` beside the `decode` function `(i: I) => Either<t.Errors, A>` which would work when we could say that `O extends I`? I simply assumed that with my `decode` helper.

**Comment by OliverJAsh** [comment]
That's an interesting idea. How hard would it be to make that change?

For now I am able to achieve all of my needs by simply replacing `I` with `O`. Complete example:

```ts
import * as E from 'fp-ts/Either';
import { identity, pipe } from 'fp-ts/function';
import * as t from 'io-ts';

const useOutputAsInput = <A, O>(type: t.Type<A, O, any>): t.Type<A, O, O> =>
    new t.Type(
        `useOutputAsInput(${type.name})`,
        type.is,
        (i: t.OutputOf<typeof type>, c) => type.validate(i, c),
        type.encode,
    );

interface ParsedUrlQuery {
    [key: string]: string | string[] | undefined;
}

type Param = ParsedUrlQuery[keyof ParsedUrlQuery];

const queryParams = <
    R extends {
        [key: string]: t.Type<any, Param, any>;
    }
>(
    r: R,
) => useOutputAsInput(t.partial(r));

const AnyParam = t.union([t.string, t.array(t.string), t.undefined]);

const AnyParamIdentity = new t.Type<Param, Param, Param>(
    'AnyParamIdentity',
    AnyParam.is,
    (p, _c) => t.success(p),
    identity,
);

const StringParamFromAnyParam = AnyParamIdentity.pipe(t.string);

// ParsedUrlQuery -> { foo?: string | string[] | undefined; bar?: string; }
const MyQueryParams = queryParams({
    foo: AnyParamIdentity,
    bar: StringParamFromAnyParam,

    // Disabled as it ruins inference (leaks `any`)
    // baz: t.number, // errors ✅
});
type MyQueryParams = t.TypeOf<typeof MyQueryParams>;

const parsedUrlQuery: ParsedUrlQuery = {
    foo: 'bar',
};

const myQueryParamsEither = MyQueryParams.decode(parsedUrlQuery);

pipe(
    myQueryParamsEither,
    E.fold(
        () => {},
        (myQueryParams) => {
            const parsedUrlQuery2: ParsedUrlQuery = MyQueryParams.encode(
                myQueryParams,
            );
        },
    ),
);

MyQueryParams.decode(parsedUrlQuery); // doesn't error ✅
MyQueryParams.decode('string here'); // errors ✅
MyQueryParams.decode({
    foo: 'bar',
    bar: 1, // errors ✅
});

// unknown -> ParsedUrlQuery
declare const ParsedUrlQueryFromUnknown: t.Type<
    ParsedUrlQuery,
    unknown,
    unknown
>;

// unknown -> ParsedUrlQuery -> { foo?: string | string[] | undefined; bar?: string; }
const MyQueryParamsFromUnknown = ParsedUrlQueryFromUnknown.pipe(MyQueryParams);

MyQueryParamsFromUnknown.decode({ bar: '100' }); // doesn't error ✅
MyQueryParamsFromUnknown.decode('string here'); // doesn't error ✅
MyQueryParamsFromUnknown.decode({ bar: 100 }); // doesn't error ✅
```

**Comment by mlegenhausen** [comment]
I think we would need to change `Type` in a breaking way to 

```
export class Type<A, O extends I, I = unknown> implements t.Decoder<I, A>, t.Encoder<A, O> {}
```

cause we can not set `A` as default type for `O` but we would make `x = decode(encode(x))` explicit in the type signature?

**Comment by OliverJAsh** [comment]
@gcanti Curious to hear if you have any thoughts on all of this?

**Comment by gcanti** [comment]
Looks like you want something along the lines of the `fromPartial` combinator in the experimental module `Decoder`

```ts
import * as D from 'io-ts/Decoder'

const AnyParam = D.union(D.string, D.array(D.string))

const MyQueryParams = D.fromPartial({
  foo: AnyParam,
  bar: D.id<string>()
})
/*
const MyQueryParams: D.Decoder<Partial<{
    foo: unknown;
    bar: string;
}>, Partial<{
    foo: string | string[];
    bar: string;
}>>
*/

MyQueryParams.decode('string here')
MyQueryParams.decode({ foo: 'bar', bar: 100 })
```

> Furthermore, I am trying to write a wrapper around t.partial that requires all properties to accept a Param as their input type

IIUC something like

```ts
type Param = ParsedUrlQuery[keyof ParsedUrlQuery] // string | string[]

const queryParams = <P extends Record<string, D.Decoder<any, Param>>>(properties: P) => D.fromPartial(properties)

const AnyParamIdentity = D.id<Param>()

const MyQueryParams2 = queryParams({
  foo: AnyParamIdentity,
  bar: pipe(AnyParamIdentity, D.compose(D.string))
  // baz: D.number // error
})
/*
const MyQueryParams2: D.Decoder<Partial<{
    foo: Param;
    bar: Param;
}>, Partial<{
    foo: Param;
    bar: string;
}>>
*/
```

**Comment by OliverJAsh** [comment]
> Looks like you want something along the lines of the `fromPartial` combinator in the experimental module `Decoder`

😍😍😍😍😍
