### ISSUE TITLE
Recursion with Codecs

### ISSUE THREAD

**Issue by patrickjtoy** [gcanti/io-ts#566]
## 📖 Documentation

I wasn't able to find any documentation or examples on how to work with recursive data structures using the new Codec module and so I am hoping for some pointers.

To start, I do want to use the new Codec module, as I would like to be able to map key names and values incoming from an external API to names and values more suited to working with in my app. The Codec module seems to be the best fit for this and similar to Elm's JSON decoders/encoders.

Here is what I've gotten so far (example paired down to only show the recursive property)

```typescript
import { pipe } from 'fp-ts/function'
import { Codec, array, imap, lazy, type } from 'io-ts/Codec'

type GroupInput = {
  sub_groups: GroupInput[]
}

const _group: Codec<unknown, unknown, GroupInput> = lazy('Group', () => {
  return type({
    sub_groups: array(_group)
  })
})

export const group = pipe(
  _group,
  imap(
    ({ sub_groups ...rest }) => ({
      subGroups: sub_groups.map(group), // <--- Error
      ...rest
    }),
    ({ subGroups, ...rest }) => ({
      sub_groups: subGroups.map(group), // <--- Error
      ...rest
    })
  )
)
```

The problem lies in how to transform the sub groups using the same pipe. To be honest, I'm not sure I am even using the `lazy` function correctly - I naively assumed it was for recursive purposes, but feel free to let me know if that assumption was incorrect. Perhaps there is a lazy utility from `fp-ts` meant to accompany Codec's lazy for this purpose? It would be great if you could point me in the right direction or, even better, provide an example of how I should accomplish this.

Thanks in advance for your help!

**Comment by gcanti** [comment]
Looks like you can do the transformation in only one step

```ts
import { pipe } from 'fp-ts/function'
import * as C from 'io-ts/Codec'

type GroupInput = {
  sub_groups: GroupInput[]
}

type GroupOutput = {
  subGroups: GroupOutput[]
}

const group: C.Codec<unknown, GroupInput, GroupOutput> = C.lazy('Group', () =>
  pipe(
    C.type({
      sub_groups: C.array(group)
    }),
    C.imap(
      ({ sub_groups, ...rest }) => ({ subGroups: sub_groups, ...rest }),
      ({ subGroups, ...rest }) => ({ sub_groups: subGroups, ...rest })
    )
  )
)

console.log(
  JSON.stringify(
    group.decode({
      sub_groups: [{ sub_groups: [] }, { sub_groups: [] }]
    }),
    null,
    2
  )
)
/*
{
  "_tag": "Right",
  "right": {
    "subGroups": [
      {
        "subGroups": []
      },
      {
        "subGroups": []
      }
    ]
  }
}
*/

console.log(
  group.encode({
    subGroups: [
      {
        subGroups: []
      },
      {
        subGroups: []
      }
    ]
  })
)
/*
{ sub_groups: [ { sub_groups: [] }, { sub_groups: [] } ] }
*/
```

**Comment by patrickjtoy** [comment]
Cheers for the fast reply and the help! Just to make sure I understand then, `C.lazy` performs some "magic" under the hood that ensures the recursive property is evaluated properly?

**Comment by gcanti** [comment]
Well, no magic actually, `lazy` is doing its job :+1:

```ts
const group: C.Codec<unknown, GroupInput, GroupOutput> = C.lazy('Group', () =>
  pipe(
    C.type({
      sub_groups: C.array(group) // <= here `group` is already `imap`ped therefore will handle the nested levels
    }),
    C.imap( // <= this handles the first level
      ({ sub_groups, ...rest }) => ({ subGroups: sub_groups, ...rest }),
      ({ subGroups, ...rest }) => ({ sub_groups: subGroups, ...rest })
    )
  )
)
```

**Comment by patrickjtoy** [comment]
Thanks for the clarification and for the awesome library!
