### ISSUE TITLE
Split decoding and fp side to reduce package size

### ISSUE THREAD

**Issue by dgreene1** [gcanti/io-ts#568]
### Current Behavior

Right now the file size of using io-ts is very large given that we have to bring in fp-ts as well.

For context, my company is considering using io-ts for the purposes of enforcing the runtime contracts in the boundary between MicroFrontend. So if all 30 MicroFrontends use io-ts, that’s a lot of size download each time the user lazy-loads a new MicroFrontend. We use [single-spa](https://single-spa.js.org/) for our microfrontend platform if you’re curious.

### Desired Behavior

We create a package called something like io-ts-lite that has no dependency on fp-ts. Then users can import that package if they want a small size.

### Suggested Solution

I don’t want to be prescriptive about the solution. The goal is just to make the file size of io-ts smaller.

### Who does this impact? Who is this for?

It’s for those who are comfortable with a more imperative style (ie those who can use an if statement instead of isRight). Functional fans and/or those who are less performance concerned can continue to use the larger package or combine the micro packages (however this issue gets solved).

### Describe alternatives you've considered

Single-spa provides a way to remove common dependencies via a connection with webpack’s external property, but that would mean that all MicroFrontends end up having different versions of io-ts at compile time and a single, newer version of io-ts at runtime... which makes me extremely uncomfortable. So this alternative will not be used.

Another alternative would be for me to create a new library that essentially fork’s io-ts... but I’d rather not split the community and/or try to compete with the real io-ts. That’s why I’m suggesting a solution that involves some kind of refactoring internally to this repo.

### Your environment

n.a. Since this is applicable to all environments.

**Comment by samhh** [comment]
I'm curious, considering tree shaking, how much of fp-ts actually makes its way into a bundle if it's only used internally by io-ts?

**Comment by dgreene1** [comment]
Given the amount of includes in all of the files, I suspect that it’s quite a lot.

**Comment by gcanti** [comment]
AFAIK the problem is not `fp-ts`, but the `class`-based APIs. For example the following snippet: 

```ts
import { isRight } from "fp-ts/Either";
import * as t from "io-ts";

const User = t.type({
  userId: t.number,
  name: t.string
});

const result = User.decode({ userId: 1, name: "name" });
if (isRight(result)) {
  console.log(result.right);
}
```

(using `io-ts@2.2.15`) produces a bundle of:

- rollup: 17K
- webpack 5: 19K

Here's the [output](https://github.com/gcanti/tree-shaking-test/blob/ad68907bee3265bc571f32302b3d2277fd288eac/target/rollup.js) (rollup).

> how much of fp-ts actually makes its way into a bundle if it's only used internally by io-ts?

it seems negligible (in this case).

**Comment by dgreene1** [comment]
I went with [zod](https://github.com/colinhacks/zod) because it was smaller and because my team is less inclined to pick up functional programming techniques.

If I have the the time, I’ll reply with the metrics. But our website was noticeably snappier.

**Comment by gcanti** [comment]
> If I have the the time, I’ll reply with the metrics

@dgreene1 thanks

`io-ts` only imports the `Either` module, `fp-ts` should be tree-shaked away, if it doesn't either you are importing from `io-ts/lib/...`, `fp-ts/lib/...` instead of `io-ts/...`, `fp-ts/...` or I'd be interested in a repro as it's a defect
