### ISSUE TITLE
fail to generate definitions

### ISSUE THREAD

**Issue by pierremarc** [gcanti/io-ts#57]
Because ```interfaceType``` is not exported, it triggers 

> error TS4023: Exported variable 'i' has or is using name 'interfaceType' from external module "[...]/node_modules/io-ts/lib/index" but cannot be named.

**Comment by gcanti** [comment]
Not sure I understand, `interfaceType` is exported as `interface` https://github.com/gcanti/io-ts/blob/d9bcfc59dc54f313d013bd2f8d9e827fcd6e5015/src/index.ts#L683. Could you please put up a repo reproducing the error?

**Comment by pierremarc** [comment]
https://github.com/pierremarc/io-ts-57

but here's the code 
```typescript
import * as io from 'io-ts';
export const i = io.interface;
export const myInterface = i({
    a: io.string,
});
```

And the problem comes from trying to re-export io.interface, which i do as a shortcut for other modules.

**Comment by gcanti** [comment]
Ah.. I got it, thanks for the repo. TypeScript currently outputs a definition file with the following declaration

```ts
declare function interfaceType<P extends Props>(props: P, name?: string): InterfaceType<P>;
...
export { nullType as null, undefinedType as undefined, arrayType as Array, functionType as Function, interfaceType as interface };
```

So `interfaceType` is not exported but the type of `io.interface` presumably points to `interfaceType` so when you try to re-export `io.i` TypeScript complains.

As a fix I could export `interfaceType` as well (and maybe also renaming the function to `_interface` so is not so similar to the exported type `InterfaceType`)
