### ISSUE TITLE
Clarify the difference between `index.ts` and the “experimental” modules in v2.2

### ISSUE THREAD

**Issue by vanniewelt** [gcanti/io-ts#571]
What's the relation between `index.ts` and the other modules like `Decoder.ts`, `Encoder.ts`, `Codec.ts` etc.? I think the `README.md` and/or documentation should be more explicit and clear about this.

It says only that there are "stable" and "experimental" features, but it doesn't say that the "experimental" modules are independent and backward-incompatible with stable ones (ie. `Type` from `index.ts` is something different from `Codec` from `Codec.ts`)

This is confusing to newcomers as it is customary for `index.ts` to serve as an entry point to a library that re-exports everything else. But counterintuitively, `index.ts` is unrelated to the rest of the modules. I think people should be at least warned about this. Ideally, I think the new modules should be factored out into a new major version, which would communicate the break with legacy code more clearly – but maybe this is what's planned when the experimental features get stabilized (?)

**Comment by gcanti** [comment]
> but maybe this is what's planned when the experimental features get stabilized

Yes, exactly, that's right.

I'll add the following warning to the README:

> The experimental modules are independent and backward-incompatible with stable ones
