### ISSUE TITLE
Make a modified variant of a type?

### ISSUE THREAD

**Issue by eivindml** [gcanti/io-ts#573]
Hi,

I have a type `School`, which I use for most of my application. But there is one instance I need a slightly modified version of this type, where one property is optional. 

Can I override one property somehow, or in some other way create this new version, without recreating the whole thing?

```js
export const School= t.intersection([
  t.type({
    _id: t.string, //
    title: t.string,
    slug: t.string, //

    contactPerson: t.type({
      name: t.string,
      email: t.string
    }),
    schoolContact: t.intersection([
      t.type({
        name: t.string,
        email: t.string
      }),
      t.partial({
        phone: t.string,
        instagram: t.string,
        facebook: t.string
      })
    ]),
    address: t.type({
      street: t.string,
      zip: t.string,
      city: t.string,
      municipality: t.string,
      location: t.type({
        lat: t.number,
        lng: t.number
      })
    })
  }),
  t.partial({
    images: t.array(ImageType),
    about: t.partial({
      established: t.number,
      area: t.number,
      numberOfStudents: t.number,
      intro: t.string,
      body: t.string
    })
  })
]);
export type School = t.TypeOf<typeof School>;
```

The other version should be exactly the same, except that `location: t.type({ lat: t.number, lng: t.number })` should be optional.

**Can this be done?**

**Comment by enricopolanski** [comment]
I'm not really well versed anymore in the `Type` api, but as a general tip, write complex types it through combining smaller ones.

E.g. 

```ts
const Location = t.type({ lat: t.number, lng: t.number })
```

now you can assign it to `location: Location`. So on, you can start refactoring your entire type and make it out of smaller `Type`s. This makes creating variants extremely simpler and gives a better developer experience overall.

**Comment by eivindml** [comment]
Thanks! This is what I ended up doing, but I still wish there was some way to create a new type based on another type, e.g. without one field.
