### ISSUE TITLE
Question: [Thing].decode optional support.

### ISSUE THREAD

**Issue by Matthijn** [gcanti/io-ts#592]
Currently I have this working, where I can decode multiple values in one go. 

```typescript
pipe(
 sequenceS(E.either)({
    value: SlugValue.decode(dto.value),
    foreignId: UUID.decode(dto.foreignId),
    redirectId: UUID.decode(dto.redirectId)
  }),
  E.map(({ value, foreignId, redirectId }) => {
    // Can do stuff here
  })
)
```

But `dto.redirectId` can be null too. How can I get it to support that? 

I tried this:

```typescript
import { option } from 'io-ts-types/lib/option'
const res = option(UUID).decode(null)

// res = {
//  _tag: 'Left',
//  left: [ { value: null, context: [Array], message: undefined } ]
//}
```

But then res seems to become a left instead of a right `Option`

**Comment by samhh** [comment]
I think you're looking for [optionFromNullable](https://gcanti.github.io/io-ts-types/modules/optionFromNullable.ts.html) from io-ts-types.

**Comment by Matthijn** [comment]
That does seem to work! So it became. 

```typescript
const res = optionFromNullable(UUID).decode(null)
````
