### ISSUE TITLE
How to parse binary file content

### ISSUE THREAD

**Issue by SirWindfield** [gcanti/io-ts#597]
Hey! Sorry to take the issue tracker hostage but [GitHub Discussions](https://docs.github.com/en/discussions) aren't enabled in this repository :)

I have binary files I'd like to parse. I am only interested in reading them and parsing them into usable types. Seeing the examples and documentation I think I have to write decoders. But I am not exactly sure how that would work for binary content. The examples all use `strings` or other types that are native to JS.

Would I have to use `Buffer` or `ArrayBuffer` as my input type? And then use those to convert into the appropiate types I want? Or is there another (better) approach?

**Comment by DenisFrezzato** [comment]
How can you have a `Buffer` of type `unknown`? I'm just interested in the use case.

Also, wouldn't [`isBuffer`](https://nodejs.org/api/buffer.html#buffer_static_method_buffer_isbuffer_obj) be enough?

**Comment by SirWindfield** [comment]
You’re right. The input wouldn’t be unknown but a Byte buffer of some sort. The use-case is to read in various binary save file formats for video games. They all have different formats. Some use special hex characters to denote the type of value that follows, some have their values at fixed locations written.
I wanted to try and use optics to understand them better. And I often found resources online that referred to them in the context of parsing/reading data from web requests or files.

**Comment by samhh** [comment]
The same author of this library and fp-ts has also written the [parser-ts](https://github.com/gcanti/parser-ts) library, though I've never used it.

**Comment by SirWindfield** [comment]
Thanks for the answers but I've decided to scrap the project! Maybe I'll find another use-case for this library, as I really like the idea behind it :)
