### ISSUE TITLE
State of this library / directions for newcomers

### ISSUE THREAD

**Issue by florianbepunkt** [gcanti/io-ts#606]
## 📖 Documentation

I recently got into FP, so definitely a newcomer with regards to this. As I see from the issues and the README this library is somewhere in flux, moving to a new API.

I wonder what the current state is and what you would recommend for a newcomer. I have a project which extensively uses fp-ts and I would like to model some domain concepts with io-ts. Does it make sense to begin a new project with the new API? How fixed is the general direction of the api changes? Are they more like loose ideas or more a sort of beta-version?
Is there any starting point to read about new api?

I did some research but only found articles that use the "old" api. I know that the modules are documented, but for a beginner it's hard if you don't have a understanding of how the parts are connected and how they are supposed to work together.

**Comment by mlegenhausen** [comment]
For newcomers I would still recommend to use the stable version. As the stable indicates there will be no breaking changes in the future and you can get lot of information how to use it form the issue tracker and a simple internet search. You should also take a look at the `io-ts-types` library that depends on the stable version of `io-ts` that provides codecs for `fp-ts` types. There are other more advanced libraries like `@morphic-ts` that depend on `io-ts` and extend the concepts even further.

You don't get all of that from the experimental version and it will take some time to port all of that to the new version.

**Comment by florianbepunkt** [comment]
@mlegenhausen Thank you. Makes sense.
