### ISSUE TITLE
Omitted value is not treated as `undefined` when calling `is` function

### ISSUE THREAD

**Issue by edosrecki** [gcanti/io-ts#616]
### Current Behavior
Missing value is not treated as `undefined` when performing the `is` function call. It does work properly when calling `decode` (it returns `Right`), so it is inconsistent.

```ts
import * as t from 'io-ts'

const Foo = t.type({
  foo: t.string,
  baz: t.union([t.undefined, t.string])
})

type Foo = t.TypeOf<typeof Foo>                          // { foo: string, baz: string | undefined }

Foo.is({ foo: 'foo', baz: 'baz' }))         // true
Foo.is({ foo: 'foo', baz: undefined })      // true
Foo.is({ foo: 'foo' })                      // false
```

### Expected behavior
I expect `is` function to return true if a property defined as `t.undefined` is omitted from the object.

```ts
Foo.is({ foo: 'foo' })                       // true
```

### Suggested solution(s)
By quickly checking the code, I see that [this line](https://github.com/gcanti/io-ts/blob/87f6b860001eb4b487429b0547cfa9a4efca33b4/src/index.ts#L1346) is responsible for that behaviour. 

Why is the `(uk === undefined && !hasOwnProperty.call(u, k))` part necessary?

EDIT:
Now I see, after removing that part, 1 test fails (for `t.uknown`). Can we somehow make both things work?

### Your environment

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |   2.2.16         |
| fp-ts      |  2.11.5          |
| TypeScript |  4.4.4          |

**Comment by grossbart** [comment]
With your codec, you're saying that the field `baz` is required, but its value could be `string | undefined`. If you define your codec like so, it should work as you expect it to:

```js
import * as t from 'io-ts'

const Foo = t.intersection([
  t.type({
    foo: t.string
  }),
  t.partial({
    baz: t.string
  })
])

type Foo = t.TypeOf<typeof Foo> // { foo: string, baz?: string }
```

**Comment by edosrecki** [comment]
@grossbart understood, but how can I then define a type like `Option<string>` and make it work with either explicit `undefined` value or omitted value?

I would like to define a type like:
```
t.type({
  foo: t.string,
  bar: optionalString
})
```

where `optionalString` is my custom type that I expect to give me `none` on both omitted and explicit `undefined`. And in this case again, `decode` can handle it well, but `is` returns false, because it automatically returns false on `undefined` values without even passing them to `type.is`.

**Comment by edosrecki** [comment]
Also if I use `optionFromNullable`:

```
import * as t from 'io-ts'
import { optionFromNullable } from 'io-ts-types'

t.type({
  foo: t.string,
  bar: optionFromNullable(t.string)
})
```

I hit the same issue.

**Comment by DenisFrezzato** [comment]
@edosrecki seems to work fine to me.
```ts
const X = t.type({
  foo: t.string,
  bar: optionFromNullable(t.string),
})

X.is({ foo: 'foo' }) // false
X.is({ foo: 'foo', bar: none }) // true
```

**Comment by edosrecki** [comment]
@DenisFrezzato 

```ts
const X = t.type({
  foo: t.string,
  bar: optionFromNullable(t.string),
})

const input = { foo: 'foo' }
const decoded = X.decode(input)

console.log(JSON.stringify(decoded, null, 2))
// {
//   "_tag": "Right",
//   "right": {
//     "foo": "foo",
//     "bar": {
//       "_tag": "None"
//     }
//   }
// }

console.log(X.is(decoded))
// false

console.log(X.is(input))
// false
```

**Comment by edosrecki** [comment]
Thanks, I was using it incorrectly, I was doing:

```ts
const input = { foo: 'foo' }
const decoded = X.decode(input)

X.is(decoded) // false (correctly)
```

instead of
```ts
X.is(decoded.right) // true :)
```

Sorry about the bug report, my bad. :)
