### ISSUE TITLE
Problem with source-map-loader when using webpack: "The keyword 'interface' is reserved"

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#63]
(Issue using io-ts 0.5.0, 0.5.1 and 0.6.0)
The problem is that Webpack transform userland code of io-ts like this:
```
import { _A, array, boolean, failure, interface, intersection, number, partial, recursion, string, success } from 'io-ts/index';
```

importing directly 'interface' even if the original code was using it like so:
```
import * as t from 'io-ts';

const myType = t.interface({
...
})
```

Resulting in an error when source-map-loader kicks in:
```
The keyword 'interface' is reserved (1:38) You may need an appropriate loader to handle this file type.
```

Also this generates a visual error in visual code studio.

A solution would be to provide an alternative keyword.

**Comment by sledorze** [comment]
Actually using 
```t._interface```
is ALREADY available, so that's all I needed.

**Comment by sledorze** [comment]
I am reopening this issue because, the same problem happends with
```t.null```

**Comment by sledorze** [comment]
@gcanti the problem is pretty general in this setting.
Maybe we can double all the exported definitions whose names match reserved keywords?

**Comment by gcanti** [comment]
@sledorze Could you please put up a repo reproducing the error?

Based on your description though, it doesn't seem an issue with io-ts, it rather seems a bug in the transformer

**Comment by gcanti** [comment]
@sledorze anyway I'm ok with exporting some alias, I propose

- `type` as an alias of `interface`
- `nullType` as an alias of `null`

does undefined raise an error too?

**Comment by sledorze** [comment]
@gcanti undefined is 'correctly webpacked' to something like: undefined as undefined$1

**Comment by gcanti** [comment]
`type` is not a [reserved keyword](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar). Also seems appropriate

```ts
type Person = {
  name: string
}

const Person = t.type({
  name: t.string
})
```

**Comment by sledorze** [comment]
It is a typescript keyword, not a js one, you're right
Hoping it will not pose an issue with tooling then :)
