### ISSUE TITLE
Question on Codec laws and transformation/normalization.

### ISSUE THREAD

**Issue by patrickjcurran** [gcanti/io-ts#632]
## 📖 Documentation
In my (simplified) use case: I want to have a refined type for "lower case strings", but I also want to be liberal about what I accept, and call `.toLowerCase()` on the input if it is a string. Of course, there's no way to use that as part of a `Codec` without breaking [law number 1](https://github.com/gcanti/io-ts/blob/master/Codec.md), because you can't recover the original string.

Is breaking that law actually a problem?

A little more context, I'm pretty sure I do need a `Codec` because I'm sharing this code between my frontend and backend, and what I want to send/receive is roughly:
```
{
  foo: BigIntFromString;
  bar: LowerCaseString;
}
```
The `bigint` doesn't play well with `JSON.parse`, so I'd like to encode/decode as a string, and `bar` I'm getting from some place I don't trust so I'd like to be liberal in accepting something not lower case. 

I just started looking at the library, so maybe I'm trying to do things that it is not intended for.

**Comment by kmbt** [comment]
Hi, I've also started using this library not long ago, and I don't understand it fully, but I suppose, that the point of this law is that if it holds, the `Codec`s compose well, are reversible and thus are very easy to reason about when building more complex solutions. External libraries might also depend on that contract.

Have you thought about just using a separate `Encoder` and `Decoder`? Or maybe decomposing your task into a `Codec` which goes by the laws and a Decoder which is meant to do the 'dirty job' of preprocessing (loosing information)? I think you may use`Either.chain()` to compose the two when decoding.

**Comment by patrickjcurran** [comment]
>Have you thought about just using a separate Encoder and Decoder? Or maybe decomposing your task into a Codec which goes by the laws and a Decoder which is meant to do the 'dirty job' of preprocessing (loosing information)? I think you may useEither.chain() to compose the .decode() functions of the two when decoding.

I have thought about that, what I'm struggling with is that my 'lower case string' is pretty low level. Imagine I have a complicated object (let's call it `ComplicatedDomainObject`) with, say, 14 different fields at various levels that are  `LowerCaseString`s. I don't want to duplicate the effort of building up the `ComplicatedDomainObject` from a separate encoder/decoder of `LowerCaseString`.

**Comment by kmbt** [comment]
Come to think of it, does `Codec.struct` actually obey the laws? While decoding, it must discard keys which are not present in the declared shape. This breaks law number 2.

**Comment by patrickjcurran** [comment]
> Come to think of it, does `Codec.struct` actually obey the laws? While decoding, it must discard keys which are not present in the declared shape. This breaks law number 2.

I think you are right (well I think it's law 1 that breaks, not 2), _and_ it's similar to my case: In both, you are accepting a wider range of values and projecting onto a narrower "acceptable" range of values.

**Comment by mlegenhausen** [comment]
You should not set `=` equal to `===` von JavaScript, it is more like an `Eq` instance from `fp-ts` so a structure where you can define what equality means. If you define a type where casing doesn't matter so will your equality do not care about casing. If this is not what you want your codec is not correctly specified and this gives you a hint what you need to change. Please also note that it is totally ok to move the lower casing out of your `io-ts` type and do it a separate step to fulfill the laws.

**Comment by kmbt** [comment]
@mlegenhausen Thank you for clarification!
