### ISSUE TITLE
Suggestion: Enable GitHub sponsorship

### ISSUE THREAD

**Issue by silasdavis** [gcanti/io-ts#655]
I recently went on a sponsorship binge for some of my favourite libraries.

io-ts is one of my favourite libraries and I came here to see if I could sponsor you to recognise your outstanding work. If you would be open to sponsorship then I would be interested. You've done a lot for free, particularly on issues.

**Comment by gcanti** [comment]
Thanks @silasdavis, enabled on my profile

**Comment by silasdavis** [comment]
Great! I hope it makes a difference, added my personal coffee/month, will see what I could might manage in the way of corporate sponsorship...

**Comment by gcanti** [comment]
@silasdavis thank you!
