### ISSUE TITLE
non-enumerable records with extra keys do not pass `io-ts.record.is`, contrary to TypeScript types

### ISSUE THREAD

**Issue by tgfisher4** [gcanti/io-ts#704]
### Current Behavior

`io-ts.record` type does not agree with the TypeScript's `Record` type, which AFAICT is its express goal. The discrepancy arises specifically for "non-enumerable" records, as they are called in the `io-ts` source.
In the following example (source code is also copy-pasted under **Reproducible example**) — https://stackblitz.com/edit/node-tqqi5y?file=index.ts — this behavior is unexpected:
```typescript
NonEnumerableRecord.is(hasExtraNonEnumerable)
> false
E.isRight(NonEnumerableRecord.decode(hasExtraNonEnumerable))
> false
```

### Expected behavior

In the above example, I expect
```typescript
NonEnumerableRecord.is(hasExtraNonEnumerable)
> true
E.isRight(NonEnumerableRecord.decode(hasExtraNonEnumerable))
> true
```
since `hasExtraNonEnumerable` is assignable to `NonEnumerableRecord` at the type-level.

The latter expectation assumes that it is a general principle that `.decode` should succeed whenever `.is` does: is this correct?

### Reproducible example
https://stackblitz.com/edit/node-tqqi5y?file=index.ts
```typescript
import * as t from 'io-ts';
import * as E from 'fp-ts/Either';

// io-ts and TypeScript agree that enumerable records can have extra keys
const EnumerableRecord = t.record(
  t.keyof({ a: null, b: null }),
  t.literal('value')
);
type EnumerableRecord = t.TypeOf<typeof EnumerableRecord>;
type EnumerableWithExtra = { a: 'value'; b: 'value'; c: 'value' };
const hasExtraEnumerable = { a: 'value', b: 'value', c: 'value' } as const satisfies EnumerableWithExtra;
// Typescript considers an EnumerableWithExtra to be a valid EnumerableRecord
const extraExtendsEnumerable: EnumerableWithExtra extends EnumerableRecord
  ? true
  : false = true;
const enumerable: EnumerableRecord = hasExtraEnumerable;
// so does io-ts
console.log(
  `${JSON.stringify(hasExtraEnumerable)} ${
    EnumerableRecord.is(hasExtraEnumerable) ? 'is' : 'is not'
  } ${EnumerableRecord.name}`
);
console.log(
  `${JSON.stringify(hasExtraEnumerable)} ${
    E.isRight(EnumerableRecord.decode(hasExtraEnumerable)) ? 'is' : 'is not'
  } ${EnumerableRecord.name}`
);

// TypeScript allows non-enumerable records to have extra keys, too, but io-ts does not
const Prefixed = t.refinement( // I use refinement to avoid needing to decode all my string literal keys below
  t.string,
  (s): s is `prefix:${string}` => s.startsWith('prefix:'),
  '`prefix:${string}`'
);
const NonEnumerableRecord = t.record(Prefixed, t.literal('value'));
type NonEnumerableRecord = t.TypeOf<typeof NonEnumerableRecord>;
type NonEnumerableWithExtra = { 'prefix:foo': 'value'; bar: 'value' };
const hasExtraNonEnumerable = { 'prefix:foo': 'value', bar: 'value' } as const satisfies NonEnumerableWithExtra;
// Typescript considers NonEnumerableWithExtra to be a valid NonEnumerableRecord
// Indeed, this is consistent with the enumerable record behavior seen above
const extraExtendsNonEnumerable: NonEnumerableWithExtra extends NonEnumerableRecord
  ? true
  : false = true;
const nonEnumerable: NonEnumerableRecord = hasExtraNonEnumerable;
// However, io-ts does _not_ consider a NonEnumerableWithExtra to be a valid NonEnumerableRecord
console.log(
  `${JSON.stringify(hasExtraNonEnumerable)} ${
    NonEnumerableRecord.is(hasExtraNonEnumerable) ? 'is' : 'is not'
  } ${NonEnumerableRecord.name}`
);
console.log(
  `${JSON.stringify(hasExtraNonEnumerable)} ${
    E.isRight(NonEnumerableRecord.decode(hasExtraNonEnumerable))
      ? 'is'
      : 'is not'
  } ${NonEnumerableRecord.name}`
);
// control: io-ts accepts this record without the extra key
const noExtraNonEnumerable = { 'prefix:foo': 'value'};
console.log(
  `${JSON.stringify(noExtraNonEnumerable)} ${
    NonEnumerableRecord.is(noExtraNonEnumerable) ? 'is' : 'is not'
  } ${NonEnumerableRecord.name}`
);
```

### Suggested solution(s)

This code — https://github.com/gcanti/io-ts/blob/master/src/index.ts#L401 — should check only that any domain key `k` of the unknown record `u` which satisfies `domain.is(k)` also satisfies `codomain.is(u[k])`, rather than requiring this for _every_ key:
```typescript
return Object.keys(u).every((k) => !domain.is(k) || codomain.is(u[k]))
```
Happy to make a PR if this is indeed the correct behavior.

### Your environment

Which versions of io-ts are affected by this issue? Did this work in previous versions of io-ts?

Exact versions are also available in the linked stackblitz environment.
Looking through the blame on this code, I don't think this example has ever respected TypeScript types, as I've demonstrated them.

| Software   | Version(s) |
| ---------- | ---------- |
| io-ts      |  2.2.20 |
| fp-ts      |  2.16.1 |
| TypeScript |   5.3.2  |

**Comment by gcanti** [comment]
@tgfisher4 yeah, this is definitely a bug, both `is` and `decode` must be fixed

**Comment by tgfisher4** [comment]
@gcanti cool, I'm working on a PR to address this and want to discuss the ideal `nonEnumerableRecord.decode` behavior.

Currently, `enumerableRecord.decode` acts like `exact.decode` in that it strips keys outside the `domain`. Personally, I find this unexpected since
1. stripping keys outside the `domain` is not necessary to ensure the `decode`ing satisfies the corresponding `Record` type, since an object with keys outside the `domain` still satisfies the `Record` type, as demonstrated in my original post,
1. `type.decode` preserves keys outside the `props`, and `record` is similar in that it directly corresponds to a representable TypeScript type (vs `exact`, whose distinction from `type` is not representable at the TypeScript type-level), and
1. `enumerableRecord.encode` preserves keys outside the domain iff `codomain.encode === identity` (since, then, `enumerableRecord.encode === identity`).

In general, I'd expect the same philosophy as `type` — do the minimum work needed to ensure the `{en,de}code`ings match the expected types, i.e.:
 - `decode` verifies the `I` is a sensible shape and transforms it into an `A` according to `{domain,codomain}.decode`, but ignores extraneous keys, since those do not affect whether the `decode`ing satisfies `A`;
 - `encode` transforms the `A` into an `O` using `{domain,codomain}.encode`, but, again, ignores extraneous keys, since those do not affect whether the `encode`ing satisfies `O`.

So, should `nonEnumerableRecord.decode` strip extraneous keys for consistency with this (IMO unexpected) behavior of `enumerableRecord.decode`, or perhaps should these both ignore extraneous keys for consistency with `type`?

In case it wasn't clear, I'd prefer the latter, perhaps with the addition of supporting `exact(record(...))` to strip keys outside the `domain` when `{en,de}code`ing to emulate the current behavior of `enumerableRecord` and `exact(type(...))`. What do you think?

**Comment by tgfisher4** [comment]
@gcanti I see, so the general philosophy is instead that a `decode`ing should match `A` as closely as possible, with `type` being an historical exception. That clarifies the `decode` behavior, thanks!

Does the same apply for `encode`, i.e., an `encode`ing should match `O` as closely as possible, in particular by stripping keys outside the `domain` for `record` types? Currently, the behavior is inconsistent in that `enumerableRecord.encode` passes through extraneous keys iff `codomain.encode === identity`, since in this case `enumerableRecord.encode === identity`, while `nonEnumerableRecord.encode` always passes through extraneous keys (while, perhaps interestingly, still passing them through `domain.encode` if `!(domain.encode === identity && codomain.encode === identity)`).

**Comment by gcanti** [comment]
Regarding encoding and those checks on `identity`, those are optimization attempts, but I think they should be removed if they compromise correctness

**Comment by tgfisher4** [comment]
Gotcha, that's what I figured, thanks @gcanti.

#705 addresses this issue and is ready for review.

**Comment by alecgibson** [comment]
Actually a case where this change has actively broken similarity between TypeScript and `io-ts` is in another type we use, which makes use of [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html):

```ts
export function stringValidatorType(name: string, predicate: (u: string) => boolean): Type<string> {
  const is = (u: unknown): u is string => typeof u === 'string' && predicate(u);
  return new Type<string>(
    name,
    is,
    (u, c) => is(u) ? success(u) : failure(u, c),
    identity,
  );
}

export function prefixedStringType<T extends string>(prefix: T): Type<`${T}${string}`> {
  return stringValidatorType('PrefixedString', (u) => u.startsWith(prefix)) as Type<`${T}${string}`>;
};
```

Then a failing test case, that should actually pass:

```ts
it('builds a record', () => {
  const PrefixRecord = t.record(t.prefixedString('foo'), t.boolean);
  type IPrefixedRecord = t.TypeOf<typeof PrefixRecord>;
  const goodRecord: IPrefixedRecord = {
    foo_a: true,
  };

  expect(PrefixRecord.is(goodRecord)).to.be.true;
  const badRecord: IPrefixedRecord = {
    // @ts-expect-error :: TypeScript doesn't allow this bad prefix
    bar_a: true,
  };

  expect(PrefixRecord.is(badRecord)).to.be.false;
});
```

**Comment by alecgibson** [comment]
🤯 Okay TypeScript continues to surprise me every day!

In any case, is there a recommended out-of-the-box way to achieve what I was previously doing (incorrectly) with `t.record`? Or I need to build a custom codec?

**Comment by alecgibson** [comment]
@tgfisher4 thanks for the very thorough reply! 🙏🏼 

Since yesterday I did a bit more rummaging in the codebase and discovered `t.refinement`, which I really should have been using instead of our own hand-rolled wrapper.

It also got me to thinking that this behaviour really is sort of like a "record refinement" (if I understand the concept of "refinement" correctly: something that validates in a stricter way than TS might allow for? Which is what this whole conversation is about).

So I wonder if the most semantic, simple solution is something like:

```ts
export function refinedRecordType<D extends t.RefinementC<t.StringC>, C extends t.Mixed>(
  domain: D,
  codomain: C,
  name?: string,
): t.RefinementC<t.RecordC<D, C>> {
  return t.refinement(
    // Deliberately use t.string instead of domain to avoid io-ts stripping non-domain keys
    // before our predicate is run
    t.record(t.string, codomain, name),
    (a) => Object.keys(a).every(domain.is),
  ) as any;
}
```

It's a little bit ugly (it has some casting), and the errors are awful (since we're just relying on `true`/`false` logic), but I think it seems to do the job whilst staying vaguely understandable.
