### ISSUE TITLE
Type Parameters?

### ISSUE THREAD

**Issue by fabiandev** [gcanti/io-ts#71]
As I'm currently testing to use `io-ts` with [ts-runtime](https://github.com/fabiandev/ts-runtime) I was wondering, if generics are on the roadmap?

```ts
type Foo<T extends any = null> = {
  prop: T;
};

let foo: Foo<number> = { prop: 1 };
```

To validate the TypeScript code from above with, e.g., something like this in JavaScript:

```js
// const Foo = ...
let foo = t.validate({ prop: 1 }, t.get(Foo, t.number));
```

I'm trying to get as close as possible to TypeScript's static type check behavior at runtime with `ts-runtime` (which I still consider experimental, but I want to move it forward), and I think this library offers more flexibility to introduce custom types/features at a smaller footprint (than [flow-runtime](https://github.com/codemix/flow-runtime/tree/master/packages/flow-runtime)).

**Comment by gcanti** [comment]
> I was wondering, if generics are on the roadmap

No, AFAIK there's no way to implement them in a `TypeOf`-compatible way, i.e. define the runtime type and then extract the static type by using `TypeOf`. 

FWIW you can get something similar with a function though

```ts
import * as t from 'io-ts'

function foo<T extends t.Any>(type: T): t.InterfaceType<{ prop: T }> {
  return t.interface({
    prop: type
  })
}

const Foo = foo(t.number)
type Foo = t.TypeOf<typeof Foo>
/*
type Foo = {
    prop: number;
}
*/
```

**Comment by fabiandev** [comment]
Thanks @gcanti! I will experiment to see, if I can come up with something suitable for [ts-runtime](https://github.com/fabiandev/ts-runtime).
