### ISSUE TITLE
Cross-prop rules on interfaces

### ISSUE THREAD

**Issue by leemhenson** [gcanti/io-ts#72]
Is there a built-in way of defining a rule like `a < b` on an interface like this?

```ts
t.interface({
  a: t.refinement(t.Integer, (v, o) => v <= o.b),
  b: t.Integer,
})
```

I'm guessing if there is, it's not done as a refinement as `predicate` only gets one arg here:

https://github.com/gcanti/io-ts/blob/master/src/index.ts#L179

**Comment by gcanti** [comment]
Refinements can be defined on any type

```ts
const MyType = t.refinement(
  t.interface({
    a: t.Integer,
    b: t.Integer
  }),
  o => o.a < o.b
)
```

**Comment by leemhenson** [comment]
Oooooooh! I knew you'd have it covered, you magician you. 😀
