### ISSUE TITLE
Incorrect compile time type for dictionary

### ISSUE THREAD

**Issue by OliverJAsh** [gcanti/io-ts#75]
Given

``` ts
const Dic = t.dictionary(t.literal('foo'), t.string);
type DicT = t.TypeOf<typeof Dic>;

const dic: DicT = {
    foo: 'bar',
    baz: 'bob'
};
```

I expect this to error because `baz` in not an allowed property. `DicT` should be equivalent to `{ [key in 'foo']: string }` (mapped type with string literals), however it is equivalent to `{ [key: string]: string }`.

Is this intentional or can we fix it?

**Comment by gcanti** [comment]
@OliverJAsh thanks for reporting, just released a fix

**Comment by OliverJAsh** [comment]
Thank you!
