### ISSUE TITLE
better error messages from UnionTypes

### ISSUE THREAD

**Issue by leemhenson** [gcanti/io-ts#79]
Hola

I've got a a big `t.union` of several (~ 7) different large `t.interface` types. To make things more interesting, these are also wrapped up in an `t.array`. When I validate my incoming array against this schema, I get a validation failure. Because the union type doesn't know which of the types was the "right one" for the object being validated, it can't give me a descriptive path down through the object to the field where the problem was. I just get a `Invalid value { ...all the object } supplied to Array<( interfaceType1 | interfaceType2 | ... )>`. I'm looking at several screen's worth of output, non of which is particularly helpful for finding the one bit which is causing the problem.

Looking at `UnionType` it basically keeps validating the incoming value against each type in the union until it gets a `Right`. Then, if no `Right` was found, it returns that shallow list of `ValidationError`. What do you think about modifying it to collect each `ValidationError[]` for each type, and then returning all of them if the union can't find a match? You'd get _even more_ output on the screen, but at least you'd be able to figure out which set of errors you should be looking at for the source value, and then you'd be able to see the path through the value to the field that contained the cause of the validation failure. 

I'm gonna have a hack around but I thought I'd see if you had any bright ideas. 💡

**Comment by leemhenson** [comment]
Something like below. Excuse the mutation! 😅 

```
export class UnionType2<RTS extends [t.Any], U = t.TypeOf<RTS["_A"]>> implements t.Type<U> {
  // tslint:disable-next-line:variable-name
  public readonly _tag: "UnionType2" = "UnionType2";
  public readonly _A: U;
  public readonly validate: t.Validate<U>;
  constructor(readonly types: RTS, readonly name: string = `(${types.map(type => type.name).join(" | ")})`) {
    // tslint:disable-next-line:no-object-mutation no-expression-statement no-this
    this.validate = (v, c) => {
      const failures: t.ValidationError[] = [];

      // tslint:disable-next-line:prefer-for-of no-let
      for (let i = 0; i < types.length; i++) {
        const validation = types[i].validate(v, c);

        if (isRight(validation)) {
          return validation;
        } else {
          // tslint:disable-next-line:no-expression-statement no-object-mutation
          failures.push(
            ...validation.value.map(err => ({
              ...err,
              context: err.context.map((context, index) => ({
                ...context,
                type: (index === 0) ? types[i] : context.type,
              })),
          })));
        }
      }

      return new Left<t.ValidationError[], any>(failures);
    };
  }
}
```

**Comment by gcanti** [comment]
Errors contain all the relevant infos: values, keys and types.

Indeed reporters are designed as separate entities in order to allow customizations.

`PathReporter` is just a barebone example of reporter, but you can easily define your own

A quick hack:

```ts
import * as t from 'io-ts'
import { Reporter } from 'io-ts/lib/Reporter'

function getUnionMessage(value: any, type: t.UnionType<any>): string {
  // Excuse the mutation! :)
  let s = 'union ' + type.name
  s += '\n  Details:\n\n'
  s += type.types.map((type: any) => '    ' + LeemhensonReporter.report(t.validate(value, type))).join('\n')
  return s
}

function getContextPath(value: any, context: t.Context): string {
  return context
    .map(({ key, type }) => {
      const anytype = type as any
      if (anytype._tag === 'UnionType') {
        return getUnionMessage(value, anytype)
      }
      return `${key}: ${type.name}`
    })
    .join('/')
}

function getMessage(value: any, context: t.Context): string {
  return `Invalid value ${JSON.stringify(value)} supplied to ${getContextPath(value, context)}`
}

const LeemhensonReporter: Reporter<Array<string>> = {
  report: validation => validation.fold(errors => errors.map(e => getMessage(e.value, e.context)), () => ['No errors!'])
}

const Foo = t.interface(
  {
    foo: t.string
  },
  'Foo'
)

const Bar = t.interface(
  {
    bar: t.number
  },
  'Bar'
)

const FooBar = t.union([Foo, Bar], 'FooBar')

console.log(LeemhensonReporter.report(t.validate({}, FooBar)).join('\n'))
/*
Invalid value {} supplied to union FooBar
  Details:

    Invalid value undefined supplied to : Foo/foo: string
    Invalid value undefined supplied to : Bar/bar: number
*/
```

**Comment by leemhenson** [comment]
Yeah, but that incurs a second pass through all the validations which could be potentially expensive. Mind you, that second pass would only be in the case of validation failure, which _should_ be an exceptional circumstance for me..... 🤔  ok that works. Cheers! 🍻

**Comment by leemhenson** [comment]
Ah no, if I change some things in my code I can make this 1 pass. Super duper. 😄

**Comment by gcanti** [comment]
> that incurs a second pass through all the validations which could be potentially expensive

You are right, though isn't this for development purposes?

> Ah no, if I change some things in my code I can make this 1 pass

How? (if I can ask)

**Comment by leemhenson** [comment]
> How? (if I can ask)

I haven't tried this yet, but since I can know whether i'm validating against a union type or not, I can decide to use `t.validate` for non-union cases vs a custom `validate` fn for unions that does the 1 at a time version and aggregates batches of `ValidationError[]`. I think. 

> You are right, though isn't this for development purposes?

For "verbose" messaging mode, yeah. But I'm also using io-ts to validate at my service boundary in production too. I'm using a custom reporter to sanitize and minimize the log output in the case of failures there though.

**Comment by gcanti** [comment]
> I've got a a big t.union of several (~ 7) different large t.interface types

@leemhenson do the interface types build a tagged union? I ask because I'm experimenting with a `taggedUnion` combinator..

**Comment by leemhenson** [comment]
Yes, each interface has a `__typeTag` string literal on it that differentiates it from the others.
