### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by gyzerok** [gcanti/io-ts#8]
What do you think about having an ability to define default value. So if value is `null` or `undefined` it is got swapped with the value provided.

```ts
t.fromValidation(null, t.withDefault(t.string, 'hello world')) // 'hello world'
```

**Comment by gcanti** [comment]
I think that is already possible

```ts
function withDefault<T extends t.Any>(type: T, defaultValue: t.TypeOf<T>): t.Type<t.TypeOf<T>> {
  return new t.Type(
    type.name,
    (v, c) => type.validate(v != null ? v : defaultValue, c)
  )
}
```

**Comment by gyzerok** [comment]
Yeah, that make sense. I would try it as you described in my code and see if it's helpful. If it is, I guess we can discuss making it part of API.

**Comment by gunzip** [comment]
while this worked for property in partial types as well until 0.9.1, this does not validate / populate default values anymore in t.partial(s) because of some changes in 0.9.2. this was a breaking change for us :)

**Comment by gcanti** [comment]
@gunzip links are broken, could you please provide a test case?

**Comment by gcanti** [comment]
I think I got a repro

```ts
export function withDefault<T extends t.Any>(type: T, defaultValue: t.TypeOf<T>): t.Type<t.InputOf<T>, t.TypeOf<T>> {
  return new t.Type(
    `withDefault(${type.name}, ${JSON.stringify(defaultValue)})`,
    type.is,
    (v, c) => type.validate(v != null ? v : defaultValue, c),
    type.serialize
  )
}

const T1 = t.partial({
  name: withDefault(t.string, 'foo')
})

console.log(t.validate({}, T1).fold(() => 'error', a => JSON.stringify(a)))
// => `{}`
```

Related commit https://github.com/gcanti/io-ts/commit/37c74a5e2038de063a950f9ba8d18b1f132ef450

My opinion is that it's better to give a possibility to the passed type to perform a deserialization and, in case of failure, fallback to `undefinedType`. I'll revert that change.

**Comment by gunzip** [comment]
sorry, here are the correct links:

https://github.com/teamdigitale/digital-citizenship-functions/blob/master/lib/utils/default.ts

https://github.com/teamdigitale/digital-citizenship-functions/blob/master/lib/utils/__tests__/default.test.ts

**Comment by safareli** [comment]
This is the version for decoders that I use:

```

export function withDefault<T extends D.Decoder<unknown, unknown>>(
  decoder: T,
  defaultValue: D.TypeOf<T>
): D.Decoder<D.InputOf<T>, D.TypeOf<T>> {
  return D.union(
    decoder,
    pipe(
      undefinedDecoder,
      D.map(() => defaultValue)
    )
  );
}

export const undefinedDecoder = {
  decode: (val: unknown) => {
    return val === undefined
      ? D.success(undefined)
      : D.failure(val, "undefined");
  },
};
```
