### ISSUE TITLE
Embedded optional types?

### ISSUE THREAD

**Issue by jez9999** [gcanti/io-ts#83]
The documentation suggests making optional members of a type using intersection:

```
const MandatoryRunSettings = t.interface({
	appName: FilledString,
});

const OptionalRunSettings = t.partial({
	shortAppName: FilledString,
});

const RunSettings = t.intersection([MandatoryRunSettings, OptionalRunSettings]);
```

However this can start to look a bit ugly if you have lots of members of a type and want related members to be next to one another.  Could we implement an "optional" tag for types so that we can just associate that data with the type?  Then we could say something like:

```
const RunSettings = t.interface({
	appName: FilledString,
	shortAppName: t.OptionalType<FilledString>,
});
```

**Comment by gcanti** [comment]
AFAIK is not possible at the field level, see here for an explanation https://github.com/gcanti/io-ts/issues/56

**Comment by jez9999** [comment]
I posted a comment in #56, please respond.  I still don't see what the problem is with this.
