### ISSUE TITLE
Why is there no type t.object?

### ISSUE THREAD

**Issue by jez9999** [gcanti/io-ts#86]
When I'm making an interface I'd like to set a property to type `t.object` so that it ensures it is set to some object.  Why does `t.object` not exist?

**Comment by jez9999** [comment]
@gcanti Is there a technical reason why `t.object` isn't there or is it just an oversight?

**Comment by phiresky** [comment]
I think the typescript `object` type did not exist yet when this library was created (introduced in TS 2.2: https://blog.mariusschulz.com/2017/02/24/typescript-2-2-the-object-type)

**Comment by jez9999** [comment]
Sounds like there's no good reason not to add it now then?  Looks like it could pretty much copy/paste the string type and replace string with object.

**Comment by gcanti** [comment]
Indeed, when I first wrote io-ts it didn't exist. 

The difference from `{ [key: string]: any }` (i.e `Dictionary`) seems accessing by index which is not allowed. You can't even use `typeof` to refine

```ts
declare function f(x: { [key: string]: any }): void

f(1) // error
f('foo') // error
f(true) // error
f(null) // error
f(undefined) // error
f({}) // ok
f([]) // ok

declare function g(x: object): void

g(1) // error
g('foo') // error
g(true) // error
g(null) // error
g(undefined) // error
g({}) // ok
g([]) // ok

declare const x: { [key: string]: any }
declare const y: object

const xx = x['foo'] // ok
const yy = y['foo'] // error: Element implicitly has an 'any' type because type '{}' has no index signature.

const xxx = x.foo // ok
const yyy = y.foo // error: Property 'foo' does not exist on type 'object'

if (typeof y['foo'] !== 'undefined') { // error

}
```

**Comment by jez9999** [comment]
Can you add it?

**Comment by gcanti** [comment]
@jez9999 released

**Comment by jez9999** [comment]
Great!

**Comment by jez9999** [comment]
@gcanti Should a `t.interface` type be able to be used where a `t.object` is required?  TypeScript says the types are incompatible but since an interface is always implemented by an object, shouldn't it count as a `t.object`?

**Comment by phiresky** [comment]
A number can also fulfill an interface like {toString:function}

**Comment by jez9999** [comment]
Well is there a way for me to say "an interface fulfilled by an object" then?  That's the kind of semantics I want here.
