### ISSUE TITLE
Intersection return wrong results

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#90]
I found this counter intuitive behaviour:
```
const xBug = t .intersection([
  t.interface({
    foo: t.string
  }),
  t.map(
    content => ({ content }),
    t.interface({
      bar: t.number
    })
  )
])

const res = t.validate({ foo: 'rrr', bar: 23 }, xBug) // RESULT  {"content":{"foo":"rrr","bar":23}}
```
I wanted something like:
```
{ foo: 'rrr', content: { bar: 23 } }
```

My expectations would be to get something like:
```
{ foo: 'rrr', bar: 23, content: { foo: 'rrr', bar: 23 } }
```
Also the implementation seems sensible to the order of the Types.

**Comment by sledorze** [comment]
I'm wondering it the problem has not come from using `map` as it introduces more than just validation but changes the shape of the structures..

**Comment by sledorze** [comment]
More comment..
I've tried with 'merge' a modified version of interface which does something like 
```
vv => {
            changed = changed || vv !== t
            t = Object.assign({}, t, vv)
          }
```

I get my expected output but that immediately make me think we should maybe introduce another combinator which just filters out extraneous members.

**Comment by gcanti** [comment]
> I wanted something like: `{ foo: 'rrr', content: { bar: 23 } }`

Indeed, since

```ts
type T = t.TypeOf<typeof xBug>
/*
type T = {
  foo: string,
  content: {
    bar: number
  }
}
*/
```

the current behavior looks like a bug.

> I think the meaning of intersection should be clarified?

The intersection of runtime types is the runtime type of the intersection

```
Type<A> & Type<B> = Type<A & B>
```

> I'm wondering it the problem has not come from using map as it introduces more than just validation but changes the shape of the structures..

Keep in mind that, while you can trasform any runtime type, deserializations are meant to be performed in the leafs (e.g. DateFromISOString, DateFromMillis, etc...)

p.s.
`t.map` is deprecated and will be removed in the next version https://github.com/gcanti/io-ts/issues/53#issuecomment-343128355

**Comment by sledorze** [comment]
@gcanti ok removing the `map` operator makes this issue disappear, however, will there be some (new) 'builders' to easily create those leaf transformations? (I'm seeing the usage  of map / prism in io-ts-types which will both be deprecated (I can understand why)).

**Comment by gcanti** [comment]
> ok removing the map operator makes this issue disappear

I think there's actually a bug though.

> will there be some (new) 'builders' to easily create those leaf transformations?

What kind of transformation? Some more examples would help.

The example used in this issue doesn't look strictly related to deserialization and could be implemented as a normal function after validating the input

```ts
{ foo: string, bar: number } => { foo: string, content: { bar: number } }
```

> I'm seeing the usage of map / prism in io-ts-types

io-ts-types will be refactored accordingly

**Comment by sledorze** [comment]
@gcanti there's no bug, I was referring to the fact that removing non shape preserving operators will prevent that kind of issue.

As for transformations, I understand we should do that on leaves and yes, they can be done at a later stage.
