### ISSUE TITLE
Co/Contravariance

### ISSUE THREAD

**Issue by sledorze** [gcanti/io-ts#98]
I have a use case in our event driven framework where I need to return a decoder (type) knowing how to decode a part of the events handled at a more general level.
Ex: at general level all possible events are: A | B | C
I am interested into some of those, hence I want to decode only: A | B, so I'm returning that decoder to the framework.

Current implementation of Type do not permit one to use it co/contra variantly of only one of it's aspect (validation or serialisation).

```
interface A {
  a: string
}
interface B {
  b: string
}
import * as t from 'io-ts'

let tAB: t.Type<any, A | B> = 1 as any
let tA: t.Type<any, A> = 1 as any

tAB = tA // KO, because of serialize and that's correct

// One may be *only* interested into this:
const r: typeof tAB.validate = tA.validate // OK

// Let's introduce 'validator'
let vAB = validator(tAB)
let vA = validator(tA)

const myB: B = {
  b: 'b'
}
const myA: A = {
  a: 'a'
}
const myAB: A | B = myA as any

vAB = vA // OK <<<<---- that's how I want to send the decoder to the 'framework'
vA = vAB // KO
validateOnly(myA, vAB) // OK
validateOnly(myB, vAB) // OK (even if vA will reject it, it's part of the domain).
validateOnly(myAB, vAB) // OK

// Let's introduce 'serializer'
let sAB = serializer(tAB)
let sA = serializer(tA)

sAB = sA // KO
sA = sAB // OK
sA.serialize(myB) // KO
sA.serialize(myA) // OK
sA.serialize(myAB) // KO
```

Implementation
```
import { Either } from 'fp-ts/lib/Either'
import { Is, Validate, Serialize, Type, getDefaultContext, ValidationError } from 'io-ts'

export declare class ValidateType<S, A> {
  readonly name: string
  readonly is: Is<A> // <--- is is part of Validate.
  readonly validate: Validate<S, A>
  readonly _A: A
  pipe<B>(ab: ValidateType<A, B>, name?: string): ValidateType<S, B>
}

export declare class SerializeType<S, A> {
  readonly name: string
  readonly serialize: Serialize<S, A>
  readonly _S: S
  pipe<B>(ab: SerializeType<A, B>, name?: string): SerializeType<S, B>
}

export const validator = <I, O>(x: Type<I, O>): ValidateType<I, O> => x
export const serializer = <I, O>(x: Type<I, O>): SerializeType<I, O> => x

export const validateOnly = <I, O>(value: I, v: ValidateType<I, O>): Either<ValidationError[], O> =>
  v.validate(value, getDefaultContext(<Type<I, O>>v))
```
I think it that may be part of io-ts, also we could then change the type of 'io-ts' 'validate' function to get ride of proposed 'validateOnly'

**Comment by gcanti** [comment]
@sledorze IMO `is` should be in `SerializeType / Encoder`

```ts
export interface Decoder<S, A> {
  // prettier-ignore
  readonly '_A': A
  // prettier-ignore
  readonly '_S': S
  readonly name: string
  readonly validate: Validate<S, A>
}

export interface Encoder<S, A> {
  // prettier-ignore
  readonly '_A': A
  // prettier-ignore
  readonly '_S': S
  readonly is: Is<A>
  readonly serialize: Serialize<S, A>
}
```

**Comment by sledorze** [comment]
@gcanti ok for naming, they're way better!
As for putting 'is' inside 'SerializeType / Encoder'; that's not a great idea as having 'A' in that position breaks the variance we wanted to provide in the first place:
`sA = sAB // OK` no more works.
(also this applies for the `readonly '_A': A`part).

Two possibilities here:
- Keep is inside 'Decoder' and not Encoder.
- Provider a third interface to capture the 'is' pattern.

What do you think?

**Comment by gcanti** [comment]
@sledorze you are right, what if we keep it simple?

```ts
export interface Decoder<S, A> {
  readonly name: string
  readonly validate: Validate<S, A>
}

export interface Encoder<S, A> {
  readonly serialize: Serialize<S, A>
}

export class Type<S, A> implements Decoder<S, A>, Encoder<S, A> {
  ...
  asDecoder(): Decoder<S, A> {
    return this
  }
  asEncoder(): Encoder<S, A> {
    return this
  }
}  
```

The `is` function was introduced as a mean to define `serialize` for generic unions, I think it shouldn't be mentioned at all

> Is there/What are the reasons for not keeping the (handy) 'pipe' combinators?

Not sure, do you think is a good thing to create `Decoder`s / `Encoder`s instead of full fledged `Type`s?

(I'll put up a PR so we can reason looking at the code)

**Comment by sledorze** [comment]
@gcanti yes, that's a good and low risk start.

**Comment by gcanti** [comment]
https://github.com/gcanti/io-ts/releases/tag/0.9.2
